### ISSUE TITLE
Honor "required_fields" in flattened methods

### ISSUE THREAD

**Issue by chrisdunelm** [googleapis/gapic-generator#1048]
E.g. https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_gapic.yaml#L341
This should mean that all non-required flattened-method parameters can be passed null, which causes the relevant field(s) will be left unset on the request object.

- [ ] Java
- [x] C#

**Comment by eoogbe** [comment]
@chrisdunelm Can you add a priority to this?

**Comment by chrisdunelm** [comment]
This is done for C#, and I suspect also done for Java. @garrettjonesgoogle can you confirm.

**Comment by garrettjonesgoogle** [comment]
I don't think we have done this for Java - @michaelbausor do you know?

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if this is still needed, please reopen.
