### ISSUE TITLE
Oneofs and parameter flattening

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator#1057]
Consider a oneof with two options, both of which are strings - and which we want to include in parameter flattening. We definitely can't use overloads for that, as they're the same types.

Definitely an issue for Java and C# - not sure about Go.

We spotted this a while ago, decided (I think) to implement it using oneof types like we do for resource names, but I don't think that's been implemented.

Open question: do we _also_ stop using overloads for oneofs that currently contain different message types? [Example from Datastore](https://github.com/googleapis/googleapis/blob/817a594ddb8ded87708b7ca853ff2735f8128bf0/google/datastore/v1/datastore.proto#L116)

It's more convenient to use overloads with GqlQuery and Query, but then if the oneof is expanded again, that doesn't work any more.

This needs addressing before GA.

**Comment by bjwatson** [comment]
@jskeet I added the `Release Blocking` tag, since you said this needs to be addresed before GA.

**Comment by landrito** [comment]
Until we have a solution, the status quo causes a bug in method samples. 

Since the oneof fields will not be required the samples do not pass in a oneof field.

A temporary solution would be to add a sample code init field to the gapic yaml.

**Comment by pongad** [comment]
I think we should remove Go. Go doesn't implement any flattening.

**Comment by chrisdunelm** [comment]
https://github.com/googleapis/googleapis/pull/272 prepared to remove the datastore RunQuery flattenings that work-around the lack of proper oneof handling.
This will affect C#; do any/all other languages use gapic-generated datastore code?

**Comment by garrettjonesgoogle** [comment]
Java isn't using a GAPIC client for Datastore, so Java won't be affected.

**Comment by eoogbe** [comment]
@jskeet Can you add a priority to this?

**Comment by jskeet** [comment]
It's low priority until it's high priority, basically - we don't have any APIs that need it right now, but as soon as we do, we'll need to get it done. Setting to P2 for the moment.

**Comment by vchudnov-g** [comment]
@chrisdunelm Any updates on this (to meet our SLO)?

**Comment by noahdietz** [comment]
@chrisdunelm Any updates on this per our SLO?

**Comment by vchudnov-g** [comment]
@chrisdunelm Any updates on this? We're out of SLO.

**Comment by vchudnov-g** [comment]
@chrisdunelm Any updates on this? Feel free to close if this is now in the µ-generator domain.

**Comment by hzyi-google** [comment]
To sum up: implement this statement in AIP:

> An RPC can provide this annotation more than once to specify multiple signatures. Order matters here: In some situations, it may not be possible to generate an overload for every signature provided. In this situation, client library generators must follow a “first match wins” strategy (generate an overload for the first signature in the conflict set, and drop the rest).

**Comment by hkdevandla** [comment]
Obsolete since it is not the requirement now that oneoff needs to be flattened. Hence closing this.
