### ISSUE TITLE
Generated clients should contain a constant containing the audience / service URL

### ISSUE THREAD

**Issue by theacodes** [googleapis/gapic-generator#1058]
(Examples in Python, but applicable to all languages)

For authentication purposes, we should expose the audience / service URL (I'm not picky on name) as a constant in the client class, e.g.:

```python
>>> from google.cloud.gapic.pubsub.v1 import publisher_client
>>> publisher_client.PublisherClient.AUDIENCE
'https://pubsub.googleapis.com/google.pubsub.v1.Publisher'
```

The audience / service URL can be determined by:

```python
https://{SERVICE_ADDRESS}/{API_NAME}
```

Where SERVICE_ADDRESS is the existing constant [here](https://github.com/googleapis/api-client-staging/blob/d0682de146e60af7fe1084d8b1a9906c63e5050b/generated/python/gapic-google-cloud-pubsub-v1/google/cloud/gapic/pubsub/v1/publisher_client.py#L51) and API_NAME is the key [here](https://github.com/googleapis/api-client-staging/blob/d0682de146e60af7fe1084d8b1a9906c63e5050b/generated/python/gapic-google-cloud-pubsub-v1/google/cloud/gapic/pubsub/v1/publisher_client_config.json#L3). (As an aside, it's probably a good idea to expose API_NAME as well).

This is important for self-signed JWT authentication to gRPC services which requires the audience up-front. See the [gRPC system test](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/ab086899a00fe56303be39be5dec7ccfe0cd14b9/system_tests/test_grpc.py#L41) for the Python auth library.

**Comment by eoogbe** [comment]
@lukesneeringer Can you add a priority to this?

**Comment by eoogbe** [comment]
@jskeet @jba @garrettjonesgoogle @alexander-fenster @vam-google @lukesneeringer @geigerj Is this still relevant to your language? What is the priority?

**Comment by jonparrott** [comment]
This is less severe in Python because we do some cleverness in the auth library to not require the audience up-front.

**Comment by eoogbe** [comment]
This doesn't seem so hard to add, but I don't want to get into a situation where I send out a bunch of PRs and then people tell me why they aren't necessary. Want to make sure this feature is still relevant before I do anything.

**Comment by jskeet** [comment]
There is an ongoing internal discussion about using JWTs with gRPC-based Google APIs. I would suggest holding on until that's resolved. (I don't know much about JWT audiences myself. I know that for some APIs at least, you need to add scopes to the credentials in order to get them to work, but that's all I know...)

**Comment by hkdevandla** [comment]
Obsolete.
