### ISSUE TITLE
Pass list of common protos to toolkit via artman

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1113]
### What

The list of common protos is configured in https://github.com/googleapis/googleapis/blob/master/gapic/packaging/common_protos.yaml. Toolkit should have knowledge of this list.

### Why

We are duplicating logic by hardcoding common proto in toolkit code, e.g., https://github.com/googleapis/toolkit/pull/1053/files#r105066100. Having access to this configuration will also be useful once `toolkit` grpcMetadataGen is capable of generating metadata for the common protos packages.

### How

We can merge `common_protos.yaml` into the package config generated by `artman`.

**Comment by hzyi-google** [comment]
Obsolete.
