### ISSUE TITLE
Ruby: Generate rubocop config and make sure generated clients pass rubocop.

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator#1120]
Currently, when running the rubocop task on the generated client. Many errors are found. We should resolve this by doing two things: 

- [ ] Generate a custom rubocop.yml to make rubocop more reasonable for generated clients. This should be based on the rubocop.ymls already present in google-cloud-ruby.
- [ ] Make the generated code pass for the generated clients using the custom rubocop.yml
- [ ] Add rubocop rake task

**Comment by geigerj** [comment]
Bumping to P1 -- this is more important to have as we more forward with GAPIC-only releases.

**Comment by landrito** [comment]
Hey @geigerj, I think you did some work similar to this recently. Is this still relevant? If so, what is left to be done?

**Comment by geigerj** [comment]
Yup, still relevant. Unfortunately what I did recently was in the opposite direction; I excluded even more files from rubocop checking.

**Comment by geigerj** [comment]
Reducing to P2, as this does not qualify as "release blocking".

**Comment by hzyi-google** [comment]
Transferred to ruby microgenerator.
