### ISSUE TITLE
Implement oneof support for flattened methods in Java

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/gapic-generator#1149]
This is necessary for Seek in Pub/Sub.

**Comment by garrettjonesgoogle** [comment]
(as discussed in https://github.com/googleapis/toolkit/issues/1057 )

**Comment by eoogbe** [comment]
@pongad Can you add a priority to this?

**Comment by pongad** [comment]
@neozwu I think you're working on this? I don't think this is P1 anymore though.

**Comment by hkdevandla** [comment]
Obsolete.
