### ISSUE TITLE
Bidi streaming sample is misleading in some cases

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1215]
For APIs like Speech, interspersing calls to `write()` with calls to `read()` can block until timeout - the generated samples should reflect this.

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by vchudnov-g** [comment]
@michaelbausor Any updates?

**Comment by michaelbausor** [comment]
No update, this remains open and P2.

**Comment by vchudnov-g** [comment]
@michaelbausor Any updates (to meet our SLO)?

**Comment by noahdietz** [comment]
This issue is out of its SLO.

Reassigning this issue to @hzyi-google as it is a sample issue AFAICT. Please reassign if you feel this is not appropriately assigned.

**Comment by vchudnov-g** [comment]
@hzyi-google Any updates on this?

**Comment by hkdevandla** [comment]
Obsolete. So closing this.
