### ISSUE TITLE
Generate per-method wrappers for helper classes in PHP

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1223]
Assess whether we should generate per-method wrappers for paging, LRO and streaming response objects. This would allow us to generate correct type documentation, which will be helpful particularly for users of IDEs like PHPStorm

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if this is still needed, please reopen.
