### ISSUE TITLE
Python: Auto-gen Improvements

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#1320]
This is a "catch-all ticket" of things I have identified that need doing in Python auto-gen.
Examples in this ticket will follow Vision (which I have hand-edited).

More important items are marked with :warning:; this ticket should be demoted to P2 once those are completed.

### *_client.py (e.g. image_annotator_client.py)

  * [x] :warning: In docstrings, references to `string` should be spelled `str`.
  * [x] :warning: In docstrings, references to `iterator` should be spelled `Iterable`.
  * [x] Docstrings should use 4-space indents.
  * [x] Docstring class references should use the `~.` prefix if a period is present in the class name.
  * [x] In docstring examples, use `...` for the prompt in hanging indents or continued statements (match the interpreter).
  * [x] :warning: @landrito The `pkg_resources.get_distribution` call needs to use the "manual" package name (e.g. `google-cloud-vision`), not the GAPIC package name. We are moving away from publishing stand-alone GAPIC packages.
  * [x] :warning: @landrito Use the new Future class from @jonparrott.
      * This has its own issue: #1426. See also GoogleCloudPlatform/google-cloud-python#3764.

### *_client.json (e.g. image_annotator_client.json)

  * [x] Rename to `image_annotator_config.py`, and write the value to a variable in the top line. Alter the corresponding GAPIC Python file to import this rather than using `pkg_resources.resource_string` to load the JSON file.

### proto package

  * [x] :warning: @lukesneeringer Add `protoc-docs-plugin` to artman. (googleapis/artman#217)

### Partial Veneer

  * [x] :warning: @landrito Add a versioned directory in the `google.cloud` namespace (e.g. `google.cloud.vision_v1`)
  * [x] :warning: @landrito Add a `types.py` file to the `google.cloud.api_vN` package which iterates over all the `_pb2.py` files in the proto and makes the messages available in a consistent namespace (see Vision for a reference implementation).
  * [x] :warning: @landrito Add an `__init__.py` file to the `google.cloud.api_vN` package which imports (1) the client and (2) the enums module from the GAPIC, and (3) the `types` module (above bullet). These should be exported wholesale in `__all__`. See Vision for a reference implementation.
  * [x] :warning: @landrito Add an unversioned file (e.g. `vision.py`) in the `google.cloud` namespace that imports each of the names from the latest GA versioned package and exports them wholesale in `__all__`. See _Video Intelligence_ (not Vision) for a reference implementation.

### Docs

  * [x] :warning: @landrito Create a `gapic` directory in the docs with an `api.rst` and `types.rst` file. See Vision for a reference implementation.
  * [x] :warning: Create an `index.rst` file with the docs overview. See Vision for a reference implementation.

### setup.py and requirements.txt

  * [x] Remove `requirements.txt` entirely.
  * [x] :warning: Remove `oauth2client` from the dependency list in `setup.py`; add `google-auth` and `requests`.
        * ~@jonparrott -- please verify that this is correct.~ Done.
  * [x] Change the author from `jjg+google-cloud-python@google.com` to `googleapis-packages@google.com`.
  * [x] :warning: Remove dependencies on `proto-google-cloud-*`.
  * [x] :warning: Add `google.cloud.gapic`, `google.cloud.proto`, `google.cloud.gapic.{api}`, `google.cloud.proto.{api}` to `namespace_packages`.
  * [x] :warning: Add Python 3.6 to the list of tested Python versions.

### Tests

  * [x] Move tests out of their deeply nested subdirectory structure into simply `tests/gapic/vN`. Updated now that we have system tests: See #1401.
  * [x] :warning: Remove `tox.ini`, add appropriate `nox.py`.
  * [ ] Add tests for uncovered GAPIC lines.

### Protos

  * [ ] Add a `ref/` directory with the raw `proto` files; add this to `MANIFEST.in`.

**Comment by jonparrott** [comment]
Couple of thoughts:

1. I'm concerned about `gapic` (the term) being surfaced in the docs. 
2. add google-auth-client and requests. - it's `google-auth`.
3. `namespace_packages` this needs to be done with some care depending on which namespace package strategy you're using, please make me a review on this PR. Getting it wrong is disaster.

**Comment by lukesneeringer** [comment]
Affirmative re: the second two.

What is your concern about the first one? I am not surfacing the term in the docs themselves, only in the docs' _directory structure_.

The only difference is in the toctree, really:

```rst
.. toctree:
  :hidden:

  usage
  something_else
  gapic/api
  gapic/types
```

**Comment by jonparrott** [comment]
That's fine.

**Comment by landrito** [comment]
I think this has been resolved:
- Change the author from jjg+google-cloud-python@google.com to googleapis-packages@google.com.

https://github.com/googleapis/googleapis/blob/master/gapic/packaging/api_defaults.yaml#L19

**Comment by vchudnov-g** [comment]
@lukesneeringer Could you update this with what is still to do, and add a comment that you reviewed and updated?

**Comment by lukesneeringer** [comment]
Whups, sorry. This is done. (Not going to do that last item.)
