### ISSUE TITLE
Configure LRO client settings per-product

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1328]
### What

Currently client libraries that use LRO construct a LRO client within the product client. This LRO client retains the [settings configured in the `googleapis` repo](https://github.com/googleapis/googleapis/blob/19379991783c56a47ab4927a60ea47fb09afe8b8/gapic/api/artman_longrunning.yaml). We should allow this to be configured per-product.

This will likely require toolkit changes to propagate the per-product LRO configuration to GAX when GAX creates the LRO client.

### Why

Each product provides its own implementation of the LRO API, so the requirements on the API may be different. For example, Video Intelligence requires a >45s timeout on `GetOperation`, which is unique to that API.

cc: @lukesneeringer @garrettjonesgoogle

**Comment by bjwatson** [comment]
@geigerj Can you assign a priority and type?

**Comment by eoogbe** [comment]
@geigerj Is this still relevant?

**Comment by geigerj** [comment]
Yes, as far as I know no work was ever done here, and we worked around the Video Intelligence bug by increasing the timeouts for `GetOperation` across all APIs.

**Comment by andreamlin** [comment]
@lukesneeringer how are we handling this in the API config spec?

**Comment by hzyi-google** [comment]
As moving to annotations, this issue becomes won't fix.
