### ISSUE TITLE
FieldConfig code is poorly documented

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1353]
The code in https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/config/FieldConfig.java does not clearly explain the purpose of the `createMessageFieldConfig` and `getMessageFieldConfig` methods, and how a message field config differs from a field config in other contexts. This should be fixed either by refactoring or documentation.

cc @geigerj

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if this is still needed, please reopen.
