### ISSUE TITLE
Process links that are split across lines in proto file

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1362]
Links such as this one are not correctly processed: https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1beta1/cloud_speech.proto#L40

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by vchudnov-g** [comment]
@michaelbausor Is this still an issue?

**Comment by michaelbausor** [comment]
AFAIK this is not affecting any APIs, and a strong case exists that this problem should be fixed in the upstream proto instead of our generator. So we should close for now, and reopen if there is a need for us to handle this problem.
