### ISSUE TITLE
NodeJS: add the ability to black list words dynamically in the init code generator.

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator#1399]
# Context
When generating language, it generated a unit test that had the init code override one of the imports causing the test to fail. To alleviate this we should be able to pass in the import names to the init code generator to make it such that those words are blacklisted.

# Shortterm fix
A short term fix for language would be to append Service to the import name.

# Example
```js
  var language = require('../src');
  ...
  it('invokes analyzeSentiment without error', function(done) {
     var client = language.v1();

      // Mock request
      var document = {};
      var request = {
          document : document
      };

      // Mock response
      var language = 'language-1613589672';
      var expectedResponse = {
          language : language
      };

      // Mock Grpc layer
      client._analyzeSentiment = mockSimpleGrpcMethod(request, expectedResponse);

      client.analyzeSentiment(request, function(err, response) {
        assert.ifError(err);
        assert.deepStrictEqual(response, expectedResponse);
        done();
      });
    });
```

**Comment by landrito** [comment]
Regeneration for all the tests will be needed after this.

**Comment by eoogbe** [comment]
@landrito Can you add a priority to this?

**Comment by vchudnov-g** [comment]
@landrito @alexander-fenster Is this still an issue?

**Comment by landrito** [comment]
AFAIK this is probably still an issue, but I think this would be better handled in googleapis/gapic-generator-typescript rather than here. I assume theres a patch in synth-tool that handles the one or two cases this arises. Closing.
