### ISSUE TITLE
Strip html tags from proto documentation for PHP

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1409]
Html tags in proto documentation often make for poor documentation generated PHP docs. We should consider stripping them out and replacing them with something more appropriate if possible. It may be difficult to do this, given that the context could vary quite a lot for a particular tag.

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if this is still needed, please reopen.
