### ISSUE TITLE
Confusing error message for sample_code_init_fields

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1429]
### What

If a `sample_code_init_field` for a repeated field is missing the index, the validator produces a confusing error message.

For example,

```
- time_series[0].points.interval.end_time.seconds=1489504140
                 ^^^^^^
    should be points[0]
```

results in `java.lang.IllegalArgumentException: Could not assign value 'interval' to type uint64`, which is confusing: there is no value called "interval" in this configuration, and it's unclear what relevance "unit64" has to this config.

### Expected behavior

`java.lang.IllegalArgumentException: Repeated field 'points' is missing an index. Did you mean points[0]?`

**Comment by eoogbe** [comment]
@geigerj Can you add a priority to this?

**Comment by hzyi-google** [comment]
Obsolete.
