### ISSUE TITLE
Support DISABLED visibility in all languages

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1437]
We would like to support using the DISABLED visibility to hide methods that should not be in the generated GAPIC clients, such as [pubsub UpdateSnapshot](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L183)

cc @garrettjonesgoogle

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by lukesneeringer** [comment]
Why is this needed? I would expect the sanitized proto would not have anything with a visibility flag of `DISABLED`.

**Comment by garrettjonesgoogle** [comment]
The general usage for this feature is hiding something from a GAPIC client when you want the user to use a handwritten entry point for that particular feature instead. (This is what we use in Java for Pub/Sub.)

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if this is still needed, please reopen.
