### ISSUE TITLE
Make gapic/packaging/dependencies.yaml part of toolkit binary

### ISSUE THREAD

**Issue by ethanbao** [googleapis/gapic-generator#1450]
Context:
Today, toolkit is relying on {googleapis repo}/gapic/packaging/dependencies.yaml when generating the GAPIC packages. The value in that config file is strongly coupled with toolkit, and will cause toolkit-generated package to not build if the toolkit doesn't match dependencies.yaml in github repo. This coupling is problematic because we won't eventually expect all artman users to always use the latests artman (even if artman can be upgraded more often whenever toolkit gets major update).

Solution:
Move gapic/packaging/dependencies.yaml out of googleapis/googleapis repo and make it part of toolkit binary.

**Comment by ethanbao** [comment]
Garrett, temporarily assign this issue to you.

**Comment by garrettjonesgoogle** [comment]
This was done in https://github.com/googleapis/gapic-generator/pull/1984 plus https://github.com/googleapis/gapic-generator/pull/2010 .
