### ISSUE TITLE
Ensure argument type doc is on same line as argument

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1530]
### What

The `credentials` type doc needs to be on the same line as the argument name doc.

### Why

https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1698

> This change is needed to correct the GAPIC documentation by moving the types to the same line as the method argument. Otherwise the types will be defined as null in the JSON documentation files, and the angular app will puke on itself.

**Comment by vchudnov-g** [comment]
@landrito Is this fixed?

**Comment by landrito** [comment]
Looks like it!
