### ISSUE TITLE
Move Markdown -> RST conversion to pandoc

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#1587]
Right now, toolkit converts documentation from protos to the `*_client.py` files using some internal mechanism.

It should use pandoc (like protoc-docs-plugin does), so we are not having to roll our own. This would avoid errors like those encountered here: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4030/commits/6efa645e253754a88eee923480680c28fd34dc0e

**Comment by eoogbe** [comment]
@lukesneeringer Can you add a priority?

**Comment by lukesneeringer** [comment]
I thought we did not put priorities on enhancements, but yes. :-)

**Comment by michaelbausor** [comment]
Downgrading this to a P1 based on how it has been prioritized and the expected time until we can get https://github.com/googleapis/gapic-generator/pull/2108 merged (next week at the earliest). If this should still be P0, please bump it back up and we can try to get that PR merged sooner.

**Comment by theacodes** [comment]
This really does need to be P0. It's far and away the most toil-inducing bug for Python libraries.

**Comment by lukesneeringer** [comment]
Okay, let's figure out if we can get this done ASAP then.
I know @eoogbe attempted to do this and ran into some kind of issue, but I am unfamiliar with what the issue was. Let me circle back and find out what we can do.

**Comment by michaelbausor** [comment]
I will investigate today and provide an ETA

**Comment by michaelbausor** [comment]
Looking into switching to pandoc and the changes in #2108, it isn't clear (a) how to quickly proceed, or even (b) that switching to pandoc will solve the problem.

@theacodes @crwilcox I want to figure out exactly what you need for this to be fixed. It seems like there is a huge gulf between what is generated now, and the massive amounts of post-processing required for e.g. DLP (see [this PR](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5815)).

If we can figure out some set of requirements, I'll go ahead and implement them ASAP, which seems likely to be faster than integrating pandoc.

**Comment by theacodes** [comment]
We need the gapic generator to *always* produce docstrings that contain valid RST. Any invalid RST markup will bork our documentation. Using a better markdown -> rst translator (like `pandoc`) will almost certainly solve the issue.

**Comment by michaelbausor** [comment]
Update: Here is an attempt to apply pandoc (via pypandoc) in artman to the proto comments before they are processed by gapic-generator: https://github.com/googleapis/artman/pull/499

**Comment by theacodes** [comment]
If you're looking for a stress test, it seems Spanner is the worst offender by far: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/6040/commits/76f1cd3d1081f8aee6eca7efb70a8d00678e9fa6

**Comment by landrito** [comment]
@michaelbausor, any updates on this?

**Comment by michaelbausor** [comment]
@landrito the current PR (https://github.com/googleapis/artman/pull/499) seems reasonable, and generates valid rst comments for Spanner. I need to follow up with a gapic-generator PR and then get review/approval on both PRs.
