### ISSUE TITLE
Node.js: Fix @namespace declarations.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#1616]
Reference: https://github.com/googleapis/toolkit/pull/1614/files/986573343ff7d0ecded8e9a8b545bfe17e8df61d#r144363773

It should follow the proto path. Related to #1597; implementing it may supercede this.

**Comment by eoogbe** [comment]
@lukesneeringer @landrito Can you add a priority?

**Comment by vchudnov-g** [comment]
@landrito Update or close

**Comment by landrito** [comment]
I think we'll eventually handle this in gapic-generator-typescript:

https://github.com/googleapis/gapic-generator-typescript/pull/1/files#r227545467
