### ISSUE TITLE
Fail early if there is a missing method config for a method.

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator#1648]
## What

We encountered an issue where nodejs would fail if there was not a method config for a method whereas ruby and python would generate a client with the method in question missing. This should be changed to fail with a list of methods without config if any are missing.

cc @lukesneeringer @geigerj

**Comment by garrettjonesgoogle** [comment]
I'm wondering if we should stop enforcing this in toolkit and depend on enforcement upstream. In toolkit, we could just skip generation of methods that aren't configured.

**Comment by geigerj** [comment]
@garrettjonesgoogle I think this eventually belongs in the config advisor that @eoogbe is building (as part of toolkit). I am hoping the will config advisor will consolidate most of this validation logic that's currently floating around in the transformers and in the  `com.google.api.codegen.config.*Config` classes.

**Comment by garrettjonesgoogle** [comment]
Another option is allowing for two modes, strict (fail when a method isn't configured) and non-strict (allow unconfigured methods). A non-strict mode would be very nice for doing development work.

**Comment by eoogbe** [comment]
The plan for the config adviser is to eventually replace all the validation logic from the `com.google.api.codegen.config.*Config` classes. It will check that all the IDL methods are defined and that there a no duplicate or extra methods.

**Comment by eoogbe** [comment]
Will be replaced by proto-based config format
