### ISSUE TITLE
Node.js - Enums are not properly documented in generated proto JSDoc files.

### ISSUE THREAD

**Issue by jmdobry** [googleapis/gapic-generator#1666]
See googleapis/nodejs-firestore#50

**Comment by eoogbe** [comment]
@alexander-fenster What is the priority?

**Comment by vchudnov-g** [comment]
As per https://github.com/googleapis/nodejs-firestore/issues/50, this appears to be solved now.

**Comment by vchudnov-g** [comment]
As per https://github.com/googleapis/nodejs-firestore/issues/50, this appears to be solved now.
