### ISSUE TITLE
java: consider rewording client doc

### ISSUE THREAD

**Issue by pongad** [googleapis/gapic-generator#1685]
Feedback from @domesticmouse on a generated client for currently-Google-internal API. Reproduced here with permission.

Both points concern text generated from [java/main.snip](https://github.com/googleapis/toolkit/blob/master/src/main/resources/com/google/api/codegen/java/main.snip)

> This class provides the ability to make remote calls to the backing service through method calls that map to API methods. Sample code to get started:

Please replace "backing service" with "API". Everything behind the exposed API is invisible to the client library user.

> The surface of this class includes several types of Java methods for each of the API's methods

Consider: This class includes several Java methods for each API endpoint:

I can pick this up if @garrettjonesgoogle and  @jabubake agree with the change.

**Comment by garrettjonesgoogle** [comment]
Maybe this instead:

"This class issues calls to the API methods of the underlying API."

**Comment by eoogbe** [comment]
"This class issues calls to the methods of the underlying API." Probably don't want to repeat API

**Comment by eoogbe** [comment]
@pongad Can you add a priority?

**Comment by hkdevandla** [comment]
Obsolete.
