### ISSUE TITLE
Ruby: Smoke tests should use standard google cloud env variables for cloud APIs

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1704]
### What

Currently the Ruby rake smoke test task attempts to use the environment variable `SMOKE_TEST_PROJECT` to determine the project to use when running smoke tests. For non-cloud APIs, that's a fine default, but if we know it's a cloud API, we should use `GCLOUD_TEST_PROJECT || {API}_TEST_PROJECT`.

### Why

Consistency with existing APIs in google-cloud-ruby.

**Comment by geigerj** [comment]
`{API}_TEST_PROJECT` is now accepted. Reclassify as enhancement to support `GCLOUD_TEST_PROJECT`.

**Comment by jbolinger** [comment]
No longer relevant given the customizations available in https://github.com/googleapis/gapic-generator-ruby.
