### ISSUE TITLE
SSL version of sample app build.gradle is too old

### ISSUE THREAD

**Issue by pongad** [googleapis/gapic-generator#1711]
Currently the SSL is hardcoded to `io.netty:netty-tcnative-boringssl-static:1.1.33.Fork26`.
This doesn't work with the latest gax and throws exception at runtime.

**Comment by andreamlin** [comment]
@pongad Can you confirm this is still an issue?

**Comment by pongad** [comment]
We use netty shaded now so this is no longer a problem.
