### ISSUE TITLE
Setup hook to trigger artman auto build

### ISSUE THREAD

**Issue by ethanbao** [googleapis/gapic-generator#1715]
Whenever a toolkit commit gets submitted, make a change to artman Dockerfile (https://github.com/googleapis/artman/blob/master/Dockerfile#L176). When that change gets merged to artman/master, a new artman Docker image will be automatically built and published if all tests pass.

**Comment by eoogbe** [comment]
@garrettjonesgoogle Can you add a priority?

**Comment by vchudnov-g** [comment]
Closing as we are moving away from artman
