### ISSUE TITLE
Artman code generation: can't configure channel size

### ISSUE THREAD

**Issue by kmjung** [googleapis/gapic-generator#1732]
(copied from https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2675)

I use artman to generate Java client libraries for my gRPC-based service. Specifically, I'm using the googleapis and toolkit versions from this commit: googleapis/artman@d065fbb

My service interface requires that I increase the inbound message size up to 10 mb. However, it doesn't appear that this option is supported currently in artman / gapic -- I had to manually edit the emitted code to make this work.

**Comment by kmjung** [comment]
See https://github.com/googleapis/google-cloud-java/pull/4022/commits/17ca4c7c65d41cbfea1c7d79124008a51314c74a

**Comment by hzyi-google** [comment]
Looks it still applies to bazel generation.

**Comment by miraleung** [comment]
Marking this as obsolete since artman is now deprecated.
