### ISSUE TITLE
Latest release candidate of artman breaks toolkit GAPIC config parsing

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1736]
I've noticed the latest release candidate of artman seems to ignore the configured package in the GAPIC config. For example, Ruby's LRO package is incorrectly parsed as `Google::Cloud::Longrunning` instead of `Google::Longrunning`; VideoIntelligence as `Google::Cloud::Videointelligence` instead of `Google::Cloud::VideoIntelligence`. I suspect the config advisor is passing the GAPIC generator default values instead of configured values.

### Repro case:

Latest stable version of artman:

```
$ artman --config google/longrunning/artman_longrunning.yaml generate ruby_gapic
...
$ find artman-genfiles/ruby/google-cloud-ruby/ -name "operations*rb"
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/longrunning/operations_pb.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/longrunning/operations_client.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/longrunning/doc/google/longrunning/operations.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/longrunning/operations_services_pb.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/test/google/longrunning/operations_client_test.rb
```

`artman:0.5.4-rc01`:

```
$ artman --config google/longrunning/artman_longrunning.yaml --image googleapis/artman:0.5.4-rc01 generate ruby_gapic
$ find artman-genfiles/ruby/google-cloud-ruby/ -name "operations*rb"
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/longrunning/operations_pb.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/longrunning/operations_services_pb.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/cloud/longrunning/operations_client.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/lib/google/cloud/longrunning/doc/google/longrunning/operations.rb
artman-genfiles/ruby/google-cloud-ruby/google-cloud-longrunning/test/google/cloud/longrunning/operations_client_test.rb
```

cc: @eoogbe @ethanbao

**Comment by geigerj** [comment]
I am going to see if I can workaround by selectively reverting ConfigAdvisor changes to `CodeGeneratorApi`.

**Comment by geigerj** [comment]
Selectively reverted ConfigAdvisor changes to `CodeGeneratorApi` in #1737. Downgrade to P2 and reassign for investigation of root cause.

**Comment by eoogbe** [comment]
The reverted generation of `ConfigProto` from `ConfigNode` didn't work properly when used with multiple config files. It merged each file's `ConfigNode` with the IDL independently before merging the generated `ConfigProto`s with each other. This ordering doesn't work when the main config file gets read before a simple config file with lots of defaults overrides it.

The fix is to merge the `ConfigNode`s before merging with the IDL and passing only one config node to the `MessageGenerator`. To implement this fix, we first need to have the discogapic config merging in place (#1726).

**Comment by eoogbe** [comment]
Will be replaced by proto-based input format
