### ISSUE TITLE
Use version constant checked in to version control instead of dynamically loading gem metadata

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1749]
### What

When setting version in the GCCL headers, instead of

```
Gem.loaded_specs['{api}'].version.version
```

use

```
Google::{API}::VERSION
```

This, of course, requires generating a `Google::{API}::VERSION`.

### Context

https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1881#discussion_r157274655

**Comment by jbolinger** [comment]
Done in https://github.com/googleapis/gapic-generator-ruby.
