### ISSUE TITLE
Add configuration for whitelist-only methods

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1755]
### Context

Bigtable added EAP methods to their public protos. See: https://github.com/googleapis/googleapis/blob/546d3afd75187e65229a2670eb440e84a05f5d9d/google/bigtable/v2/bigtable.proto#L86

### What

APIs may have features or methods in their IDL that are only accessible to certain, whitelisted users. In some cases, it may be desirable for client libraries to annotate such methods, or guard them with feature flags, etc. To do so, we should introduce an additional method annotation to the GAPIC config. The semantics of this annotation may vary based on what is idiomatic in a particular client library language.

### Why

It is a poor user experience for methods to be available on the client object that generally do not work for most customers.

**Comment by hzyi-google** [comment]
@hkdevandla It's somewhat related to how we are going to support googleapis_private... so bringing this to your attention for you to decide whether to proceed.

**Comment by hkdevandla** [comment]
This will be not be supported.
