### ISSUE TITLE
Restore `types` property with raw proto contents

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/gapic-generator#1756]
*This issue inspired by https://github.com/googleapis/nodejs-vision/issues/17*

As explained in the issue above, in pre-GAPIC Node.js API client libraries, we had a `types` property exposed directly from the module:

```js
const types = require('@google-cloud/vision').types;
```

Expand to see the contents of `types`:

<details>
<pre>
{ Vertex: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  BoundingPoly: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  Position: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  TextAnnotation: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function],
     DetectedLanguage: 
      { [Function: Message]
        encode: [Function],
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function],
        decodeJSON: [Function] },
     DetectedBreak: 
      { [Function: Message]
        encode: [Function],
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function],
        decodeJSON: [Function],
        BreakType: [Object] },
     TextProperty: 
      { [Function: Message]
        encode: [Function],
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function],
        decodeJSON: [Function] } },
  Page: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  Block: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function],
     BlockType: { UNKNOWN: 0, TEXT: 1, TABLE: 2, PICTURE: 3, RULER: 4, BARCODE: 5 } },
  Paragraph: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  Word: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  Symbol: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  WebDetection: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function],
     WebEntity: 
      { [Function: Message]
        encode: [Function],
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function],
        decodeJSON: [Function] },
     WebImage: 
      { [Function: Message]
        encode: [Function],
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function],
        decodeJSON: [Function] },
     WebPage: 
      { [Function: Message]
        encode: [Function],
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function],
        decodeJSON: [Function] } },
  Feature: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function],
     Type: 
      { TYPE_UNSPECIFIED: 0,
        FACE_DETECTION: 1,
        LANDMARK_DETECTION: 2,
        LOGO_DETECTION: 3,
        LABEL_DETECTION: 4,
        TEXT_DETECTION: 5,
        DOCUMENT_TEXT_DETECTION: 11,
        SAFE_SEARCH_DETECTION: 6,
        IMAGE_PROPERTIES: 7,
        CROP_HINTS: 9,
        WEB_DETECTION: 10 } },
  ImageSource: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  Image: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  FaceAnnotation: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function],
     Landmark: 
      { [Function: Message]
        encode: [Function],
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function],
        decodeJSON: [Function],
        Type: [Object] } },
  LocationInfo: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  Property: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  EntityAnnotation: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  SafeSearchAnnotation: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  LatLongRect: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  ColorInfo: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  DominantColorsAnnotation: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  ImageProperties: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  CropHint: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  CropHintsAnnotation: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  CropHintsParams: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  ImageContext: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  AnnotateImageRequest: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  AnnotateImageResponse: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  BatchAnnotateImagesRequest: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  BatchAnnotateImagesResponse: 
   { [Function: Message]
     encode: [Function],
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     decodeJSON: [Function] },
  Likelihood: 
   { UNKNOWN: 0,
     VERY_UNLIKELY: 1,
     UNLIKELY: 2,
     POSSIBLE: 3,
     LIKELY: 4,
     VERY_LIKELY: 5 },
  ImageAnnotator: 
   { [Function: ServiceClient]
     super_: [Function: Client],
     service: { batchAnnotateImages: [Object] } } }
</pre>
</details>

We can restore *similar* functionality by adding a loop over the proto file from the generated file (e.g. https://github.com/googleapis/nodejs-vision/blob/master/src/v1/index.js):

```js
const ImageAnnotatorClient = require('./image_annotator_client');
const grpc = require('google-gax').grpc();
const path = require('path');

module.exports.ImageAnnotatorClient = ImageAnnotatorClient;

module.exports.types = grpc.loadProto(
  path.join(__dirname, '..', '..', 'protos'),
  `google/cloud/vision/v1/image_annotator.proto`
).google.cloud.vision.v1;
```

This gives us a bit weirder of a response, though:

<details>
<pre>
{ ImageAnnotator: 
   { [Function: ServiceClient]
     super_: [Function: Client],
     service: { batchAnnotateImages: [Object] } },
  Feature: 
   { Type: 
      Enum {
        options: undefined,
        name: 'Type',
        parent: [Type],
        resolved: false,
        comment: null,
        filename: 'C:\\Users\\sawch\\dev\\play\\gcloud-1513804175\\node_modules\\@google-cloud\\vision\\protos\\google\\cloud\\vision\\v1\\image_annotator.proto',
        valuesById: [Object],
        values: [Object],
        comments: [Object],
        reserved: undefined } },
  ImageSource: {},
  Image: {},
  FaceAnnotation: { Landmark: { Type: [Enum] } },
  LocationInfo: {},
  Property: {},
  EntityAnnotation: {},
  SafeSearchAnnotation: {},
  LatLongRect: {},
  ColorInfo: {},
  DominantColorsAnnotation: {},
  ImageProperties: {},
  CropHint: {},
  CropHintsAnnotation: {},
  CropHintsParams: {},
  ImageContext: {},
  AnnotateImageRequest: {},
  AnnotateImageResponse: {},
  BatchAnnotateImagesRequest: {},
  BatchAnnotateImagesResponse: {},
  Likelihood: 
   Enum {
     options: undefined,
     name: 'Likelihood',
     parent: 
      Namespace {
        options: [Object],
        name: 'v1',
        parent: [Namespace],
        resolved: false,
        comment: null,
        filename: null,
        nested: [Object],
        _nestedArray: null,
        ImageAnnotator: [Service],
        Feature: [Type],
        ImageSource: [Type],
        Image: [Type],
        FaceAnnotation: [Type],
        LocationInfo: [Type],
        Property: [Type],
        EntityAnnotation: [Type],
        SafeSearchAnnotation: [Type],
        LatLongRect: [Type],
        ColorInfo: [Type],
        DominantColorsAnnotation: [Type],
        ImageProperties: [Type],
        CropHint: [Type],
        CropHintsAnnotation: [Type],
        CropHintsParams: [Type],
        ImageContext: [Type],
        AnnotateImageRequest: [Type],
        AnnotateImageResponse: [Type],
        BatchAnnotateImagesRequest: [Type],
        BatchAnnotateImagesResponse: [Type],
        Likelihood: [Object],
        Vertex: [Type],
        BoundingPoly: [Type],
        Position: [Type],
        TextAnnotation: [Type],
        Page: [Type],
        Block: [Type],
        Paragraph: [Type],
        Word: [Type],
        Symbol: [Type],
        WebDetection: [Type] },
     resolved: false,
     comment: null,
     filename: 'C:\\Users\\sawch\\dev\\play\\gcloud-1513804175\\node_modules\\@google-cloud\\vision\\protos\\google\\cloud\\vision\\v1\\image_annotator.proto',
     valuesById: 
      { '0': 'UNKNOWN',
        '1': 'VERY_UNLIKELY',
        '2': 'UNLIKELY',
        '3': 'POSSIBLE',
        '4': 'LIKELY',
        '5': 'VERY_LIKELY' },
     values: 
      { UNKNOWN: 0,
        VERY_UNLIKELY: 1,
        UNLIKELY: 2,
        POSSIBLE: 3,
        LIKELY: 4,
        VERY_LIKELY: 5 },
     comments: 
      { UNKNOWN: null,
        VERY_UNLIKELY: null,
        UNLIKELY: null,
        POSSIBLE: null,
        LIKELY: null,
        VERY_LIKELY: null },
     reserved: undefined },
  Vertex: {},
  BoundingPoly: {},
  Position: {},
  TextAnnotation: 
   { DetectedLanguage: {},
     DetectedBreak: { BreakType: [Enum] },
     TextProperty: {} },
  Page: {},
  Block: 
   { BlockType: 
      Enum {
        options: undefined,
        name: 'BlockType',
        parent: [Type],
        resolved: false,
        comment: null,
        filename: 'C:\\Users\\sawch\\dev\\play\\gcloud-1513804175\\node_modules\\@google-cloud\\vision\\protos\\google\\cloud\\vision\\v1\\text_annotation.proto',
        valuesById: [Object],
        values: [Object],
        comments: [Object],
        reserved: undefined } },
  Paragraph: {},
  Word: {},
  Symbol: {},
  WebDetection: { WebEntity: {}, WebImage: {}, WebPage: {} } }
</pre>
</details>

To use one property as an example, `Likelihood`, here's what we want (old functionality):

```js
types.Likelihood;
{
  UNKNOWN: 0,
  VERY_UNLIKELY: 1,
  UNLIKELY: 2,
  POSSIBLE: 3,
  LIKELY: 4,
  VERY_LIKELY: 5
}
```

... and what we get with my code above:

```js
types.Likelihood;
{
  options: undefined,
  name: 'Likelihood',
  parent: {
    options: [Object],
    name: 'v1',
    parent: [Namespace],
    resolved: false,
    comment: null,
    filename: null,
    nested: [Object],
    _nestedArray: null,
    ImageAnnotator: [Service],
    Feature: [Type],
    ImageSource: [Type],
    Image: [Type],
    FaceAnnotation: [Type],
    LocationInfo: [Type],
    Property: [Type],
    EntityAnnotation: [Type],
    SafeSearchAnnotation: [Type],
    LatLongRect: [Type],
    ColorInfo: [Type],
    DominantColorsAnnotation: [Type],
    ImageProperties: [Type],
    CropHint: [Type],
    CropHintsAnnotation: [Type],
    CropHintsParams: [Type],
    ImageContext: [Type],
    AnnotateImageRequest: [Type],
    AnnotateImageResponse: [Type],
    BatchAnnotateImagesRequest: [Type],
    BatchAnnotateImagesResponse: [Type],
    Likelihood: [Object],
    Vertex: [Type],
    BoundingPoly: [Type],
    Position: [Type],
    TextAnnotation: [Type],
    Page: [Type],
    Block: [Type],
    Paragraph: [Type],
    Word: [Type],
    Symbol: [Type],
    WebDetection: [Type]
  },
  resolved: false,
  comment: null,
  filename: 'C:\\Users\\sawch\\dev\\play\\gcloud-1513804175\\node_modules\\@google-cloud\\vision\\protos\\google\\cloud\\vision\\v1\\image_annotator.proto',
  valuesById: {
    '0': 'UNKNOWN',
    '1': 'VERY_UNLIKELY',
    '2': 'UNLIKELY',
    '3': 'POSSIBLE',
    '4': 'LIKELY',
    '5': 'VERY_LIKELY'
  },
  values: {
    UNKNOWN: 0,
    VERY_UNLIKELY: 1,
    UNLIKELY: 2,
    POSSIBLE: 3,
    LIKELY: 4,
    VERY_LIKELY: 5
  },
  comments: {
    UNKNOWN: null,
    VERY_UNLIKELY: null,
    UNLIKELY: null,
    POSSIBLE: null,
    LIKELY: null,
    VERY_LIKELY: null
  },
  reserved: undefined
}
```

I would guess this is due to an underlying change in protobuf-- is there any way to restore the original functionality?

**Comment by stephenplusplus** [comment]
cc @lukesneeringer (original implementer, I believe) && @alexander-fenster

**Comment by JustinBeckwith** [comment]
*gentle ping* @alexander-fenster @timburks

**Comment by nicolasgarnier** [comment]
one more gentle ping :) This is preventing us from upgrading to newer versions of the Cloud Vision SDK in codelabs and open source sample apps because there is no more ways to compare Likelhoods.

**Comment by fenixsolorzano** [comment]
Will there be any @types anytime soon?😅

**Comment by andreamlin** [comment]
@alexander-fenster Would you mind responding to this issue?
Feel free to justify downgrading the priority.

**Comment by alexander-fenster** [comment]
OK so two issues here. @fenixsolorzano, I believe you're talking about TypeScript typings, that we are working on and expect to release the first versions this quarter :)

@andreamlin @stephenplusplus @JustinBeckwith, re: exposing Protobuf types, since we're going to replace JavaScript gapic-generator with a new TypeScript generator, I will take care of that in the scope of that new generator. We'll leave this issue open for now and I'll transfer it to TypeScript generator repository soon.

**Comment by andreamlin** [comment]
@alexander-fenster Can you update that with the timeline for the TypeScript generator to be used in production?

**Comment by alexander-fenster** [comment]
We plan to have alpha (= generate some APIs) by the end of Q1'18, and beta (= generate most APIs) by the end of Q2'18.

**Comment by jbolinger** [comment]
@alexander-fenster any updates based on your progress with the new generator?

**Comment by fenixsolorzano** [comment]
@alexander-fenster About **TypeScript typings**, is there another issue about that? I want to subscribe to that issue to be notified about it's completion

**Comment by vchudnov-g** [comment]
@alexander-fenster Could you provide an update and/or lower the priority if that makes sense?

**Comment by vchudnov-g** [comment]
@alexander-fenster We're out of SLO for this issue. Could provide an update and/or lower the priority?

**Comment by alexander-fenster** [comment]
I'm going to close this now since (a) we're moving to TypeScript with all the types available, happens this/next quarter, and (b) this is going to be WONTFIX for the current generator.
