### ISSUE TITLE
Generate resource names from proto

### ISSUE THREAD

**Issue by eoogbe** [googleapis/gapic-generator#1783]
In order to simplify the gapic config generation process for API producers, we should generate the resource names from proto. Discogapic already fills in the `resource_name_generation` fields, so we should match that feature when generating from proto.

**Comment by andreamlin** [comment]
hopefully this will become outdated or refiled when the API config spec goes live

**Comment by eoogbe** [comment]
Deprecating the gapic config, so closing this issue
