### ISSUE TITLE
Python: Markdown conversion issue.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#1786]
There is an issue converting documentation from Markdown to ReST when the documentation is offering a literal backtick: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/78dc4b0475f9dff491bd4e375a19d6b8dab02bd8

This is most likely a problem in pandoc.
Action items: prove that, then post a bug there.

**Comment by jonparrott** [comment]
See also https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4695/commits/a44f6ceff101b338ae5c3e1718b378887ec6fd12

**Comment by noahdietz** [comment]
Hi any updates here (per our SLO)? There seem to be several other python-related documentation issues (#2159 #401 #2449). Maybe they could be tackled together?

**Comment by vchudnov-g** [comment]
@lukesneeringer @hzyi-google Any updates on this? We're out of SLO.

**Comment by software-dov** [comment]
Leaning towards won't fix due to microgenerator transition timeline.
