### ISSUE TITLE
Support test subsetting

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/gapic-generator#1802]
Motivating case: in https://github.com/googleapis/toolkit/pull/1799 , smoke tests for Java had to be fixed because they were broken in #1757 . There are no baseline tests for anything but a simple-call smoke test, because only one smoke test can be defined per API, and adding a new API to test something brings in a crap-ton of baggage.

Thus, I propose that we support "test subsetting": this would allow us to define a new API to generate code for, but only test a subset of the output, for example the smoke test file in the current example. Then, the overhead of testing features that can only be defined once per API would be much lower.

**Comment by hzyi-google** [comment]
Smoke tests generation support is dropped.
