### ISSUE TITLE
java: Generate lite protos and lite-enabled grpc

### ISSUE THREAD

**Issue by ejona86** [googleapis/gapic-generator#1805]
com.google.api.grpc has artifacts for full protobuf and grpc, but not for protobuf lite. This means there is not a canonical library to use on Android, which means libraries can't use any of the services (otherwise it'd risk duplicated classes in the class path).

Note that this will require at least a little care because lite protobuf generated code will conflict with full protobuf generated code. So it may be a good idea to use the same artifactId for lite and full protobuf. Unclear what the best approach is.

**Comment by garrettjonesgoogle** [comment]
Should we do an approach like guava and add a qualifier to the version? We'd probably want '-lite' to take precedence over the non-lite version, so it would need to be alphabetically following "lite". Or we could do "-a-lite" and "-b-full".

**Comment by ejona86** [comment]
CC @ericgribkoff

**Comment by miraleung** [comment]
Noted and will put on our backlog for v2 of the Java microgenerator. Closing as obsolete.
