### ISSUE TITLE
Method sample initialization uber-issue

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1809]
### What

Toolkit current generates sample code for each client library method, but the values of the API request are generally uninitialized. This issue tracks process in configuring the values of the API request so that the method samples can be used to make successful requests.

### Why

Uninitialized method samples may denote a valid API call if a required field is excluded.

### How

Configuration needs to be added to the GAPIC YAML configuration files in [googleapis](https://github.com/googleapis/googleapis). This may involve both technical changes to the configuration format, and figuring out how to federate the task of providing the configuration to the right teams.

**Comment by hzyi-google** [comment]
Moved to backlog. https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
