### ISSUE TITLE
Uninitialized required fields should have a comment 

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1810]
### Context
https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1866#issuecomment-358061944

### What

If a field is required, it should be populated. Currently, an empty object may be created if the sample initialization values are not configured. In this case, we should generate an explanatory comment to populate the object.

For example, currently, one unconfigured Ruby NL method sample is

```
require "google/cloud/language/v1"

language_service_client = Google::Cloud::Language::V1.new
document = {}
response = language_service_client.analyze_syntax(document)
```

This might incorrectly imply that it is valid to send an empty document. Instead, display

```
require "google/cloud/language/v1"

language_service_client = Google::Cloud::Language::V1.new
// TODO: initialize document
document = {}
response = language_service_client.analyze_syntax(document)
```

**Comment by geigerj** [comment]
Temporarily assigning to myself to look into for Ruby, but ultimately, this could be done cross-language.

cc: @vchudnov-g

**Comment by vchudnov-g** [comment]
I agree we should do this cross-language. This has some implications for samplegen.

**Comment by geigerj** [comment]
Done for Ruby in #1813. I'll look into other languages as time permits (or open this up to language leads if not).

**Comment by jbolinger** [comment]
Python added in #1840 - not sure if I'll have time to do the others but it was a good introduction.

**Comment by jbolinger** [comment]
I think this issue is no longer relevant given the current sample gen spec. Feel free to reopen if you feel otherwise.
