### ISSUE TITLE
Copyright year should vary by API

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1815]
Current guidance is that the copyright year in license headers should remain fixed after changes to a file. Currently, when toolkit updates the copyright year, all generated clients will be refreshed to the new year, when instead they should be pinned to the year in which they were created.

This could be solved using an optional gapic configuration that specifies the copyright year to use. This could be autofilled by the config generator to the current year.

**Comment by garrettjonesgoogle** [comment]
This gets tricky: what about new client files added in years after the year that the client was first created?

**Comment by lukesneeringer** [comment]
The best thing would be to use `XXXX-YYYY` (where XXXX is specified and YYYY is generation-time-based) everywhere.

I assume this would move into package generation though.

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if this is still needed, please reopen.
