### ISSUE TITLE
Common protos used for testing are out of date

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1821]
Toolkit requires the common protos in order to run baseline tests. Currently toolkit can get these protos from two different places: 1) From the [google-common-protos package](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.api.grpc%22%20AND%20a%3A%22grpc-google-common-protos%22), and 2) from the googleapis submodule.

If the submodule has been initialized, those protos are used. Otherwise, it gets the protos from the google-common-protos package.

The googleapis submodule was [recently updated](https://github.com/googleapis/toolkit/pull/1787) but it is not possible to update the google-common-protos package because recent published versions do not include the protos themselves, only the java files.

**Comment by michaelbausor** [comment]
This PR will fix Java proto packages so that they include the proto files: https://github.com/googleapis/toolkit/pull/1820

**Comment by eoogbe** [comment]
Did that PR address the issue?

**Comment by michaelbausor** [comment]
Yes, this can be closed.
