### ISSUE TITLE
bidi method samples have unbalanced parens

### ISSUE THREAD

**Issue by pongad** [googleapis/gapic-generator#1829]
Originally reported by @lama0206 in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2764/. 

[This line](https://github.com/googleapis/toolkit/blob/3bac8312816b25bca87daac46c1b9cbf33cf17ed/src/test/java/com/google/api/codegen/testdata/java/java_library.baseline#L2072) has one extra closing paren.

**Comment by garrettjonesgoogle** [comment]
This is fixed (as can be seen at https://github.com/googleapis/gapic-generator/blob/59098a9b991ce0e8a69b772e4b6b818bdc761186/src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline#L2308 )
