### ISSUE TITLE
java: allow UTF-8 encoding in generated code

### ISSUE THREAD

**Issue by pongad** [googleapis/gapic-generator#1852]
By default, Java seems to assume that source files are ASCII-encoded.

However, some proto files have unicode characters in comments. When protoc generates java source files from these proto files, these characters are copied verbatim into Java comments. Compiling these file fails.

Since proto files are UTF8 encoded, we should include line `compileJava.options.encoding = 'UTF-8'` in generated `build.gradle` files.

**Comment by hzyi-google** [comment]
Obsolete. Gapic generator does not handle packagegen any more.
