### ISSUE TITLE
Stale gRPC stubs used for cloud spanner

### ISSUE THREAD

**Issue by carl-mastrangelo** [googleapis/gapic-generator#1856]
https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2989    fails due to an old version of the generated grpc code in use.  Looking on maven, it looks like 1.2.0, which is a few months old at this point.  It would be nice if this could be bumped to 1.10.0

@garrettjonesgoogle would you mind taking a look?

**Comment by carl-mastrangelo** [comment]
@garrettjonesgoogle friendly ping.   Any chance these could be rolled out in the near future?

**Comment by garrettjonesgoogle** [comment]
We need to change this line: https://github.com/googleapis/gapic-generator/blob/master/build.gradle#L426

**Comment by garrettjonesgoogle** [comment]
Follow-up: this has been released in google-cloud-spanner.
