### ISSUE TITLE
PHP: Generate per-option docs for oneof fields

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1915]
Some oneof fields don't have proto docs for each item in the oneof, e.g. https://github.com/googleapis/googleapis/blob/master/google/privacy/dlp/v2/dlp.proto#L2074

In this case, toolkit should pull the docs from the oneof type.

**Comment by chingor13** [comment]
We currently have a workaround in the `synth.py` script to update these doc strings.

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if there is still a need for this, please reopen.
