### ISSUE TITLE
Java: Support bundling of proto/grpc classes in same package

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/gapic-generator#1917]
Currently, the output build.gradle assumes that the proto/grpc classes will be in a separate package. For many APIs, it may be simpler to just bundle it all together; we should add an option to make this possible.

**Comment by Thar-Ngel** [comment]
> Currently, the output build.gradle assumes that the proto/grpc classes will be in a separate package. For many APIs, it may be simpler to just bundle it all together; we should add an option to make this possible.

**Comment by miraleung** [comment]
Noted and will put on the internal backlog. Closing as obsolete due to the new Java microgenerator.

**Comment by Admin8818** [comment]
Hi
