### ISSUE TITLE
Java: Don't put gradle files in parent directory of output

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/gapic-generator#1918]
Java generation will dump gradle files into the parent directory of the output. This is somewhat rude, and could even be dangerous if it overwrites user files that they don't want overwritten.

**Comment by hzyi-google** [comment]
With bazel in place we should just stop generating gradle files.

**Comment by hkdevandla** [comment]
This is will closed as part of the Java Microgenerator.
