### ISSUE TITLE
Consider changing gradle artifacts to match repo name

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator#1932]
As the repo name has changed, I'm having to change my build scripts for C# to account for that. The change is only partial though - the gradle artifact is still "toolkit".

I'm partly filing this bug so that hopefully when this is changed, the issue will be closed and I'll get notified, so I'll know to change my script again...

**Comment by jskeet** [comment]
Okay, I'm confused. It's building a gapic-generator-0.0.5-all.jar for me, despite the artifact having an id of toolkit. Oh well... closing this for now...

**Comment by garrettjonesgoogle** [comment]
Yeah the artifact was already renamed in https://github.com/googleapis/gapic-generator/pull/1916 (right before the repo rename)
