### ISSUE TITLE
Python: incorrect dependencies in generated setup.py

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#1938]
When I generated dialogflow, the following was in install_requires:

```
install_requires = [
    'google-api-core >= 0.1.0, < 0.2.0dev',
    'googleapis-common-protos[grpc] >= 1.5.2, < 2.0dev',
]
```

instead of googleapis-common-protos I would expect the following

```    
'google-api-core[grpc]<2.0.0dev,>=0.1.4',
```

**Comment by garrettjonesgoogle** [comment]
@vam-google tee hee hee

**Comment by vam-google** [comment]
Perfect timing...

**Comment by jonparrott** [comment]
I'm going to mark this as a P1 - but feel free to reprioritize.

Reasoning: we are unable to depend on generated setup.py files working with the known-good set of Python libraries because of the incompatible version ranges.

**Comment by jonparrott** [comment]
Note, you might as well go ahead and do https://github.com/googleapis/gapic-generator/issues/1849 as well.
