### ISSUE TITLE
Warnings for all auto-generated files

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator#1986]
Greetings folks! 👋 
I'm starting to look through some of our new repositories, and noticing a trend.  I have no idea which files are hand written, and which ones are auto-generated.  I'd love to be able to tell at a glance :)

Is there any way we could add a big fat header to every auto-generated file that said "WARNING:  This file is AUTO-GENERATED!!!!1"?

**Comment by alexander-fenster** [comment]
+1 on this. Can someone more familiar with the code let me know if you think there is another way of doing that, other than just editing templates of all generated files?

**Comment by michaelbausor** [comment]
PHP does have something like this: https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/Bigtable/src/V2/BigtableClient.php#L19

It is just in the templates: https://github.com/googleapis/gapic-generator/blob/master/src/main/resources/com/google/api/codegen/php/partial_veneer_client.snip#L16

**Comment by timburks** [comment]
+ @garrettjonesgoogle @lukesneeringer FYI and consideration for current and future code generators (and guidelines for writing them)

**Comment by vchudnov-g** [comment]
+1 All autogenerated files should mark themselves as such. We're doing that with samples. All microgenerators should follow suit.

**Comment by pongad** [comment]
Go and Java are already doing this.

Go adds a comment to the top of the file like [this](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/kms/apiv1/doc.go#L15).

Java adds `@Generated` annotation like [that](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java#L126)

**Comment by bcoe** [comment]
:wave: I just did my first code review on https://github.com/googleapis/nodejs-scheduler/pull/59, and just wanted to bump this issue -- it would be nice to figure out a convention for, in my case JavaScript, that helps indicate what's hand written and what's generated.

**Comment by hzyi-google** [comment]
I'm closing this as Java and PHP already has such headers while other languages are no longer supported by this generator.
