### ISSUE TITLE
Python: Attempting to append to None value object

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2014]
In the generated code for IoT, there are multiple methods that have `metadata=None` as a default and later we try to append. This will fail. The following code needs to be added to set a better default. See attached commit for more context.
```
+        if metadata is None:
+            metadata = []
+        metadata = list(metadata)
```

https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5355/commits/2a97ee519ee0fd354a870d8e082e409696e6cbd5

cc: @theacodes

**Comment by andreamlin** [comment]
Resolved by https://github.com/googleapis/gapic-generator/pull/2061.
