### ISSUE TITLE
Python: attempt to read nonexistent attr

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2015]
In the generated code for IoT, there are two locations (ln 380, 755) in    `google/cloud/iot_v1/gapic/device_manager_client.py` where attempts are made to read non-existent attributes.

```
-        routing_header = google.api_core.gapic_v1.routing_header.to_grpc_metadata(
-            [('device_registry.name', device_registry.name)], )
-        metadata.append(routing_header)
+        if hasattr(device_registry, 'name'):
+            routing_header = google.api_core.gapic_v1.routing_header.to_grpc_metadata(
+                [('device_registry.name', device_registry.name)], )
+            metadata.append(routing_header)
```

https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5355/commits/2a97ee519ee0fd354a870d8e082e409696e6cbd5

cc: @theacodes

**Comment by theacodes** [comment]
Since `device_registry` can also be a dict, this code is really brittle.
