### ISSUE TITLE
Ruby: Add logging configuration instructions to README and guide docs

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator#2022]
Please add the following static text to the generator template for package `README.md` and top-level "guide" documentation. No customization is needed for package name. The location at which to insert the text is shown in  this [commit for manually adding to existing READMEs](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2094/commits/3358a1710d6a8ffe4390dcd81bfba37f33de6c08) and this [commit for manually adding to existing guides](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2094/commits/7f25c70fdf87d9da060599cd7d45c3586c7778da).

The text:

## Enabling Logging

To enable logging for this library, set the logger for the underlying [gRPC](https://github.com/grpc/grpc/tree/master/src/ruby) library. The logger that you set may be a Ruby stdlib [`Logger`](https://ruby-doc.org/stdlib-2.5.0/libdoc/logger/rdoc/Logger.html) as shown below, or a [`Google::Cloud::Logging::Logger`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-logging/latest/google/cloud/logging/logger) that will write logs to [Stackdriver Logging](https://cloud.google.com/logging/). See [grpc/logconfig.rb](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/logconfig.rb) and the gRPC [spec_helper.rb](https://github.com/grpc/grpc/blob/master/src/ruby/spec/spec_helper.rb) for additional information.

Configuring a Ruby stdlib logger:

```ruby
require "logger"

module MyLogger
  LOGGER = Logger.new $stderr, level: Logger::WARN
  def logger
    LOGGER
  end
end

# Define a gRPC module-level logger method before grpc/logconfig.rb loads.
module GRPC
  extend MyLogger
end
```

**Comment by jbolinger** [comment]
@quartzmo minor thing, but did you mean for the header to be `##` instead of `###`?

Sort of looks strange to me as a second level header because of what comes after it.

**Comment by jbolinger** [comment]
Also the "Supported Ruby Versions" is not generated - worth adding that to the generated README now as well?

**Comment by quartzmo** [comment]
> did you mean for the header to be ## instead of ###? Sort of looks strange to me as a second level header because of what comes after it.

Good catch! Looking at the [whole, rendered file](https://github.com/quartzmo/google-cloud-ruby/blob/3358a1710d6a8ffe4390dcd81bfba37f33de6c08/google-cloud-bigquery-data_transfer/README.md), I would say that `## Enabling Logging` is correctly at the same level as `## Quick Start`, but that `### Next Steps` should be changed to `## Next Steps`. It doesn't make sense to me to include the extensive reading suggested in "Next Steps" under "Quick Start". What do you think?

In either case, I will need to make an update to fix this in #2094. Glad you pointed it out before I merged that PR>

**Comment by quartzmo** [comment]
I vote for the inclusion of "Supported Ruby Versions". (Although I have no idea of why it wasn't included, maybe there was a good reason?)

**Comment by jbolinger** [comment]
Yup, sounds good. I'll add the supported version as well and I think it also makes sense to promote that to a second level along with next steps header so it's not under the logger setup section.

**Comment by jbolinger** [comment]
Oh, so it looks like changing to `## Next Steps` is going to be a problem. That change would impact every language. Still possible, but it will require more discussion if we want to push for it.

Do you think it would be okay to move the logging and ruby version sections below `### Next Steps` as second level `##` headers instead? That layout seems natural to me.

**Comment by quartzmo** [comment]
@jbolinger Yes, sounds good. I'll update GoogleCloudPlatform/google-cloud-ruby#2094 to move the logging and ruby version sections below `### Next Steps` as second level `##` headers instead.
