### ISSUE TITLE
samplegen: fixes to and for check-calling-form-in-baseline: yaml file updates, tag string format

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#2044]
Some additional changes are needed on top of #2012 

1. The library_gapic.yaml should be migrated to proper `callingFormCheck` strings. Sorry I overlooked this in #2012 
1. We should add `callingFormCheck` lines for the additional languages
1. The multi-line yaml literal suggested for the multi-language `callingFormCheck` lines is not working for me. Let's either update the doc or revisit the format
1. As a result of the above, we should deal with any resulting error messages from the check
1. The `callingFormCheck` string should not require specifying the `value_id`, since it is already embedded in a value set. Let's avoid the repetition
1. If it's easy, error messages should ideally also output the method name where the expected value set/calling form combination was not found. This would make it easier to fix errors, but is not a strict requirement because we're only using this for testing the generator itself, so we can name value sets distinctly to make finding errors easy.

**Comment by vchudnov-g** [comment]
See a [PR in progress](https://github.com/vchudnov-g/toolkit/commit/5ba84da483ccaac6e383209ff21f105d7c177bc9) in my fork that begins to address items 1 and 2. I am blocked on 3, so will let @pongad handled that, as well as doing 5.

**Comment by pongad** [comment]
Resolved by #2049
