### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator#2054]
It would be rad if we could generate TypeScript libraries as well as JavaScript.  Putting this here for tracking purposes :)

**Comment by joofholland** [comment]
Hi! Is there any progress on this? I would like to use Google generated typings

**Comment by alexander-fenster** [comment]
Hi @joofholland! We plan to ship our first TypeScript libraries later this or early next quarter. This issue will be updated when the first auto-generated TypeScript libraries are published.

**Comment by andreamlin** [comment]
@alexander-fenster Can you add a priority?

**Comment by alexander-fenster** [comment]
So, it's finally (!) here, in a separate repo https://github.com/googleapis/gapic-generator-typescript - closing this issue.
