### ISSUE TITLE
Generator creates invalid Ruby Tests

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/gapic-generator#2080]
MiniTest no method named assert_not_nil. Looks like it should be refute_nil as http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html#method-i-refute_nil

**Comment by jbolinger** [comment]
Thanks for reporting this @TheRoyalTnetennba. I'm surprised it hasn't come up before.
