### ISSUE TITLE
When generating Ruby texttospeech v1, credentials.rb gets generated in the wrong place

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2081]
Ran the Ruby generator on texttospeech v1.

It generated the file `lib/google/cloud/text_to_speech/v1/credentials.rb`.
This file is supposed to be located at `lib/google/cloud/text_to_speech/credentials.rb`

**Comment by jbolinger** [comment]
This one should be fixed by #2079 and the new behavior is to version this file (i.e it should go in the v1 directory).

Also, @landrito this is the kind of thing your recent testing proposal would help catch... so let's push for that soon.

**Comment by dazuma** [comment]
Ah, that makes sense. Okay, closing.
