### ISSUE TITLE
[Python] some py files from generator contain utf-8 chars but are missing the source encoding header

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2097]
*.py files that contain utf-8 characters should specify the encoding with the following header
```
# -*- coding: utf-8 -*-
```

**Comment by crwilcox** [comment]
Example: https://github.com/dialogflow/dialogflow-python-client-v2-private/pull/1/commits/c370c731aa003c61eea619d4d631cbf8de108ce0

**Comment by crwilcox** [comment]
I should also note I believe this can be safely added to all generated files.

**Comment by timburks** [comment]
Thanks @crwilcox -- @lukesneeringer could you take care of this or find an owner?

**Comment by lukesneeringer** [comment]
We can add these to our files easily, but it will be trickier to add it to the pb2 files (which is I think where the problems lie). It can be done though, and we already edit those files to alter imports.

**Comment by crwilcox** [comment]
Those are the files with the issue typically, yes.

**Comment by tseaver** [comment]
For those playing along at home:  note that current `synth.py` files in `google-cloud-python` still need to have the following replacement, or else the unit tests break on Python 2.7:

```python
s.replace(
    '**/proto/*_pb2.py',
    r"(^.*$\n)*",
    r"# -*- coding: utf-8 -*-\n\g<0>")
```
