### ISSUE TITLE
Update samples to use version constructor

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator#2099]
Automate changes shown in: https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2146

**Comment by jbolinger** [comment]
@frankyn the bucket name is a configuration option (i.e. you need to update the yaml file). For speech that value is here: https://github.com/googleapis/googleapis/blob/7ccfa2cd4a2737dc828061809d60ee03b23e2b5d/google/cloud/speech/v1p1beta1/speech_gapic.yaml#L35

The version thing I will update shortly.

**Comment by frankyn** [comment]
@jbolinger the line you mentioned seems to be apart of smoke tests. I think that should stay the same. The lines below for sample snippets have `gs://bucket_name/file_name.flac`. Unless there's a bug and it's using the smoke test value instead.

**Comment by jbolinger** [comment]
@frankyn yeah, you're correct. It is indeed a bug and it's using the wrong value. I'll open a new issue for it.
