### ISSUE TITLE
Ruby samples use smoke test values

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator#2106]
Ruby samples use values from the smoke test `init_fields` rather than the `sample_code_init_fields`.

To reproduce generate the speech v1 API and note that the sample in `lib/google/cloud/speech.rb` is using the smoke test value.

Originally reported in #2099

**Comment by frankyn** [comment]
Once this is completed, then we can refresh. 

Thanks Joe!

**Comment by vchudnov-g** [comment]
@jbolinger Any updates on this? We're out of SLO here.

**Comment by eoogbe** [comment]
@jbolinger Any updates?

**Comment by jbolinger** [comment]
All P2+ are being addressed with https://github.com/googleapis/gapic-generator-ruby and won't be fixed here.

**Comment by noahdietz** [comment]
@jbolinger has this issue been moved to the gapic-generator-ruby repo? If it won't be fixed here, the issue should be tracked where it'll be fixed. This issue is out of SLO right now. I'm happy to open the issue myself if preferred.

**Comment by jbolinger** [comment]
We can track it here: https://github.com/googleapis/gapic-generator-ruby/issues/63 and close this here since there is no plan to fix this in the legacy generator (synth workarounds are available).
