### ISSUE TITLE
Ruby: Service tests create global classes that need to be namespaced

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2117]
Currently, the generated service client tests for Ruby generate a few global classes. For example, I just generated video_intelligence, and the generated service client test file `test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb` includes the following toplevel classes:
* `CustomTestError`
* `MockGrpcClientStub`
* `MockVideoIntelligenceServiceCredentials`

The problem is when we generate more than one API version in the same library (as we do in Ruby), the tests for the multiple versions cannot coexist. The toplevel classes are defined in the generated tests for _each_ API version, and thus conflict. In some cases, this won't make a difference because the generated classes are identical, and Ruby allows you to reopen classes. However, if there are any differences in these classes, the conflicts will cause problems. Currently, the credentials classes are causing test failures because each version has a separate credentials base class, so the toplevel class is trying to subclass multiple base classes, resulting in a compile error.

A reasonable workaround might be to mangle the generated class names to include the API version. e.g. `MockVideoIntelligenceServiceCredentials_v1beta1`.

**Comment by dazuma** [comment]
I would just go with giving all the test helper classes versioned names. It keeps things straightforward.

**Comment by timburks** [comment]
Just for background:
- Should these classes be in the libraries at all? (i.e. are they useful to library users, just artifacts of our testing, or something else)
- Should some of these classes be in GAX instead?

**Comment by dazuma** [comment]
They are specific to the tests and belong there. (e.g. mocks, etc.)

**Comment by dazuma** [comment]
ping

**Comment by jbolinger** [comment]
@dazuma sorry for the delay on this one (@landrito and I will try to clear out the P1 backlog shortly).
