### ISSUE TITLE
Ruby: Expand credentials-related env variables to match handwritten clients

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2118]
Currently, the generated credentials.rb files for Ruby look for credentials in six environment variables, three for credential file paths, and three for json string data. The handwritten credential files honor ten environment variables (5 for paths and 5 for json). We should update the generated credential classes to match.

For example, generated credential classes for the trace service include the following:

```ruby
  PATH_ENV_VARS = %w(TRACE_KEYFILE GOOGLE_CLOUD_KEYFILE GCLOUD_KEYFILE)
  JSON_ENV_VARS = %w(TRACE_KEYFILE_JSON GOOGLE_CLOUD_KEYFILE_JSON GCLOUD_KEYFILE_JSON)
```

These should be updated to read:

```ruby
  PATH_ENV_VARS = %w[TRACE_CREDENTIALS
                     TRACE_KEYFILE
                     GOOGLE_CLOUD_CREDENTIALS
                     GOOGLE_CLOUD_KEYFILE
                     GCLOUD_KEYFILE].freeze
  JSON_ENV_VARS = %w[TRACE_CREDENTIALS_JSON
                     TRACE_KEYFILE_JSON
                     GOOGLE_CLOUD_CREDENTIALS_JSON
                     GOOGLE_CLOUD_KEYFILE_JSON
                     GCLOUD_KEYFILE_JSON].freeze
```

(It would also be a good idea to freeze the constants, as shown above.)

**Comment by jbolinger** [comment]
I think Mike beat you to this one via GoogleCloudPlatform/google-cloud-ruby#1830, which was updated in #2110. Let me know if that looks good to you (there is no `.freeze` so we could add that if you think it'll make any difference)

**Comment by dazuma** [comment]
Okay, that looks good. Freezing is a good idea, but not nearly as important. I'll do another pass at the constant generation, and open a separate issue around freezing if it looks worthwhile. Thanks!
