### ISSUE TITLE
Node: generated unused mockSimpleGrpcMethod() in tests

### ISSUE THREAD

**Issue by jkwlui** [googleapis/gapic-generator#2120]
Generating the latest video-intelligence library result in tests that failed `npm run lint`. It complains mockSimpleGrpcMethod() is defined but not used.

https://github.com/googleapis/nodejs-video-intelligence/pull/51

**Comment by michaelbausor** [comment]
Ping @alexander-fenster

**Comment by alexander-fenster** [comment]
Here, we need to include `mockSimpleGrpcMethod()` in the output only if the API has simple gRPC methods (and video-intelligence is one rare example of an API with all methods being long running). I'm not sure if there is an easy way to write this condition in the snip file. Looking.

**Comment by kinwa91** [comment]
We are still experiencing this issue in video-intelligence. Not blocking, but good to get it fixed :)

**Comment by landrito** [comment]
@alexander-fenster any updates on this?

**Comment by vchudnov-g** [comment]
@alexander-fenster Any updates? This issue is out of SLO. Is it prioritized correctly?

**Comment by alexander-fenster** [comment]
I guess it must not be a P0. Yoshi team has a [workaround](https://github.com/googleapis/nodejs-video-intelligence/blob/6139be496dc77715f0238794a82552bf3a6af972/synth.py#L29) for that in their synth script for this library, and video intelligence is the only library affected (it does not have non-long-running methods). 

I will decrease the priority of this issue. Having that said, it should be a quick fix anyway.

**Comment by kinwa91** [comment]
I'm okay with that. Thanks Alex!

**Comment by eoogbe** [comment]
@alexander-fenster Any updates?

**Comment by noahdietz** [comment]
@alexander-fenster any update here? Is there a quick fix that can be detailed here for another person to pick up? Thanks

**Comment by alexander-fenster** [comment]
I'd like not to fix it now in gapic-generator since it's something that can be taken care of by Yoshi in synth tool and it never affects end users' experience. We can try taking care of that in scope of TypeScript micro generator (let's leave this open here for now and I'll move it to that repo when it's alive).

**Comment by vchudnov-g** [comment]
Deprioritizing as per last comment.

**Comment by vchudnov-g** [comment]
@alexander-fenster Could you update this issue? Was this fixed in gapic-generator (in which case, feel free to close this) or addressed some other way elsewhere (in which case feel free to leave a note why this will not be fixed here). Thanks!

**Comment by alexander-fenster** [comment]
@vchudnov-g It's fixed in https://github.com/googleapis/gapic-generator-typescript/pull/155 (for the TypeScript generator). I'll close this issue here.
