### ISSUE TITLE
[Node] Pub Sub has manually written method in generated code

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2127]
While generaing in the nodejs-pubsub package I found this code getting removed in `src/v1/subscriber_client.js` since it was added manually. Is this code the generator should have inserted?

```
    // note: editing generated code
    this.waitForReady = function(deadline, callback) {
      return subscriberStub.then(
        stub => stub.waitForReady(deadline, callback),
        callback
      );
    };
```

**Comment by callmehiphop** [comment]
We actually have a couple of use cases where accessing members of the grpc client is needed. Maybe instead of stubbing more of those methods we could just add getters for the grpc clients.

**Comment by vchudnov-g** [comment]
@alexander-fenster We're out of SLO for this issue. Could provide an update and/or lower the priority?

**Comment by alexander-fenster** [comment]
The manual change is still there, but the micro-generator is supposed to fix that. Lowering the priority for now since it does not affect anyone (handled by `synthtool`).
