### ISSUE TITLE
[Node] Generated tests for speech do not pass

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2129]
https://github.com/googleapis/nodejs-speech/pull/100/commits/e30d80d2fa7b4af430cc3fefcb5e48995c10bbd2

The inner api call for streamingRecognize is called multiple times with different inputs. This causes the code as generated to fail. There are some small tweaks that also might help.

1) when config is undefined `{streamingConfig:undefined}` is sent instead of `{}`. 
2) when audioContent is `{}`, `{audioContent:{}}` is sent. 

If both of those things were adjusted I think the tests may work as is. We can also have a stub that understand multiple call/return values as I have edited it to do.

**Comment by JustinBeckwith** [comment]
@lukesneeringer @alexander-fenster just getting this on y'alls radar.  This is blocking automated updates to speech.

**Comment by alexander-fenster** [comment]
Wait wait, isn't it due to manual layer (`helpers.js`) that breaks the autogen'd unit tests? If so, there's not much the generator can do.

**Comment by andreamlin** [comment]
@crwilcox friendly ping

**Comment by crwilcox** [comment]
@alexander-fenster I dug into this and it can be resolved by adjusting the helper. The issue was is the helper would send two pieces of data separately instead of together (as the generator does). I will send a PR shortly that allows us to start generating the tests again and use them as is.
