### ISSUE TITLE
Java gapics: Use ResourceName types for singular params in flattened methods

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2137]
https://github.com/googleapis/gapic-generator/pull/2131 introduces a change to prevent all flattened methods that have at least one repeated param from using ResourceName types (uses String instead).

Improve client usability by allowing singular params to be ResourceName types, even when the repeated params are using List<String> types.

**Comment by hzyi-google** [comment]
Fixed in #3081
