### ISSUE TITLE
[PHP] Namespace inconsistency during deprecation

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/gapic-generator#2141]
We're trying to update the KMS client lib for PHP. The newly generated code is using a nicer namespace like `Google\Cloud\Kms\V1\CryptoKey\CryptoKeyPurpose` instead of `Google\Cloud\Kms\V1\CryptoKey_CryptoKeyPurpose`. Also the generator keeps the old namespaced class with a deprecation warning.

This is a great feature, but we found there are some usages of old classes in various places.

1. [`Google\Cloud\Kms\V1\Gapic\KeyManagementServiceGapicClient`](https://github.com/tmatsuo/google-cloud-php/blob/95d2dd7215af1fd20892b573fcdea8244939c843/Kms/src/V1/Gapic/KeyManagementServiceGapicClient.php#L890)
2. [`\Google\Cloud\Kms\V1\CryptoKey.php`](https://github.com/tmatsuo/google-cloud-php/blob/95d2dd7215af1fd20892b573fcdea8244939c843/Kms/src/V1/CryptoKey.php#L198)
3. Some occurrences in the unit tests [`\Google\Cloud\Kms\Tests\Unit\V1\KeyManagementServiceClientTest`](https://github.com/tmatsuo/google-cloud-php/blob/95d2dd7215af1fd20892b573fcdea8244939c843/Kms/tests/Unit/V1/KeyManagementServiceClientTest.php#L34)

For 1, this is the sample code in the doc comment, so it is basically telling users to use the deprecated class which will be removed with the next release. I think the sample code should use the newer class name.

For 2 and 3, I still think it is cleaner to use the newer namespace.

**Comment by vchudnov-g** [comment]
@michaelbausor Updates?

**Comment by andreamlin** [comment]
@michaelbausor Updates?

**Comment by jbolinger** [comment]
@michaelbausor any updates?

**Comment by landrito** [comment]
@michaelbausor any updates?

**Comment by jbolinger** [comment]
@michaelbausor any updates?

**Comment by michaelbausor** [comment]
No update at this time.

**Comment by vchudnov-g** [comment]
@michaelbausor Could you provide an update and/or lower the priority if appropriate?

**Comment by michaelbausor** [comment]
This will be fixed in https://github.com/googleapis/gapic-generator/pull/2757

**Comment by vchudnov-g** [comment]
@hzyi-google Did #2757 fix this? If so could you close this issue?

**Comment by hzyi-google** [comment]
Fixed by #2757.
