### ISSUE TITLE
[Ruby] Examples are showing incorrect construction of client objects

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2143]
It looks like the Ruby examples were recently changed from, e.g.:

```ruby
require "google/cloud/tasks/v2beta2"
cloud_tasks_client = Google::Cloud::Tasks::V2beta2.new
#...
```

To

```ruby
require "google/cloud/tasks"
cloud_tasks_client = Google::Cloud::Tasks::V2beta2.new(version: :V2beta2)
#...
```

This is incorrect. It needs to be:

```ruby
require "google/cloud/tasks"
cloud_tasks_client = Google::Cloud::Tasks.new(version: :v2beta2)
#...
```

Note the TWO corrections:
* Need to call `new` on the service module, not the version module, if you want to pass a version argument.
* The version argument is misspelled; it should not be capitalized.

See https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2186 for an example.

**Comment by jbolinger** [comment]
Do you think this could have anything to do with the synth tools you're using? I don't know much about how they work, but I just regenerated this locally and got this in the examples sections:

```
require "google/cloud/tasks/v2beta2"
cloud_tasks_client = Google::Cloud::Tasks::V2beta2.new
```

I could change it to use the symbol, and change the case of the symbol, but that doesn't explain what's in that PR where the two ways to create a client are being mixed incorrectly.

**Comment by dazuma** [comment]
The synth tool for that directory isn't doing any postprocessing. I suppose it's possible synth is using a different version of gapic-generator than you're running locally?

**Comment by jbolinger** [comment]
Do you know what version you're using? I've tried with a few versions but haven't been able to reproduce it.

**Comment by dazuma** [comment]
As I understand it, it's using the current latest artman docker image `googleapis/artman:latest`. See https://github.com/GoogleCloudPlatform/synthtool/blob/master/synthtool/gcp/gapic_generator.py

**Comment by dazuma** [comment]
I just tried running synthtool locally (which runs artman from that image) and I'm getting the same weirdly "mixed" results.

**Comment by jbolinger** [comment]
Thanks @dazuma I was able to reproduce it. It was something unrelated on my side but seeing that synthtool script was pretty useful anyway.

Turns out this is because of a bad regex and it is happening because it's v2beta2 vs. something like v2, which isn't covered by our tests. I should be able to fix that part fairly quickly.

**Comment by dazuma** [comment]
Tested artman 0.14.1. It looks like the second bullet point is fixed:

> The version argument is misspelled; it should not be capitalized.

but not the first:

> Need to call `new` on the service module, not the version module, if you want to pass a version argument.

**Comment by dazuma** [comment]
Just to be clear, when I generate tasks v2beta2, in the file `google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb` the following was generated around line 450ish:

```ruby
          # @example
          #   require "google/cloud/tasks"
          #
          #   cloud_tasks_client = Google::Cloud::Tasks::V2beta2.new(version: :v2beta2)
          #   formatted_parent = Google::Cloud::Tasks::V2beta2::CloudTasksClient.location_path("[PROJECT]", "[LOCATION]")
```

This should be

```ruby
          # @example
          #   require "google/cloud/tasks"
          #
          #   cloud_tasks_client = Google::Cloud::Tasks.new(version: :v2beta2)
          #   formatted_parent = Google::Cloud::Tasks::V2beta2::CloudTasksClient.location_path("[PROJECT]", "[LOCATION]")
```

**Comment by jbolinger** [comment]
Ops, I didn't mean to auto close this. @dazuma we should have a new release later today.

**Comment by dazuma** [comment]
Great, looking forward to testing it!

**Comment by jbolinger** [comment]
@dazuma is this still an issue? 

After my last change I checked locally for the cloud tasks library and it seemed to be generating the names correctly.

**Comment by dazuma** [comment]
It looks good now. I've tested a number of cases today. Closing.
