### ISSUE TITLE
CircleCI: move to v2.0

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator#2147]
CircleCI v1.0 will be deprecated on August 31st, 2018. We need to move the project to CircleCI v2.0 by creating `.circleci/config.yml` and making it run the workflow.

![image](https://user-images.githubusercontent.com/4015807/42663876-91063aae-85ec-11e8-8c44-df254eccec5b.png)

**Comment by alexander-fenster** [comment]
https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by michaelbausor** [comment]
@landrito can this be closed out now?

**Comment by michaelbausor** [comment]
I believe the answer is yes - closing out now.
