### ISSUE TITLE
[NodeJS] assert.equal() is deprecated since node v10

### ISSUE THREAD

**Issue by kinwa91** [googleapis/gapic-generator#2154]
eslint-plugin-node v7 doesn't like us using assert.equal() anymore. Replace `assert.equal` with `assert.strictEqual`

reference: https://github.com/googleapis/nodejs-automl/pull/11

**Comment by JustinBeckwith** [comment]
Yeah I just ran into this too.  @alexander-fenster we could use a hand here :)
