### ISSUE TITLE
Sphinx finds unexpected indentation in dialogflow docstrings

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2157]
Currently there are a few docstrings in the generated dialogflow client. (in agents_client.py)

![image](https://user-images.githubusercontent.com/638797/42959451-b5051352-8b3d-11e8-8121-8b4f63ff33f7.png)

These docstrings have unexpected indentation
` dialogflow-python-client-v2/dialogflow_v2/__init__.py:docstring of dialogflow_v2.AgentsClient.import_agent:41:Block quote ends without a blank line; unexpected unindent.`

The screenshot shows the generation undoing a manual change I made to get docs builds passing.

**Comment by vchudnov-g** [comment]
@lukesneeringer ping

**Comment by vchudnov-g** [comment]
@lukesneeringer ping

**Comment by noahdietz** [comment]
@lukesneeringer friendly ping

**Comment by lukesneeringer** [comment]
@michaelbausor Is this a result of your previous fixes? (It seems like the timing is roughly right for that.)

**Comment by michaelbausor** [comment]
I don't think the problem is related, as it is from July, much earlier than my fixes. But the recent pandoc fix might have *fixed* this problem - I'm not sure.

**Comment by andreamlin** [comment]
@crwilcox Is this still an issue?

**Comment by jbolinger** [comment]
@lukesneeringer or @michaelbausor any updates on this?

**Comment by landrito** [comment]
@lukesneeringer or @michaelbausor any updates?

**Comment by vchudnov-g** [comment]
@lukesneeringer Could you provide an update, as per SLO?

**Comment by noahdietz** [comment]
@lukesneeringer @michaelbausor any updates on this? Thanks

**Comment by andreamlin** [comment]
@crwilcox has this been fixed?

**Comment by jbolinger** [comment]
@lukesneeringer or @crwilcox any updates? Is this fixed?

**Comment by michaelbausor** [comment]
Closing this out. If it's still a problem, we can reopen.
