### ISSUE TITLE
Create new instance of client info rather than stomping on shared instance.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2161]
While reviewing a new client @tseaver noticed a bit that may need revising. 

Quoting from https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5665/files/12676aaf08dc795f2216f9441896cfae54edd382#diff-198e257d2c267a0bc3e3d2f3e77ec561

 https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/dlp/google/cloud/dlp_v2/gapic/dlp_service_client.py#L173
```python
        if client_info is None:
            client_info = (
                google.api_core.gapic_v1.client_info.DEFAULT_CLIENT_INFO)
        client_info.gapic_version = _GAPIC_LIBRARY_VERSION
```

This bit is problematic -- the `DEFAULT_CLIENT_INFO` instance is going to be scribbled on by every library generated this way, which means that each time an app instantiates a generated client, they *all* use the last-instantiated one's `gapic_version`.

Rather than reuse the instance, we should be constructing a *new* one here, e.g.:

```python
        if client_info is None:  # create a new instance
            client_info = (
                google.api_core.gapic_v1.client_info.ClientInfo(
                    gapic_version=_GAPIC_LIBRARY_VERSION)
        else:  # update caller-supplied instance
            client_info.gapic_version = _GAPIC_LIBRARY_VERSION
```

**Comment by jbolinger** [comment]
@crwilcox @lukesneeringer this has been quiet for awhile - is it still relevant?

**Comment by tseaver** [comment]
@jbolinger The generator is still emitting code which has this flaw (@crwilcox re-genned several libraries over the weekend, ant their clients all have it).

**Comment by tseaver** [comment]
- https://github.com/googleapis/gapic-generator/blob/085018f461968ab38f1cb85565a9198c15684458/src/main/resources/com/google/api/codegen/py/main.snip#L140
- https://github.com/googleapis/gapic-generator/blob/3bcf41a4de3f55bea470f6e72386406685ba77e7/src/test/java/com/google/api/codegen/testdata/py/python_multiple_services.baseline#L964
- https://github.com/googleapis/gapic-generator/blob/3bcf41a4de3f55bea470f6e72386406685ba77e7/src/test/java/com/google/api/codegen/testdata/py/python_no_path_templates.baseline#L907
- https://github.com/googleapis/gapic-generator/blob/a05cf23a4844f6ec16833d545fd69009fb939d25/src/test/java/com/google/api/codegen/testdata/py/python_library.baseline#L1213
