### ISSUE TITLE
[Ruby] AVAILABLE_VERSIONS is not finding any results

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2174]
Apparently as a result of https://github.com/googleapis/gapic-generator/pull/2163 now the `AVAILABLE_VERSIONS` determination for a single-service library is returning no results.

Specifically, it's failing in the case where postVersionDirPath is empty. The original intent for that case appears to be that the directory name itself gets `.rb` appended to it (e.g. `/path/to/v1` -> `/path/to/v1.rb`). But the change yields `/path/to/v1/.rb` which is incorrect.

The resulting change (e.g. https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2209/files) then fails tests.

I think we need to have different logic for empty vs non-empty postVersionDirPath.

**Comment by dazuma** [comment]
@jbolinger @landrito ping

**Comment by landrito** [comment]
Ah woops. I'll have a fix in by early next week.
