### ISSUE TITLE
[Ruby] Acceptance tests are generated without reference to API version

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2185]
On generating google-cloud-speech for Ruby with version "v1p1beta1", the generated file "google-cloud-speech/acceptance/google/cloud/speech/v1p1beta1/speech_smoke_test.rb" includes the following code near the top:

```ruby
describe "SpeechSmokeTest" do
  it "runs one smoke test with recognize" do

    speech_client = Google::Cloud::Speech.new
```

This should be:

```ruby
describe "SpeechSmokeTest V1p1beta1" do
  it "runs one smoke test with recognize" do

    speech_client = Google::Cloud::Speech.new version: :v1p1beta1
```

(Note the TWO changes needed: the name of the spec, and the argument to the client constructor.)

Other generated files seem to have the correct version.

**Comment by jbolinger** [comment]
@dazuma for this one I'm assuming that you don't care about the capitalization of the version in the `describe` string or the difference between `foo.new version: :v1` vs `foo.new(version: :v1)` but do let me know if that's not the case.

**Comment by dazuma** [comment]
No, I don't care about the captialization or the parens. :)
