### ISSUE TITLE
Python docs builds should not have 'raw-latex'

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2191]
The docs builds for python do not have raw-latex as a directive. This causes our builds to fail. One example is in `dataproc`

```
labels:
          Optional. The labels to associate with this job.  Label keys
          must be between 1 and 63 characters long, and must conform to
          the following regular expression: [:raw-latex:`\p{Ll}`:raw-
          latex:`\p{Lo}`][:raw-latex:`\p{Ll}`:raw-latex:`\p{Lo}`:raw-
          latex:`\p{N}`\_-]{0,62}  Label values must be between 1 and 63
          characters long, and must conform to the following regular
          expression: [:raw-latex:`\p{Ll}`:raw-latex:`\p{Lo}`:raw-
          latex:`\p{N}`\_-]{0,63}  No more than 32 labels can be
          associated with a given job.
```

Is there a plugin for sphinx you expect we are using or is this a bug?

**Comment by vchudnov-g** [comment]
@lukesneeringer Update?

**Comment by noahdietz** [comment]
@lukesneeringer friendly ping for an update

**Comment by andreamlin** [comment]
@lukesneeringer Would you mind taking action on this?

**Comment by lukesneeringer** [comment]
Update: I just verified (using the microgenerator) that pandoc does not add `:raw-latex:` directives like this to the Markdown found in the proto. (I used the original example from dataproc to test.)

Looking into why it is happening here.

**Comment by lukesneeringer** [comment]
Figured out the issue. Filed googleapis/artman#535 to fix it.

**Comment by jbolinger** [comment]
@lukesneeringer Any news on this one?

**Comment by landrito** [comment]
@lukesneeringer any updates?

**Comment by vchudnov-g** [comment]
@lukesneeringer Could you provide an update, as per SLO?

**Comment by noahdietz** [comment]
@lukesneeringer I have pinged on the PR mentioned here, but any update would be appreciated. Thanks

**Comment by lukesneeringer** [comment]
Bah. Sorry for never seeing this (and thanks Andrea for emailing).

@crwilcox: The issue in the PR that fixes this underlying issue is that it creates a new issue in Spanner that we have to deal with. I think that transactions comment is _already_ an issue for Yoshi, am I correct? If so, it seems like an improvement to adjust the tests and merge that PR.

**Comment by lukesneeringer** [comment]
Pinging this thread to say that I am going to make an executive decision to adjust the tests and merge this PR in a few days unless @crwilcox objects.

**Comment by jbolinger** [comment]
@lukesneeringer is this resolved based on your last note?

**Comment by lukesneeringer** [comment]
It is now fixed.
