### ISSUE TITLE
[Ruby] Logging and monitoring clients will not compile, possibly because of outdated common types

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2204]
Currently the generated logging and monitoring clients for Ruby will not compile because they reference the common proto type `google.api.MonitoredResourceMetadata` which is not defined. I believe this type is supposed to live in the [googleapis-common-protos-types gem](https://rubygems.org/gems/googleapis-common-protos-types), which hasn't been updated since last year and probably just needs to be regenerated.

**Comment by andreamlin** [comment]
Yeah I had the same problem for Java; the logging clients needed a refreshed google-common-protos dependency to pick up the new prototype.

**Comment by andreamlin** [comment]
Generated the ruby package. Just need to release now.

**Comment by andreamlin** [comment]
Assigned to @landrito  to release.

**Comment by landrito** [comment]
Version 1.0.2 of googleapis-common-protos-types is released: 
https://rubygems.org/gems/googleapis-common-protos-types/versions/1.0.2

Closing. Reopen if you find a bug with the release.

**Comment by dazuma** [comment]
Thank you! Testing the new release—it appears to be working correctly so far.
