### ISSUE TITLE
Regenerate python common types

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2209]
Same as https://github.com/googleapis/gapic-generator/issues/2204 but for python clients. This breaks generation of Logging and Monitoring clients.

**Comment by lukesneeringer** [comment]
What exactly is missing?

**Comment by tseaver** [comment]
`1.6.0b4` has those types.  @lukesneeringer [mentioned](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/6081#issuecomment-424129052) making a `1.5.4` release to address this issue until the `1.6.0` final release is ready.

**Comment by tseaver** [comment]
@lukesneeringer Ping?

**Comment by tseaver** [comment]
Is there an issue blocking a release of a non-beta version of `googleapis-common-protos` which can be used with the current logging / monitoring protos?

**Comment by tseaver** [comment]
@lukesneeringer Thanks for making the [1.5.4 release](https://pypi.org/project/googleapis-common-protos/1.5.4/).  Unfortunately, it breaks pretty much all our APIs which use `google.longrunning`.  The generated code for them has lines like:

```python
  _descriptor.MethodDescriptor(
    name='DeleteDataset',
    full_name='google.cloud.automl.v1beta1.AutoMl.DeleteDataset',
    index=3,
    containing_service=None,
    input_type=_DELETEDATASETREQUEST,
    output_type=google_dot_longrunning_dot_operations__pb2._OPERATION,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\0023*1/v1beta1/{name=projects/*/locations/*/datasets/*}')),
  ),
```

but  `operations_pb2` no longer exports that module, because it is now an alias for `operations_grpc_pb2`, via:

```python
try:
  from google.longrunning.operations_grpc_pb2 import *
except ImportError:
  from google.longrunning.operations_proto_pb2 import *
```

The `*` import leaves out names prefixed with underscores. :(

**Comment by tseaver** [comment]
The 1.5.3 version of `operations_pb2.py` explicitly imports `_OPERATION`:

```python
try:
    from google.longrunning.operations_grpc_pb2 import *
    from google.longrunning.operations_grpc_pb2 import _OPERATION
except ImportError:
    from google.longrunning.operations_proto_pb2 import *
    from google.longrunning.operations_proto_pb2 import _OPERATION
```

**Comment by lukesneeringer** [comment]
Aww, rats. I explicitly reverted that file to _avoid_ changing anything there.

**Comment by lukesneeringer** [comment]
1.5.5 is released with this fixed.

**Comment by lukesneeringer** [comment]
@crwilcox tells me this is in good shape now.
