### ISSUE TITLE
Change PHP Namespace for AutoML

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gapic-generator#2229]
Can we change the PHP namespace in [`automl_gapic.yaml`](https://github.com/googleapis/googleapis/blob/master/google/cloud/automl/v1beta1/automl_gapic.yaml#L16) to `AutoML` from `Automl`?

If so, will this be enough, or do we need to add the `php_namespace` option to all of the [`*.proto`](https://github.com/googleapis/googleapis/tree/master/google/cloud/automl/v1beta1) files as well?

**Comment by vchudnov-g** [comment]
@michaelbausor Any updates?

**Comment by michaelbausor** [comment]
Closing as no longer relevant - if this is still needed, please reopen.
