### ISSUE TITLE
Regenerate common protos for PHP

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2238]
Same as https://github.com/googleapis/gapic-generator/issues/2209 and https://github.com/googleapis/gapic-generator/issues/2204, but for PHP.

This blocks new regens for the Logging and Monitoring clients, which depend on the newest common protos.

**Comment by andreamlin** [comment]
Marking as P1 in line with the other issues.

**Comment by michaelbausor** [comment]
PR: https://github.com/googleapis/gax-php/pull/210

**Comment by andreamlin** [comment]
@michaelbausor so this is complete?

**Comment by michaelbausor** [comment]
Yes, closing out
