### ISSUE TITLE
Fail to generate python artman_iamcredentials_v1.yaml

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2265]
Failed to generate python_gapic of /var/code/googleapis/google/iam/credentials/artman_iamcredentials_v1.yaml. 

See https://circleci.com/gh/googleapis/googleapis/1344 for failing build log.

**Comment by andreamlin** [comment]
[sources_generation-stdout.log](https://github.com/googleapis/gapic-generator/files/2320120/sources_generation-stdout.log)
^ artman log file

**Comment by andreamlin** [comment]
internall bug #112268544

**Comment by andreamlin** [comment]
target has been whitelisted in artman repo but artman still needs to be released for googleapis/googleapis build to pick up the changes.

**Comment by michaelbausor** [comment]
@andreamlin is this now resolved, or is it still an open issue?

**Comment by vchudnov-g** [comment]
@andreamlin update?

**Comment by andreamlin** [comment]
The issue is in https://github.com/googleapis/artman/issues/518

**Comment by andreamlin** [comment]
This has been fixed in artman's master branch.

We will cut an artman release very soon.

**Comment by andreamlin** [comment]
This should be good in the newest version of artman [v0.16.2](https://hub.docker.com/r/googleapis/artman/tags/)
