### ISSUE TITLE
Remove 'cloud' from default package names

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2299]
Curerntly, default package names in configgen add `"cloud"` to the package name. We should handle package names for non-Google-Cloud and third-party codegen.

**Comment by andreamlin** [comment]
See [LanguageSettingsMerger](https://github.com/googleapis/gapic-generator/blob/e3501faea84f61be2f59bd49a7740a486a02fa6b/src/main/java/com/google/api/codegen/configgen/mergers/LanguageSettingsMerger.java#L41). for how anything starting with `"google"` is replaced by something that starts with `"google.cloud"`

**Comment by hzyi-google** [comment]
Configgen is deprecated.
