### ISSUE TITLE
[Ruby] Don't replace backticks with plus signs in comments

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2303]
Currently the Ruby generator is replacing backticks (i.e. code markup syntax in Markdown) with plus signs (which is rdoc syntax). However, we are generating YARD format documentation using Markdown, so we actually do _not_ want this replacement to happen. This issue is causing a lot of syntax-critical pieces of documentation (like regexes and other format strings) to be misformatted and/or mangled.

@jbolinger Marking this as P1 because it's quite difficult to reverse this after the fact in a synth transform (i.e. determining whether a plus sign is a literal plus or a transformed backtick), but I assume it would be easy to remove the replacement in the generator. Would you be able to get a quick patch in?

**Comment by jbolinger** [comment]
@dazuma I'll take a look at this tomorrow. Does this problem occur anywhere else besides the method samples in the comments?

**Comment by dazuma** [comment]
@jbolinger It's generally not sample code (which is properly code-formatted by indentation). Rather, it's generally proto comments documenting services, messages, and fields, that are translated into Ruby comments. For example:

Source proto: https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/entity.proto#L42

Generated Ruby: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb#L29

**Comment by jbolinger** [comment]
@dazuma you might want to take a quick look at #2306 to see if the output looks good. 

It was a global search and replace for backticks, so pretty straightforward, but it was also normalizing multiple backticks into a single `+` character. With this change they will remain as multiple - does that make any difference for you?

**Comment by jbolinger** [comment]
@dazuma sounds good. I've started the release process so this should land in a day or two.
