### ISSUE TITLE
google.api.Retry specifies additional codes or all codes?

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2310]
[go/api-client-library-config-spec](go/api-client-library-config-spec) says that `Retry` specifies the _additional_ codes, _in addition_ to the default status codes, that should be retried on. 

However, [go/api-client-library-generation](go/api-client-library-generation) says that  `Retry` specifies _the_ codes, instead of the default status codes, that should be retried on.

**Comment by lukesneeringer** [comment]
Closing this as very stale given @noahdietz and @jadekler have done signficant work on retries, with an AIP pending.
