### ISSUE TITLE
Backfill retry codes in googleapis/googleapis

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2311]
We have to let GAPIC config take precedent over the protofile when it comes to retry codes right now, before the API protofiles in googleapis/googleapis have their appropriate retry codes defined.

**Comment by michaelbausor** [comment]
@andreamlin is this a bug? Or a todo item? I'm not sure how to categorize this so that someone could be assigned and take action on it.

**Comment by hzyi-google** [comment]
Obsolete.
