### ISSUE TITLE
Make sample instructions include ADC setup (for Cloud) and make them configurable per-API

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#2320]
The standalone sample files are meant to be standalone runnable by someone browsing the repository. As such, we have instructions in the file on installing pre-requisites for the sample to run (e.g. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/language/generated-samples/v1/language_sentiment_text.py#L19)

One thing that's missing in these instructions is setting up the Application Default Credentials that are needed. For someone new to GCP, this may also include setting up a project.

So, for our Cloud APIs, how about we add something like the following at the top of the file

```
To run this sample, you'll need to first
  - have created a project on the Google Cloud Platform Console (see https://cloud.google.com/docs/overview/#console_name)
  - download a service account key file to your local machine and set the environment variable GOOGLE_APPLICATION_CREDENTIALS to point to the location of that file (see https://cloud.google.com/docs/authentication/production)
  - install the latest package dependency by running
     pip install....
```

I'm open to tweaking the wording and the hyperlinks.

These instructions should also be configurable per API since
1. even within Cloud, the package to install in the last step depends on the API
2. non-cloud APIs will have different set-up instructions

**Comment by hkdevandla** [comment]
Obsolete.
