### ISSUE TITLE
Add support for explicit close of transport / channel

### ISSUE THREAD

**Issue by tseaver** [googleapis/gapic-generator#2337]
We have two reports where users are hitting system limits when creating large numbers of GAPIC-based clients:

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5523
- https://github.com/GoogleCloudPlatform/google-cloud-python/issues/6077

While that is not an expected usage pattern, we should still expose a way for callers to perform an explicit shutdown on the transport / channel in order to free up resources in such cases.

**Comment by tseaver** [comment]
In answering https://github.com/googleapis/google-cloud-common/issues/265, it occurs to me that exposing the `channel` as an attribute / read-only property of the transport would be the Right Thing(TM) for this issue  Users could then perform an explicit close:

```python
client.transport.channel.close()
```

**Comment by lukesneeringer** [comment]
This sounds right to me also.
