### ISSUE TITLE
[Python] generated docstrings for 'google.cloud.container_v1.types.Cluster' break docs build

### ISSUE THREAD

**Issue by tseaver** [googleapis/gapic-generator#2449]
```python
  File "/home/tseaver/projects/agendaless/Google/src/gcp/.nox/docs/lib/python3.6/site-packages/sphinx/util/logging.py", line 410, in filter
    raise SphinxWarning(location + ":" + message)
sphinx.errors.SphinxWarning: /home/tseaver/projects/agendaless/Google/src/gcp/container/google/cloud/container_v1/types.py:docstring of google.cloud.container_v1.types.Cluster:185:Inline interpreted text or phrase reference start-string without end-string.
> /home/tseaver/projects/agendaless/Google/src/gcp/.nox/docs/lib/python3.6/site-packages/sphinx/util/logging.py(410)filter()
-> raise SphinxWarning(location + ":" + message)
(Pdb) pp location
('/home/tseaver/projects/agendaless/Google/src/gcp/container/google/cloud/container_v1/types.py:docstring 
```

The actual file containing that docstring is `google/cloud/container_v1/proto/cluster_service_pb2.py`.  The offending bit is:

```
      current_node_version:
          [Output only] Deprecated, use `NodePool.version </kubernetes-e
          ngine/docs/reference/rest/v1/projects.zones.clusters.nodePool>
          `__ instead. The current version of the node software
          components. If they are currently at multiple versions because
          they're in the process of being upgraded, this reflects the
          minimum version of all nodes.
```

where the backtick-double-underscore is wrapped away from the closing angle bracket.

**Comment by andreamlin** [comment]
@tseaver How much of a blocker is this for the Yoshi team? We can bump this to a P1 if it's introducing a lot of toil on your end.

**Comment by tseaver** [comment]
@andreamlin 

> How much of a blocker is this for the Yoshi team? We can bump this to a P1 if it's introducing a lot of toil on your end.

Thanks, but /google-cloud-python/pull/6634/ adds a workaround for it in `container/synth.py`, so we aren't blocked.

**Comment by vchudnov-g** [comment]
@lukesneeringer Could you provide an update? (We're about to pass the SLO window on this one)

**Comment by noahdietz** [comment]
Is this related to a line wrapping bug #2159 ?

**Comment by vchudnov-g** [comment]
@lukesneeringer @hzyi-google Any updates on this? We're out of SLO.

**Comment by tseaver** [comment]
FWIW, the workaround added in https://github.com/googleapis/google-cloud-python/pull/6634 is still in effect when generating `google-cloud-container`:

```
synthtool > Replaced 'nodePool>\\n' in google/cloud/container_v1/proto/cluster_service_pb2.py.
synthtool > Replaced '(\\s+)`__ instead' in google/cloud/container_v1/proto/cluster_service_pb2.py.
```

**Comment by vchudnov-g** [comment]
@software-dov Any updates on this? Feel free to close if this becomes a non-issue because of the µ-generators.
