### ISSUE TITLE
Ruby CircleCI job is bugging out

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2458]
Starting failing at https://github.com/googleapis/gapic-generator/pull/2455.

**Comment by andreamlin** [comment]
Seems to be a CircleCI docker image problem: https://github.com/circleci/circleci-images/issues/275

**Comment by felicianotech** [comment]
The referenced CircleCI Issue above has been resolved.

**Comment by andreamlin** [comment]
Thanks for the update @felicianotech !
