### ISSUE TITLE
[node] JSON file cannot be resolved without explicit ".json" extension when using require

### ISSUE THREAD

**Issue by danielcardeenas** [googleapis/gapic-generator#2464]
#### Environment details

  - OS: Windows 10
  - Node.js version: 9.11.1
  - npm version: 6.1.0
  - `@google-cloud/datastore` version: 2.0.0

#### Steps to reproduce

  1. compile code with webpack

When compiling the code, the next error occurs:
```
ERROR in ./node_modules/@google-cloud/datastore/src/v1/datastore_client.js
Module not found: Error: Can't resolve './datastore_client_config' in '...\node_modules\@google-cloud\datastore\src\v1'
```

Due to require not having explicit '.json' extension, compiler fails to find the file
```javascript
// datastore_client.js
const gapicConfig = require('./datastore_client_config');
```

![image](https://user-images.githubusercontent.com/2654812/49335717-85a87f00-f5b8-11e8-9f63-49c1223d8406.png)

**Comment by andreamlin** [comment]
@alexander-fenster would you mind updating?
