### ISSUE TITLE
Use timeout value in config

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2481]
We never use the value of [`timeout_millis`](https://github.com/googleapis/gapic-generator/blob/6f888379edfdd5735fe7cbf65880dcf7d015f884/src/main/proto/com/google/api/codegen/config.proto#L251) from the GAPIC config. Nothing ever calls the derived [`MethodConfig#getTimeout`](https://github.com/googleapis/gapic-generator/blob/6f888379edfdd5735fe7cbf65880dcf7d015f884/src/main/java/com/google/api/codegen/config/MethodConfig.java#L53)

We should use this value in the generated surface.

**Comment by hzyi-google** [comment]
Obsolete as Gapic config is deprecated.
