### ISSUE TITLE
Go gapic generator should use gax-go/v2

### ISSUE THREAD

**Issue by jadekler** [googleapis/gapic-generator#2483]
https://github.com/googleapis/gax-go

cc @pongad @noahdietz

**Comment by noahdietz** [comment]
If you don't mind, can you catch me up on any API changes in `v2` that need to be reflected in the snippets/generated code? Or is this going to be as straight forward as changing the `gax-go` [import](https://github.com/googleapis/gapic-generator/blob/bf308627e3012ca7ae2042f05ee018578efadcd2/src/main/java/com/google/api/codegen/transformer/go/GoGapicSurfaceTransformer.java#L322) to `github.com/googleapis/gax-go/v2;gax;;`?

A quick look shows the `v1` pkg is referencing `v2`. So I'm guessing to start it can just be an import change?

Thanks for the patience as I ramp up on this :smile:

**Comment by jadekler** [comment]
No API changes at all :) Just need an import path change.

**Comment by noahdietz** [comment]
One "import path change" coming right up!

Thanks for the tee-ball-esque first gapic-generator issue :laughing:
