### ISSUE TITLE
Go generator should only change the version of a client when there are actually changes

### ISSUE THREAD

**Issue by jadekler** [googleapis/gapic-generator#2485]
Currently when I run artman to generate Go gapics, _every single gapic is updated every time_ because the `const versionClient = "20181217"` is updated.

It makes it really hard to figure out what actually changed. Can we please make this only happen to gapics that actually changed?

cc @noahdietz

**Comment by noahdietz** [comment]
Closing in favor of [google-cloud-go#1262](https://github.com/googleapis/google-cloud-go/issues/1262).
