### ISSUE TITLE
[Ruby] Service factory module names can conflict with model class names

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2492]
When generating google-cloud-dataproc, there is a service called `WorkflowTemplateService`. The ruby generator creates a factory module `Google::Cloud::Dataproc::V1::WorkflowTemplate` which contains the factory method for creating the service client. The gapic generator's current practice is to strip the words `Service` and `Client` from the name of this module. In this case, however, there is already a proto class named `WorkflowTemplate` that thus conflicts, resulting in code that does not load. (Note that the [proto](https://github.com/googleapis/googleapis/blob/master/google/cloud/dataproc/v1/workflow_templates.proto) names the service `WorkflowTemplateService` to thus distinguish it from the `WorkflowTemplate` data type, but the generator strips off `Service`.) The generator needs to detect this case, and refrain from stripping `Service` from the name if necessary to distinguish the names.

See https://github.com/googleapis/google-cloud-ruby/pull/2685

**Comment by jbolinger** [comment]
@dazuma I just CC'd you on a related internal request about this. Should we reconsider how this works (i.e. make it configurable or stop stripping vs. checking for this special case?)

**Comment by hzyi-google** [comment]
Hi @jbolinger @dazuma, is there a decision made on this issue? For now, it seems gapic-generator continues to trim `Service`s, but they are added back during packaging, and this is causing generated samples to not work. For example:

- `Service`s are added back for talent services: https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-talent/synth.py#L80
- But generated samples do not know this post-process, so the generated sample looks like this:
```ruby
require "google/cloud/talent"

# [START talent_list_companies]

# List Companies
def sample_list_companies(project_id)
  # [START talent_list_companies_core]
  # Instantiate a client
  company_client = Google::Cloud::Talent::Company.new version: :v4beta1

  formatted_parent = company_client.class.project_path(project_id)

  # Iterate over all results.
  company_client.list_companies(formatted_parent).each do |element|
    puts "Company: #{element.name}"
    puts "Display name: #{element.display_name}"
    puts "External ID: #{element.external_id}"
  end

  # [END talent_list_companies_core]
end
```
We would want the generated samples to be able to run against generated clients, so we can't append the `Service` in gapic-generator for SampleGen. Any ideas?

cc/ @googleapis/samplegen

**Comment by jbolinger** [comment]
No, we have not solved this. Synth is rewriting any name collisions for the time being.

The chances of name collisions are even higher in the micro-generator but we haven't decided upon a resolution strategy for it yet. I'm not really sure what you can do short-term other than special case it for instances like these where we know synth is patching it.

**Comment by beccasaurus** [comment]
Yikes. Best of luck in the micro. I hope y'all land on the side of using the full service name for sanity when working against protos. Tho the Rubyist in me hates the `Service` suffixes. Le sigh.

Hmm. @hzyi-google let's have the sample generator continue to trim `Service` suffixes and I'll use the synth scripts to add it back, as necessary. I can basically just look at each synth script for a given library and, if there is a `s.replace` adding `Service`, then I'll have it do the sample to the sample files.

**Comment by hzyi-google** [comment]
SGTM

**Comment by vchudnov-g** [comment]
@hzyi-google @jbolinger Any updates on this? We're out of SLO.

**Comment by hzyi-google** [comment]
There doesn't seem to be a plan to solve this issue in the monolith, but the micro generator will handle it.
