### ISSUE TITLE
[node][ruby] Broken link for toISOString in timestamp.proto

### ISSUE THREAD

**Issue by kinwa91** [googleapis/gapic-generator#2493]
See this broken generated markdown [link](https://github.com/googleapis/nodejs-automl/blob/master/src/v1beta1/doc/google/protobuf/doc_timestamp.js#L90). The Mozilla link ends with a `]`(breaks link) where in the [source proto](https://github.com/protocolbuffers/protobuf/blob/46a48e49aa8357bbeee8040819a35e59880e329a/src/google/protobuf/timestamp.proto#L116) it ended with `)`(correct)

**Comment by kinwa91** [comment]
Another link problem in `timestamp.proto` is the `joda.org` link:

https://github.com/googleapis/nodejs-automl/blob/17d4c65ea4908f643e883424b935a9626332105a/src/v1beta1/doc/google/protobuf/doc_timestamp.js#L94-L96

**Comment by alexander-fenster** [comment]
Some problem with Markdown parsing / printing / whatever. It's not only for Node, Ruby is also affected: https://github.com/googleapis/gapic-generator/search?q=toISOString&unscoped_q=toISOString

**Comment by alexander-fenster** [comment]
I suggest we don't investigate and fix it here since we'll be moving to microgenerators for both affected languages. Feel free to reopen if you think this is wrong.
