### ISSUE TITLE
ensure string literals properly escape characters as needed

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#2513]
At the moment, this means ensuring that double quotes `"` inside the string literal (eg in a samplegen `print` statement) get escaped if needed. I encountered this with a config that contained something like this:
```
- print:
  - "alpha\"beta\"gamma"

```

which resulted in an incorrect  PHP string literal in the generated sample, `"alpha"beta"gamma"`, instead of the correct `"alpha\"beta\"gamma"`

This is not a problem in Python, since we use single quotes `'` to delimit string literals. But in PHP we aren't escaping the doubles, and it causes an error. Don't know about other languages.

We should ensure the characters in {`"` `'` `%` `\n`} are escaped as needed  in each language in `- print`:

- [x] Python
- [x] Java
- [x] PHP
- [x] NodeJS

We should ensure the characters in {`"` `'` `%` `\n`} are escaped as needed  in each language in `- defaults`:

- [ ] Python
- [ ] Java
- [ ] PHP
- [ ] NodeJS

**Comment by eoogbe** [comment]
@hzyi-google What's the status of this?

**Comment by hzyi-google** [comment]
Haven't worked on it yet.

**Comment by vchudnov-g** [comment]
Update: we're currently working on this, iterating through the edge cases.

**Comment by hzyi-google** [comment]
Escaping special characters are covered in #2566.
We still need to make sure they are correctly escaped in `defaults` though. Leave this issue open for tracking.
Also bump it down since the rest of the work is non-blocking.
