### ISSUE TITLE
Samplegen: we should turn off default output handling for RPCs that returns `Empty`

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2519]
cc/ @vchudnov-g

**Comment by eoogbe** [comment]
@hzyi-google What the status of this?

**Comment by hzyi-google** [comment]
I haven't worked on it yet. Is it causing you any troubles?

**Comment by vchudnov-g** [comment]
Lowering to P2, though I hope we get to this soon.

**Comment by hzyi-google** [comment]
Fixed by #2617
