### ISSUE TITLE
String formatting functions are removed after introducing resource_name_generation

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2521]
This blocks release of some Java clients, such as the below Vision v1 library.

See comments of https://github.com/googleapis/google-cloud-java/pull/4161 for details.

It might be common for an API to only configure the resource path entities without specifying the `resource_name_generation` section that lists all the message objects that refer to those entities. In that case, `enableStringFormatFunctions` will be true, because it is true iff `resource_name_generation` is empty. However, once the `resource_name_generation` section is introduced, then we no longer generate the String format functions, and removing those functions will break some clients.

**Comment by andreamlin** [comment]
@chingor13 Besides Vision, what other GA'd APIs are affected by this?

**Comment by andreamlin** [comment]
still need to 
release artman with latest gapic-generator
add the `enableStringFormatFunctions` config param to the affected clients

**Comment by vchudnov-g** [comment]
@andreamlin Could you provide an update?

**Comment by andreamlin** [comment]
Done! Thanks for the reminder
