### ISSUE TITLE
SampleGen: Update the generated CLI to use consistent `--param-name=""` flags for all languages

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2550]
Today, we vary the CLI flags used to pass parameters to generated samples (when run) across the languages:
 - Python: `--file_path="image.png"`
 - PHP: `--filePath="image.png"`

I advocate that these are all changed to follow a `--file-path="image.png"` dash-es convention

Reasoning:
 - Almost all common *nix tools follow a standard `--foo-bar=` naming convention, so this does not conflict with any particular programming language's convention
 - It will be somewhat useful for any users who happen to run samples in many languages
 - It will be very, very useful for any sample developers who are generating samples in many languages
 - It will allow tools which test samples in many languages to use a common interface across the CLIs for executing samples for testing

**Comment by vchudnov-g** [comment]
Agreed that the CLI argument convention (a) should be the same across languages, and (b) should adhere to an accepted standard.

I'd be OK with either snake_case or dash-case, but I prefer snake_case because IMO it's much more prevalent (and also what we use in YAML, etc.).

**Comment by vchudnov-g** [comment]
Hmm, a cursory look at a few `man` pages suggests that both snake_case and dash-case are in wide use, but perhaps dash-case is used a bit more....

**Comment by devbww** [comment]
For what it's worth, when gapic supports C++, and if that support uses Abseil to handle CLI flags, then snake_case would be preferable.

**Comment by beccasaurus** [comment]
> if that support uses Abseil to handle CLI flags, then snake_case would be preferable.

Hoping we won't run into issues with languages where the opposite is true

The only reason why I would like to see `snake_case` is because it provides a nice, deterministic mapping from `YAML <--> CLI`, which I would like a lot!

**Comment by vchudnov-g** [comment]
It sounds like we should be able to do either. My personal preference is snake_case as well. We can go with that if that's the majority opinion. @hzyi-google ?

**Comment by hzyi-google** [comment]
OK let's do snake_case.

**Comment by hzyi-google** [comment]
@devbww I don't actually think the casing here would cause any troubles for Abseil though. The CLIs here are only used for generated samples, for which we expect to be standalone executable, not a generated "package" to be managed by any dependency management tool. but I can never tell :/
We don't see sanke_case causing any problems to existing languages, at least not for now, so let's just do snake_case.
