### ISSUE TITLE
Is there a tutorial anywhere?

### ISSUE THREAD

**Issue by irthomasthomas** [googleapis/gapic-generator#2556]
Hello,

I am looking to build an interface to the sheets api, in a language not currently supported. My plan was to start with the javascript version and rewrite it for my needs. But I am having a devil of a time deciphering the documents. Are there any other guides or tutorials out there?

Thanks!

**Comment by irthomasthomas** [comment]
I find these steps confusing. Is step 1 talking about /usr/local/bin? Why not just say that? And what is YOUR_PROTO_DIR and YOUR_PROTO_FILE?

1. The include directory with the proto files bundled with protoc (from the protoc setup step). Hereafter, this will be referenced as ${PROTOC_INCLUDE_DIR}. 
3. The directory containing your proto. Hereafter, this will be referenced as ${YOUR_PROTO_DIR}.
4. Your proto file (or files). Hereafter, this will be referenced as ${YOUR_PROTO_FILE}.

**Comment by eoogbe** [comment]
We do not have another tutorial besides the README docs. The directories refer to the location of your .proto files. If your protos are located at `~/protos/example.proto`, you would have:
PROTO_INCLUDE_DIR: `/usr/local/bin/protoc/include`
YOUR_PROTO_DIR: `~/protos`
YOUR_PROTO_FILE: `~/protos/example.proto`

If the directory containing the googleapis repo is `~/googleapis`, the command to run would be:
```shell
protoc -I=/usr/local/bin/protoc/include -I=~/googleapis -I=~/protos \
  --include_imports --include_source_info -o ~/protos/example.desc ~/protos/example.proto
```

**Comment by vchudnov-g** [comment]
Let us know if you have more questions, @irthomasthomas !

**Comment by irthomasthomas** [comment]
Sorry chaps I was away and haven't had chance to try it yet. But your clarification looks good, and I believe it answers my questions. Many thanks. @vchudnov-g @eoogbe
