### ISSUE TITLE
Where are files for sheets api?

### ISSUE THREAD

**Issue by irthomasthomas** [googleapis/gapic-generator#2557]
Sorry to keep posting issues, but I don't know where else to go for help. I'm working through your instructions and I come to look for the sheets api but I can not find the prerequisite yaml file. I can find json files from the discovery service but no yaml file.

**Comment by eoogbe** [comment]
The Sheets API does not have proto files released. It can't be generated using the GAPIC generator. You can access the Sheets API [here](https://developers.google.com/sheets/api/)
