### ISSUE TITLE
SampleGen: Java LRO missing import for LongRunningXMetadata [API Speech V1]

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2592]
I generated a sample for [Speech V1 `LongRunningRecognize`](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.Speech.LongRunningRecognize)

The sample generated includes the following:

```java
 64       LongRunningRecognizeRequest request =
 65           LongRunningRecognizeRequest.newBuilder().setConfig(config).setAudio(audio).build();
 66       OperationFuture<LongRunningRecognizeResponse, LongRunningRecognizeMetadata> future =
 67           speechClient.longRunningRecognizeOperationCallable().futureCall(request);
```

([sample code](https://github.com/beccasaurus/gapic-docs-samples/blob/master/code-samples/speech/v1/java/src/main/java/com/google/cloud/examples/speech/v1/LongRunningRecognizeOperationCallableLongRunningCallableSpeechTranscribeAsync.java) – _lol it has lots of 'Metadata' imports because a script of mine kept adding them when I regenerated_)

I got an error because `LongRunningRecognizeMetadata` is not imported.

By default, the imports included:

```java
import com.google.cloud.speech.v1.LongRunningRecognizeRequest;
import com.google.cloud.speech.v1.LongRunningRecognizeResponse;
import com.google.cloud.speech.v1.LongRunningRecognizeMetadata;
```

And it worked when I added Metadata

```java
import com.google.cloud.speech.v1.LongRunningRecognizeRequest;
import com.google.cloud.speech.v1.LongRunningRecognizeResponse;
```

Not sure if this is generic to LROs or something Speech specific :)

Poking around other LROs I don't see Metadata messages, e.g. a [Video Intelligence LRO](https://cloud.google.com/video-intelligence/docs/reference/rpc/google.cloud.videointelligence.v1#google.cloud.videointelligence.v1.VideoIntelligenceService.AnnotateVideo)

/cc @hzyi-google

**Comment by hzyi-google** [comment]
Should the later two code snippets be swapped?
It does seem to be generic to LROs. It's very possible that I thought the `Metadata`s are not needed so I did not teach gapic-generator to import them :( I'll check later.

**Comment by hzyi-google** [comment]
If you specified `.*` in calling form, the generated sample package would still not compile due to #2599. If you need to run the sample in the meantime, delete all the samples whose names start with `LongRunningXCallable` (I am 95% sure you don't need those samples for your use case), and the rest of them would compile.
