### ISSUE TITLE
SampleGen: Change accessing a map field by key from using `{ }` to using `[ ]`

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2600]
on success:
- [ ] define
- [ ] print

parameters:
- [ ] default
- [ ] attributes

**Comment by vchudnov-g** [comment]
Marking P1 because it's important we settle this one way or the other before wide adoption, but it's not blocking development of other features.

**Comment by landrito** [comment]
@hzyi-google any updates on this?

**Comment by vchudnov-g** [comment]
Let's fix this soon so that micro-generators can directly implement the `[ ]` style

**Comment by hzyi-google** [comment]
I'll get to this once I finish default calling forms and sample tester manifests.

**Comment by vchudnov-g** [comment]
We decided to defer this even longer, given the complication of implementing this in the monolith and the relatively higher importance of other features.

**Comment by hzyi-google** [comment]
Moved to backlog. https://github.com/googleapis/gapic-generator/wiki/feature-backlog
