### ISSUE TITLE
Go: generated examples should have comment identifying gen'd types

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator#2620]
There has been feedback indicating confusion around the difference between the `genproto` pkg and the `gapic` pkg. Because of naming & alias name misunderstandings, some see the former as the "old" client and the latter as the "new" one, which then gets folks confused as to why they need both imported.

The `genproto` pkg contains the generated types for the API protos, while the `gapic` pkg contains the generated client that consumes them.

To help clear this up, the generated example snippets should include a comment above the use of the `genproto` types indicating where it comes from.

cc @broady @jadekler

**Comment by noahdietz** [comment]
@broady I've been poking around gapic-generator looking at how to add these request object import comments to the generated example snippets. It is a bit of work to add this to the existing gapic-generator implementation. It would be trivial to add this to the micro-generator implementation that we will move to in the near future.

Since this is more of a nice-to-have, I'd prefer to move this issue to gapic-generator-go (the micro-generator) and implement it there (exclusively). @jadekler gave +1 to this offline. WDYT?

Same applies to [golang-samples #791](https://github.com/GoogleCloudPlatform/golang-samples/issues/791), I'd do both changes in *just* the micro-generator.

**Comment by broady** [comment]
+1 for micro-generator

**Comment by noahdietz** [comment]
Closing in favor of [gapic-generator-go#107](https://github.com/googleapis/gapic-generator-go/issues/107)
