### ISSUE TITLE
SampleGen: set Map field defaults on request objects

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2624]
I need to author a sample which requires configuring the values of a Map on the request object.

[`rpc CreateJob`](https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job_service.proto#L43) takes a [`CreateJobRequest`](https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job_service.proto#L131-L143) which has a required [`Job`](https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job.proto) on which I need to demonstrate setting [`custom_attributes`](https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job.proto#L231).

There are two parts to this:

1. To **unblock** the sample, the ability to set literal defaults
2. The ability to provide command-line arguments / method parameters for these values

### #1 Providing default literal values

**`Map<string, string> string_to_string_map = 0;`**

 -
    ```yaml
    defaults:
    - string_to_string_map["Example key"]="Example valye"
    ```

**`Map<string, int32> string_to_int_map = 1;`**

 -
    ```yaml
    defaults:
    - string_to_int_map["Example key"]=5
    ```

**`Map<int32, string> int_to_string_map = 2;`**

 -
    ```yaml
    defaults:
    - int_to_string_map[5]="Example value"
    ```

**`Map<string, string[]> string_to_strings_map = 3;`**

 -
    ```yaml
    defaults:
    - string_to_strings_map["Example key"][0]="First repeated value"
    - string_to_strings_map["Example key"][1]="Second repeated value"
    ```

**`Map<string, MyMessage> string_to_object_map = 4;`**
```
message MyMessage {
  bool enabled = 0;
  string name = 1;
  repeated string words = 2;
}
```

 -
    ```yaml
    defaults:
    - int_to_string_map["Cool Object"].enabled=True
    - int_to_string_map["Cool Object"].name="Cool object"
    - int_to_string_map["Cool Object"].words[0]="Cool"
    - int_to_string_map["Cool Object"].words[1]="object"
    - int_to_string_map["Another Object"].name="I am an object with a different key"
    ```

### #2 Method Parameters (and CLI)

This gets a bit more fun.

With Arrays, it's been OK for us to use literal index values in our configuration to define _which index_ a given value is for:

```yaml
defaults:
- words[0]="First"
- words[1]="Second"
```

It's not critical that the index, itself, be configurable. This is totally, perfectly okay. I have yet to run into or think of a use-case where providing an index via method param/CLI is important.

For Maps, it seems reasonable to want to pass in the Key and Value, amiright?

Perhaps not critical, though.

We can (and maybe should) support this in the same way that we do Arrays:
 - the index value (be it an int index or T key) is statically set in the sample configuration
 - the value of the element can be provided via method param (CLI)

```yaml
defaults:
- config.attributes["DELIMITER"]="%"
- config.attributes["Max Size"]=12
- config.attributes["Options"][0]="First option"
- config.attributes["Options"][1]="Second option"
```

To create a method parameter for the _value_ of any of these:

```yaml
attributes:
- parameter: config.attributes["Max Size"]
  sample_argument_name: max_size
```

I can't think of any ways *I like* to make the key something configurable.

```yaml
defaults:
- config.attributes["Your Project Key"]="Your Value"
attributes:
- parameter: ?
  sample_argument_name: attribute_value
- parameter: config.attributes["Your Project Key"]
  sample_argument_name: attribute_value
``` 

----

I'd like the following features:

 1. Setting default literal key and literal value
 2. Setting default literal key and parameterized value (built on top of the current Array support)

I have no need to look into parameterizing keys at this time.

/cc @googleapis/samplegen

**Comment by vchudnov-g** [comment]
Cool, thanks for the ideas. We'll write up a design, discuss, and implement. This will be an interesting feature!

**Comment by beccasaurus** [comment]
My hope is that it won't be all that interesting 😉

Ignore everything I said about the possibility of dynamic map keys and then it's the exact same as the Array support we have today except `[0]` can support `["key"]`.

If I try to generate this today, I get:
> java.lang.IllegalArgumentException: expected number after '[': custom_attributes["my_attribute"][0]="My attribute value"

**Comment by vchudnov-g** [comment]
Yeah, if it's just static keys (ie not a CLI arg or sample func param), then it's a minor extension to the config and shouldn't be too hard to implement. Plumbing, plumbing,....

**Comment by tswast** [comment]
I tried this out for BigQuery Data Transfer today. FYI: the protobuf library doesn't seem to use Struct/Map in the expected way.

```
    transfer_config = {
        "destination_dataset_id": "your_dataset_id",
        "display_name": "Your Scheduled Query Name",
        "data_source_id": "scheduled_query",
        "params": {
            "query": "SELECT 1;  -- Use standard SQL syntax.",
            "destination_table_name_template": "your_table_{run_date}",
            "write_disposition": "WRITE_TRUNCATE",
            "partitioning_field": "",
        },
        "schedule": "every 24 hours",
    }

    response = client.create_transfer_config(parent, transfer_config)
```

Fails with `ValueError: Protocol message Struct has no "query" field.`

If I then try:

```
    transfer_config = {
        "destination_dataset_id": "your_dataset_id",
        "display_name": "Your Scheduled Query Name",
        "data_source_id": "scheduled_query",
        "params": {
            "fields": {
                "query": "SELECT 1;  -- Use standard SQL syntax.",
                "destination_table_name_template": "your_table_{run_date}",
                "write_disposition": "WRITE_TRUNCATE",
                "partitioning_field": "",
            },
        },
        "schedule": "every 24 hours",
    }

    response = client.create_transfer_config(parent, transfer_config)
```

Fails with `TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.Value got str.`.

I actually have to convert to protobuf using ParseDict.

```
    transfer_config = google.protobuf.json_format.ParseDict(
        {
            "destination_dataset_id": "your_dataset_id",
            "display_name": "Your Scheduled Query Name",
            "data_source_id": "scheduled_query",
            "params": {
                "fields": {
                    "query": "SELECT 1;  -- Use standard SQL syntax.",
                    "destination_table_name_template": "your_table_{run_date}",
                    "write_disposition": "WRITE_TRUNCATE",
                    "partitioning_field": "",
                }
            },
            "schedule": "every 24 hours",
        },
        bigquery_datatransfer_v1.types.TransferConfig(),
    )

    response = client.create_transfer_config(parent, transfer_config)
```

I think that's probably more an issue with the generated client code than the sample, but one or the other has to change.

**Comment by hzyi-google** [comment]
@tswast This seems to be a Protobuf Python question. @lukesneeringer Can you take a look (just the last comment. You can ignore everything else)?

**Comment by beccasaurus** [comment]
The protobuf docs for [Map Fields](https://developers.google.com/protocol-buffers/docs/reference/python-generated#map-fields) talk more about how existing field objects behave, not how to instantiate them.

Is there a `type` representing that request which can be constructed instead of using a Dict?

I've seen Python samples which use all objects to construct requests (rather than relying on some of the Dict-to-object functionality)

**Comment by tswast** [comment]
That's maybe a different discussion, but yeah I agree it's a bit odd that we try to pass in a Dict and not protobuf objects in the generated samples. It means we run into problems like my above comment. https://github.com/googleapis/gapic-generator/issues/2624#issuecomment-482751619

One problem with Python protos is lots of properties aren't actually settable. For example, you can't set a repeated (array/list) property to a list of objects. You actually have to call `property_name.append(some_object)`. Maps may work similarly where you can't set them all at once, just key-by-key.

**Comment by beccasaurus** [comment]
> One problem with Python protos is lots of properties aren't actually settable

FYI this is the same in most, if not all, languages.

**Comment by hzyi-google** [comment]
Update on the original issue:

- Setting default values should already work using `{}`:

```yaml
parameters:
  defaults:
  - string_to_strings_map{"Example key"}[0]="First repeated value"
```
We should add some tests in baseline however.

- Configuring map keys to be a parameter isn't supported yet.

**Comment by hzyi-google** [comment]
Move to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
