### ISSUE TITLE
SampleGen: configure sample to use default API version (import language instead of import language_v1)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2627]
**Feature Request:**

For 3** of our programming languages, we offer a default API version which is imported by default.

> ** _all dynamic languages, except PHP_

`=>` _Most of our code samples use this._  
`=>` _We **rarely** specify the API version for these languages._   
`=>` _We generally **only** specify versions for opting into Beta features._

When we generate samples, GAPIC does not know which version is the default. This is managed by the packaged API library (which wraps GAPIC generated source). So, to generate this syntax, the samples need to know if the version being generated is the default. Also, it might be beneficial to be able to generate both default-style and explicit-version-style samples without editing the GAPIC config (not required), which might make this an opportunity for a CLI flag.

Anyway! We'll need this.

P1 _(high priority after 7 language coverage, as part of the canonical sample matching project)_

Just take a look at any live samples on cloud.google.com and you'll see that none of them specify versions. [Speech](https://cloud.google.com/speech-to-text/docs/sync-recognize),[Video Intelligence](https://cloud.google.com/video-intelligence/docs/analyze-labels), [Natural Language](https://cloud.google.com/natural-language/docs/analyzing-entities), [Cloud Vision](https://cloud.google.com/vision/docs/detecting-faces), etc 

---

Default examples:

 - 🚀 *Node.js*
    ```js
    const speech = require('@google-cloud/speech');

    // Creates a client
    const client = new speech.SpeechClient();
    ```

 - 🐍 *Python*
    ```py
    from google.cloud import speech
    from google.cloud.speech import enums
    from google.cloud.speech import types

    client = speech.SpeechClient()
    ```

 - 💎 *Ruby*
    ```ruby
    require "google/cloud/speech"

    speech = Google::Cloud::Speech.new
    ```

`=>` @googleapis/samplegen

**Comment by landrito** [comment]
@hzyi-google any updates on this?

**Comment by beccasaurus** [comment]
FWIW, I'm not expecting anything on this under later in the Quarter

=> P2 for now

**Comment by hzyi-google** [comment]
@beccasaurus Can we hand this over to use `synth`?
