### ISSUE TITLE
Java doccomment does not contain sample usage

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2649]
After generating a client, @kolea2 noticed that the methods don't have sample usage. Is there a config that is incorrect here or is this perhaps a bug?

Java missing sample: https://github.com/googleapis/google-cloud-java/blob/master/google-api-grpc/grpc-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechGrpc.java#L259 

Python method: https://github.com/googleapis/google-cloud-python/blob/master/speech/google/cloud/speech_v1/gapic/speech_client.py#L333

**Comment by landrito** [comment]
@andreamlin is there a reason why this is the case?

**Comment by andreamlin** [comment]
For the given Java class, that is a file generated by the [grpc-protoc plugin](https://github.com/grpc/grpc-java/tree/master/compiler). We don't own that plugin. Also, even though that class is public, it isn't really meant to be used by user; our gapic-generated classes wrap them.

For the given Python class, I'll have to do a little more digging. A very premature guess is that we might not generate sample code for streaming methods.

**Comment by andreamlin** [comment]
For the python method given, there is a method sample inside the method. It's a little bare, but it's still there.

**Comment by andreamlin** [comment]
feel free to reopen for followup questions
