### ISSUE TITLE
SampleGen: Node.js: generate samples in `samples/{version}`

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2681]
Rather than:

```
src/samples/v1/*.js
```

I would like:

```
samples/v1/*.js
```

`src/samples/{version}` => `samples/{version}`

That's all!

Basically, in synth scripts I'm currently moving the generated `src/samples` dir into `samples/{version}` so we may as well generate it that way 😄

@googleapis/samplegen

**Comment by hzyi-google** [comment]
Fixed by #2729
