### ISSUE TITLE
Accessing unset fields in header request params in PHP

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2683]
See https://gist.github.com/jdpedrie/c816046f188a56edc2b06ee07ae98039 for a snippet of the Genomics PHP client library, and a comment showing what the generated method should look like.

**Comment by andreamlin** [comment]
cc @dwsupplee

**Comment by andreamlin** [comment]
filing as P1 because it is blocking client generation for at least one APIs.

**Comment by dwsupplee** [comment]
We saw this happen on AutoML's [UpdateDataset](https://github.com/googleapis/googleapis/blob/master/google/cloud/automl/v1beta1/automl_gapic.yaml#L265-L276) call. It seems as though when we saw this issue come up, a `dataset` wasn't a required parameter in the gapic configuration. A `dataset` is now required, so we shouldn't see this issue come up with our next generation - but this may be something worth investigating for future calls where we may attempt to add a resource header based on an optional argument. It is probably safe to move this to P2.

**Comment by michaelbausor** [comment]
Moving to P2. I also created a PR just to see the bug in baselines: https://github.com/googleapis/gapic-generator/pull/2687. Seems like it also affects Python, on this line: https://github.com/googleapis/gapic-generator/pull/2687/files#diff-f7e1b0b3f703b5c8ece5073db3bce027R1771

**Comment by dwsupplee** [comment]
This issue has struck again: https://github.com/googleapis/google-cloud-php/blob/5387613599af844242b1b1ffb5aa722579cd61b4/Dialogflow/src/V2/Gapic/AgentsGapicClient.php#L893-L895

**Comment by vchudnov-g** [comment]
@hzyi-google Could you PTAL?

**Comment by vchudnov-g** [comment]
@hzyi-google Any updates on this? When do you expect you'll have bandwidth to address this?

**Comment by hkdevandla** [comment]
@dwsupplee , Not sure about the next steps here. It looks like non-actionable at this point. So I will close this bug for now. Please re-open if there is anything that needs to be done or fixed.
