### ISSUE TITLE
Don't require the GAPIC config for discogapic

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2690]
It's a slight pain to refresh the GAPIC config for the Compute client.

This work would best be started after we have started migration to a GAPIC config v2.

**Comment by vam-google** [comment]
Discogapic config for Compute client is now [generated automatically](https://github.com/googleapis/discovery-artifact-manager/blob/master/gapic/google/compute/v1/BUILD.bazel#L12) via bazel (and this is how Yoshi generates the client for publishing). 

Closing as obsolete.
