### ISSUE TITLE
Support for V2 config with no interfaces

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#2693]
A v2 config that configures no interfaces will break gapic-generator here: https://github.com/googleapis/gapic-generator/blob/master/src/main/java/com/google/api/codegen/config/GapicProductConfig.java#L174

Should we:
 - Fix this, and any other places where we assume at least one interface exists in config proto, and also support generation for unlisted interfaces as well as unlisted methods, or:
- Require that the v2 config contain an empty interface config for each interface to be generated.

**Comment by andreamlin** [comment]
thanks for filing this

i would like to not have to make everything in config v2 optional, including the interfaceConfigProtos.

investigating.

**Comment by vchudnov-g** [comment]
@hzyi-google Any updates on this? We're out of SLO.

**Comment by vchudnov-g** [comment]
@hzyi-google Any updates on this?

**Comment by hzyi-google** [comment]
I believe this has already been fixed, as we've already have APIs without `- interfaces`.
