### ISSUE TITLE
Use the service YAML `title:` as the API name in generated artifacts

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator#270]
What:
The current README auto-generates the service title, which doesn't always look right. For example, "Google Pubsub API" in http://pythonhosted.org/gax-google-pubsub-v1/ should be "Google Cloud Pub/Sub API", per https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.yaml#L7.

We can also see this in package repositories:
- [Python](https://pypi.python.org/pypi/gapic-google-cloud-logging-v2): now correct
- [Java](https://search.maven.org/#artifactdetails%7Ccom.google.cloud%7Cgoogle-cloud-logging%7C1.3.1%7Cjar): needs to be fixed

Why:
Use the correct name for our APIs. Even more importantly, this impacts our branding for the [Stackdriver family of APIs](https://cloud.google.com/stackdriver/docs/).
- [x] C#
- [ ] Go
- [ ] Java
- [ ] NodeJS
- [ ] PHP
- [x] Python
- [x] Ruby

**Comment by geigerj** [comment]
As part of this, let's ensure that the source and usage of the API name/title is consistent across all of our tools. I think `artman`, `packman`, and `toolkit` all have some sort of concept of API name -- we should ensure these do not vary without justification, and eliminate any duplicate concepts (for example, maybe the `api_name` field of the Artman config/`pipeline_args`).

**Comment by bjwatson** [comment]
@geigerj Has this been partially done?

**Comment by geigerj** [comment]
@bjwatson This is done for Python. (Just checked the box.)

**Comment by bjwatson** [comment]
Thanks @geigerj!

**Comment by eoogbe** [comment]
@bjwatson Is this still relevant?

**Comment by bjwatson** [comment]
@eoogbe This needs to be evaluated by the language leads for the remaining languages.

@geigerj Why do http://pythonhosted.org/gax-google-pubsub-v1/ and http://pythonhosted.org/gax-google-logging-v2/ show the wrong names? They should be "Google Cloud Pub/Sub API" and "Stackdriver Logging API", respectively.

**Comment by eoogbe** [comment]
cc/ @jskeet @pongad @garrettjonesgoogle @lukesneeringer @michaelbausor @geigerj Language leads for remaining languages

**Comment by geigerj** [comment]
@bjwatson Those pages are out-of-date. The packages are called `gapic-google-{api}` now (not `gax-...`). For example, here's an [index.rst](https://github.com/googleapis/api-client-staging/blob/master/generated/python/gapic-google-cloud-pubsub-v1/docs/index.rst) checked into `api-client-staging` that shows "Google Cloud Pub/Sub API".

**Comment by jskeet** [comment]
We don't generate the README for C#, and probably won't any time soon.
This will be relevant when generating the csproj (project) file, so cc @chrisdunelm but I'm going to tick C# as the README part is irrelevant.

**Comment by garrettjonesgoogle** [comment]
We don't generate the README yet for Java either, so checking the box since it is N/A.

**Comment by bjwatson** [comment]
@jskeet @garrettjonesgoogle We should think more broadly than just the README. We autogen the API name in other places. For example, I see that the [Maven Logging package](https://search.maven.org/#artifactdetails%7Ccom.google.cloud%7Cgoogle-cloud-logging%7C1.3.1%7Cjar) shows:

```xml
<name>Google Cloud Logging</name>
```

This should be "Stackdriver Logging API".

**Comment by jskeet** [comment]
Within google-cloud-dotnet we have an API catalog which includes all manner of things like this, that most code doesn't care about (and which we don't want to have to rerun codegen to change):
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/apis.json

While eventually it might be nice to have all the config in a single place, the reality is that we're finding this split very pragmatic.

**Comment by bjwatson** [comment]
As long as the .NET generated artifacts are showing the correct API names, then there's no problem within the scope of this issue.

**Comment by hzyi-google** [comment]
Obsolete.
