### ISSUE TITLE
Java gapic: Pagination wrappers create a circular dependencies between Client & Stub layers

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/gapic-generator#2709]
Currently the pagination wrappers live in the Client, which also delegates to the stub:
```java
public final ListTablesPagedResponse listTables(ListTablesRequest request) {
  return listTablesPagedCallable().call(request);
}
public final UnaryCallable<ListTablesRequest, ListTablesPagedResponse> listTablesPagedCallable() {
  return stub.listTablesPagedCallable();
}

public class ListTablesPagedResponse extends AbstractPagedListResponse // ...
public static class ListTablesPage extends AbstractPage // ...
public static class ListTablesFixedSizeCollection extends AbstractFixedSizeCollection // ...
```

The stub will import the pagination wrappers and use it construct the callable chain:
```java
private final UnaryCallable<ListTablesRequest, ListTablesPagedResponse> listTablesPagedCallable;

this.listTablesPagedCallable =
        callableFactory.createPagedCallable(
            listTablesTransportSettings, settings.listTablesSettings(), clientContext);
```

And its also used in the stub settings:
```java
private final PagedCallSettings<ListTablesRequest, ListTablesResponse, ListTablesPagedResponse>
      listTablesSettings;
```

**Comment by igorbernstein2** [comment]
I think this be an issue for build systems like bazel and makes it hard to define a consistent public surface for client like bigtable.

I'm not sure how this can be fixed in a backwards compatible manner. But I figured I would start a discussion

**Comment by vam-google** [comment]
@igorbernstein2 Why is this an issue for Bazel system (or more importantly why is any build system affected by this)?

**Comment by igorbernstein2** [comment]
I was under the impression that bazel doesn't allow circular dependencies.

**Comment by vchudnov-g** [comment]
@vam-google Any updates on this? We're out of SLO.

**Comment by software-dov** [comment]
@vam-google @igorbernstein2 can you two hash out importance/fixibility?

**Comment by vam-google** [comment]
I want to say that this can be closed. @igorbernstein2 WDYT?

**Comment by igorbernstein2** [comment]
The practical issue for me is that it forces me to keep the generated gapic clients as part of the public surface in the Bigtable client. (Bigtable client provides a manually written layer on top of the gapic generated stub, it doesn't need the generated client).

However, I don't think moving this to the stub w/o api breakage will be easy, the classes are way too intertwined to split the layers.
