### ISSUE TITLE
Support parsing field_name_patterns in gapic config v2

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2734]
Sometimes we need to narrow down the type of a resource type, say from a resource set to a single resource. This can be done by reusing the field_name_patterns in the gapic config v2.

This is needed for Java and especially C#, where the field names are based on the resource type.

**Comment by hzyi-google** [comment]
No longer supported as we decided to redesign multi-pattern resource names and generate all the overloads in cases of child_type.
