### ISSUE TITLE
Fix and re-enable showcase tests

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#2735]
Showcase tests were disabled in https://github.com/googleapis/gapic-generator/pull/2727 due to not being compatible with the latest changes to resource name annotations.

**Comment by noahdietz** [comment]
Looks like work was started to  update the annotations here [#131](https://github.com/googleapis/gapic-generator-python/pull/123) but stalled due to micro-generator images not being updated with the api-common-proto changes. Starting  there...

**Comment by noahdietz** [comment]
Python: waiting on a release with [fix](https://github.com/googleapis/gapic-generator-python/pull/123)

**Comment by noahdietz** [comment]
Kotlin: I will take a shot at updating this micro-generator, but if it becomes too much of a time suck, I will merge w/o Kotlin support and wait for Joe to return

**Comment by noahdietz** [comment]
Kotlin: the showcase CI for kotlin-smoke-test was disabled via [gapic-showcase#136](https://github.com/googleapis/gapic-showcase/pull/136) temporarily. [gapic-showcase#137](https://github.com/googleapis/gapic-showcase/issues/137) to track its reinstatement.

**Comment by noahdietz** [comment]
Resource annotation updates lands in gapic-showcase v1.2.0

**Comment by noahdietz** [comment]
Looks like #2646 fixes this by re-enabling with the showcase v0.2.0
