### ISSUE TITLE
Python generator produces bad content block following 'raw' directive

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator#2736]
Generated docstrings had content blocks with incorrect indentation following the ['raw' directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through). 

This came up while generating Dialogflow. See https://github.com/googleapis/dialogflow-python-client-v2/pull/123/commits/1e2250a8138d256bc47f92c39a49f6fa93a1d748#diff-5ee1b23c828be645ab5561df5053bd49

The generator produced: 
```
                .. raw:: html
                <pre>curl \
```

After a replacement with synthtool:

```
                .. raw:: html

                   <pre>curl \
```

**Comment by andreamlin** [comment]
@lukesneeringer Would you mind taking a look at this?

The docstrings are pulled from the proto comments.

**Comment by noahdietz** [comment]
@lukesneeringer any ideas here? Should we reassign to @software-dov or @hzyi-google ?

**Comment by software-dov** [comment]
Fixed up via synth, the transition to the microgenerator obviates a real fix.
