### ISSUE TITLE
Oneof documentation

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#274]
Python currently documents

```
message Foo {
  ...
  oneof {
    A a = 20;
    B b = 21;
  }
  ...
}
```

The same as

```
message Foo {
  ...
  A a = 20;
  B b = 21;
  ...
}
```

We should investigate a better way of doing this by alerting the user that fields `a` and `b` cannot both be set. Presumably this applies to all languages, not just Python.
- [ ] NodeJS
- [ ] PHP
- [ ] Python
- [ ] Ruby

**Comment by bjwatson** [comment]
Simple solution is to add boilerplate text to message and/or method documentation to indicate the mutually exclusive choices.

Needs to be done for ALL languages!

**Comment by geigerj** [comment]
Example: https://github.com/googleapis/api-client-staging/pull/49/files#diff-b501d76c46c9dbbbe708c8a4ce8a5a4dR216

**Comment by jskeet** [comment]
The *message* documentation is presumably down to proto. For methods with parameter flattening, I think we may still have an issue for C# and Java, but it's a slightly different one. It was considered around the time of resource name design, but not implemented. Will raise a separate issue for this, but "tick" C# as done for this one.

**Comment by geigerj** [comment]
Agree that this documentation work is not applicable to languages that will address oneofs through #1057.

**Comment by eoogbe** [comment]
Is this still relevant?

**Comment by geigerj** [comment]
@eoogbe I think so -- we should still be documenting proto3 `oneof`s (clearly, although I don't think it's accurate to say we've been treating this missing additional documentation as release-blocking.

**Comment by hkdevandla** [comment]
Obsolete.
