### ISSUE TITLE
Add ability to suppress unwanted autogenerated code for clients that use the gapic  as a implementation detail

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/gapic-generator#2742]
Cloud Bigtable's client API differs from it's protocol. So it requires a manual wrapper and uses GAPIC as an internal implementation detail. Unfortunately this means that the underlying gapic api is exposed alongside the intended api. This is not only confusing to customers, but also forces the client developers to keep the gapic surface stable. To avoid this issue I'm currently using synth.py script to mutate the autogenerated to hide it:
https://github.com/googleapis/google-cloud-java/pull/5035

It would be nice if there was a way to do this without this hack

**Comment by andreamlin** [comment]
@igorbernstein2 Which generated entities is this referring to, specifically?

**Comment by igorbernstein2** [comment]
I would love to be able to exclude the auto generated clients (leaving behind only the stubs).
Also would be great to make the callable factories package private.
You can find a full list of files that I'm removing here:
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/synth.py

**Comment by igorbernstein2** [comment]
Also related: it would be nice for gapic to generate a GrpcBaseStub. That exposes the base callables w/o retries. This would allow manually written clients avoid unnecessary links in the callable chains

**Comment by igorbernstein2** [comment]
I was able to address the GrpcBaseStub need in gax:
https://github.com/googleapis/gax-java/pull/891

And I don't think it will be possible to disable generation of clients as they have a circulat dependency with the stubs.

So I'm going to close this
