### ISSUE TITLE
Upgrade gax version to 1.44.0?

### ISSUE THREAD

**Issue by tadeoj** [googleapis/gapic-generator#2751]
Hello, I use googleapis proto definitions directly from the repository https://github.com/googleapis/googleapis. 
I tried to download the last stable commit to build with bazel and I have an error which I found referenced in the next issue of https://github.com/googleapis/google-cloud-java/issues/4946.

Would it be possible to update the dependency of gax to version 1.44.0?

I've seen googleapis and use this repository to define this version.

Thank you very much in advance.

**Comment by andreamlin** [comment]
This is blocked on https://github.com/googleapis/gapic-generator/issues/2735

**Comment by miraleung** [comment]
Looks like we're on 1.53 already, closing.
