### ISSUE TITLE
[Ruby] Docs classes not generated for IAM protos referenced via reroute_to_grpc_interface

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2766]
Normally the Ruby gapic generator generates "docs" source files for relevant protos. (Because generated proto classes do not otherwise have the expected annotated comments for doc generation.)

In most cases, this also extends to IAM-related protos used in calls such as `SetIAMPolicy` when they are declared directly in the service proto. For example, securitycenter declares `rpc SetIAMPolicy` directly in https://github.com/googleapis/googleapis/blob/master/google/cloud/securitycenter/v1/securitycenter_service.proto and imports the necessary protos from, e.g. `google/iam/v1/iam_policy.proto`. As a result, docs for these protos are generated. See, e.g., https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/iam_policy.rb

For two (that I can determine so far) services, however, the IAM calls in question are not declared directly in the service proto, but are referenced in the artman config via `reroute_to_grpc_interface`. KMS is an example. (The calls are not defined in https://github.com/googleapis/googleapis/blob/master/google/cloud/kms/v1/service.proto but are declared in https://github.com/googleapis/googleapis/blob/master/google/cloud/kms/v1/cloudkms_gapic.yaml). PubSub also appears to be an example. In these cases, artman fails to generate the docs files correctly for the IAM protos. See https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/iam_policy.rb

**Comment by noahdietz** [comment]
@dazuma @jbolinger is this going to be fixed in this generator? I imagine with the microgenerator coming out and the reroute feature not being supported, it won't be "fixed" in there.

I would like to close it if it's not going to be addressed or lower the priority.

**Comment by jbolinger** [comment]
I don't think this is relevant in gapic-generator-ruby since the configuration is totally different. We're not planning to fix it here so I'll close this and we can open new issues if there are problems with how the micro-generator creates docs.
