### ISSUE TITLE
feat: generated samples should include metadata for README generation

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator#2771]
When generating samples, samples should be populated with a meta-information header.

As an example, for JavaScript, a header might look something like this:

```js
// sample-metadata:
//   title: Create Job
//   description: Create a job that posts to /log_payload on an App Engine service.
//   usage: node createJob.js [project-id] [location-id] [app-engine-service-id]
```

These headers can be parsed by tools generating READMEs and other documentation.

**Comment by beccasaurus** [comment]
@bcoe Does it matter where that comment appears in the file? Is it associated with a particular region tag or with the file, as a whole?

If there's a file in the wild somewhere, link? :)

**Comment by bcoe** [comment]
@beccasaurus the simple little parser I wrote (read: regex) doesn't care where it's located. If it finds one somewhere in the sample, it uses it; If it can't it falls back to defaults. Here's an example of a sample that has been annotated with some meta information:

https://github.com/googleapis/nodejs-scheduler/blob/master/samples/createJob.js

**Comment by beccasaurus** [comment]
@bcoe Coming soon to a generator near you ~ #2782
