### ISSUE TITLE
all: disable gRPC service config lookup

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator#2778]
We need to disable gRPC service config resolution in GAPICs until the gRPC service config is fully implemented/adopted. All languages need to have their equivalent of [DisableServiceConfig](https://godoc.org/google.golang.org/grpc#WithDisableServiceConfig) set on GAPICs. Without this, if a service owner adopts and defines a gRPC service config, the clients will immediately consume it, resulting in duplicated retry implementation with the gax-based retries.

- [x] Go
- [x] Python
- [x] Java
- [x] PHP
- [x] Ruby
- [x] NodeJS
- [x] C#

**Comment by noahdietz** [comment]
focusing this work only on micro-generators

**Comment by noahdietz** [comment]
On second thought, we want clients to be safe as early as possible so we should disable it here as well asap

**Comment by noahdietz** [comment]
C# disabled gRPC ServiceConfig resolution [here](https://github.com/googleapis/gax-dotnet/commit/ac695425d9f25314ab60316d72f1d4eed57ef581)

**Comment by noahdietz** [comment]
Node.js: based on the [grpc-js comparison](https://github.com/grpc/grpc-node/blob/9c274034d05690d5709d4064f627b774b8305c32/PACKAGE-COMPARISON.md), the [C-core option](https://github.com/grpc/grpc/blob/927841120712051604650fbc7017d6ff2592af33/include/grpc/impl/codegen/grpc_types.h#L281) might not be supported in grpc-js.

**Comment by noahdietz** [comment]
Ruby: This will be handled in gax-ruby via https://github.com/googleapis/gax-ruby/pull/213

**Comment by noahdietz** [comment]
PHP: This will be handlded in gax-php via https://github.com/googleapis/gax-php/pull/240

**Comment by noahdietz** [comment]
Java: This will be handled in gax-java via https://github.com/googleapis/gax-java/pull/731

**Comment by hkdevandla** [comment]
@noahdietz , can you take a look and see if this is still relevant?

**Comment by noahdietz** [comment]
> can you take a look and see if this is still relevant?

This is done. Thanks for circling back to this.

**Comment by matetukacs** [comment]
@noahdietz Any news on grpc-js supporting "grpc.service_config_disable_resolution" grpc option? The TXT DNS queries that are made to attempt to resolve the config are massively slowing down the dns lookups of firestore and pubsub for us. I tried using the c++ grpc lib but node-firestore does not seem to be compatible with it.

Thanks in advance!

**Comment by noahdietz** [comment]
@matetukacs hi there. I'm not personally familiar with grpc-js, and in https://github.com/googleapis/gapic-generator/issues/2778#issuecomment-498744216 I was relaying what I had heard from others.

This repo is for a code generator that generates code dependent on grpc-js. I recommend opening an issue on the grpc-js repo inquiring about support for this option, including any information you can share about the performance degradation you're experiencing.

Apologies that I couldn't be more helpful.

**Comment by matetukacs** [comment]
Thanks @noahdietz! Creating an issue as you suggested.
