### ISSUE TITLE
[Python] Generator produces bad docstrings with 'raw-latex'

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator#2779]
From my understanding of #2191 and https://github.com/googleapis/artman/pull/535, the generator should not produce raw-latex. 

However, a [long proto comment](https://github.com/googleapis/googleapis/blob/32a10f69e2c9ce15bba13ab1ff928bacebb25160/google/cloud/automl/v1beta1/io.proto#L101-L158) in AutoML seems to result in some bad docstrings with 'raw-latex' in them.

See https://github.com/googleapis/google-cloud-python/pull/8029.

**Comment by busunkim96** [comment]
As an aside, the generated docstrings are pretty hard to read when they're generated from long proto comments with interesting formatting. 

Would it be reasonable to ask product teams to avoid adding too much documentation here?

These docs generated without error in Sphinx but it doesn't look like the formatting intended by the author.

Examples:
* [link](https://googleapis.github.io/google-cloud-python/latest/automl/gapic/v1beta1/types.html#google.cloud.automl_v1beta1.types.BatchPredictOutputConfig)
![image](https://user-images.githubusercontent.com/8822365/58050027-117c7c00-7b03-11e9-9bf0-aa25060fa4c0.png)
* [link](https://googleapis.github.io/google-cloud-python/latest/automl/gapic/v1beta1/types.html#google.cloud.automl_v1beta1.types.BatchPredictInputConfig)
![image](https://user-images.githubusercontent.com/8822365/58050140-64eeca00-7b03-11e9-8063-2de2053246fc.png)

**Comment by hzyi-google** [comment]
@lukesneeringer would you be able to take a look at this?

**Comment by software-dov** [comment]
Bump @lukesneeringer @busunkim96 
Is this being worked on?

**Comment by busunkim96** [comment]
@software-dov Not that I know of. I see this the most with AutoML, which has some pretty long proto comments to explain file formats.

**Comment by hzyi-google** [comment]
Hmmm, I can take this up if no one has cycles, but I need someone to translate Python terminology to something I can understand :(

**Comment by software-dov** [comment]
I can translate python terminology. Not sure I really understand the issue, though.

**Comment by software-dov** [comment]
Leaning towards won't fix due to microgenerator transition timeline.
