### ISSUE TITLE
SampleGen: remove six from Python samples

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2806]
### git revert #2272 – samplegen: convert binary type to str

We can remove six :)

> Not part of the current [Python Sample Authoring Guide](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
>
> Also, I asked. We can remove it.

@googleapis/samplegen

**Comment by hzyi-google** [comment]
Fixed in ^^^^^^^ #2811
