### ISSUE TITLE
SampleGen: print(u'all output strings {}'.format('as unicode strings'))

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2807]
There was a recent bug filed against out samples _(hand-written but same syntax as our generated ones)_.

If you're using Python 3 and you do this...

```py
response = client.get_company(name)
print('Company name: {}'.format(response.name)) # <==  if response.name has   🔥
                                                #  🔥  unicode characters     🔥
                                                #  🔥  this explodes terribly 🔥
```
```
🐞 UnicodeEncodeError: 'ascii' codec can't encode character
    u'\xea' in position 1: ordinal not in range(128)
```

We could fix this for Python 2 users in our generated code samples by simply rendering the following instead:

```py
response = client.get_company(name)
print(u'Company name: {}'.format(response.name)) # <==  if response.name has   🌈
      ^                                          #  🦄  unicode characters     🌈
      ^                                          #  🦄  this works fine :)     🌈
```

**Note:**
 - Python 2 support is a non-goal for generated samples now, afaik
 - e.g. I would like to [remove](https://github.com/googleapis/gapic-generator/issues/2806) the `six` code we added _(it adds distracting cruft to the samples)_

But, presuming this is always OK and safe to add to every printed string _(I'm not a Python expert)_, it seems like a trivially small change that will help protect some folks from experiencing the lovely world of string encoding errors :)

**Let's print everything** like this: `print(u'whatever {}'.format(22))` _(if using .format)_

=> @crwilcox incase it's bad to always `print(u'the things'.format('ピザ'))`

/cc @dizcology @googleapis/samplegen 

#inspiration https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2183

**Comment by vchudnov-g** [comment]
To clarify, based on a separate discussion: the `UnicodeEncodeError` above happens in Python 2, not Python3. Adding the `u` prefix makes the statements work for Python 2, which we'd prefer even if supporting Python 2 is not an explicit goal. At some point, maybe after Python 2 eol, we may remove the prefixes, which are not needed in Python 3.
