### ISSUE TITLE
SampleGen: replace // param = "default" with method(param = "default")

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2809]
Instead of doing this:

```js
method(param x, param y) {
  // x = "Cool value";
  // y = "Rad value";

  const client = amazing.things()
  // ...
}
```

Now, let's do this:

```js
method(param x = "Cool value", param y ="Rad value") {
  const client = amazing.things()
  // ...
}
```

Or, when > 80 chars:

```js
method(
  param x = "Cool value",
  param y ="Rad value"){
  const client = amazing.things()
  // ...
}
```

> ^ All pseudocode.
> Each language has preferred syntax for wrapping method params onto multiple lines. 

That's all :)

----

1. Cloud DPE has been doing this for awhile. We dig it.
2. Nearly every language supports default parameter values these days.

Languages without default method parameter values (iirc)
 - 🐹 Go
 - ☕️ Java

For each, we can come up with something.

Here's an idea I like for Java from @kurtisvg:

```java
public static void runSnippet(){
    String projectId = "my-project-id";
    String textToInspect = "My name is Gary and my email is gary@example.com";
   inspectString(projectId, textToInspect); 
}

// Inspects the provided text.
public static void inspectString(String projectId, String textToInspect) {
```

^--- essentially mocks default parameters, or more specifically – the way that we use default parameter values in samples & the benefits we and our users gain from them:
 1. discoverable
 2. easy to change in-line
 3. easy to change by calling method
 3. not commented out --> they are actually exercised (code coverage +1)

@googleapis/samplegen 

/cc @kurtisvg

**Comment by hzyi-google** [comment]
Moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
