### ISSUE TITLE
SampleGen: Node.js Library require is incorrect

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2815]
@googleapis/samplegen 

Generates
```
const speech = require('speech.v1p1beta1').v1p1beta1;
```

Not a Node.js person, but I believe it should be: 
```
const speech = require('@google-cloud/speech').v1p1beta1;
```

**Comment by hzyi-google** [comment]
cl/251701768 would update the service config of speech, and once the CL is merged it will resolve this issue.

I'll close it here, but please feel free to ask for reopen / yell at me if you still see the problem.
