### ISSUE TITLE
Adopt DNS-provided gRPC ServiceConfig

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator#2816]
Today, no formal process exists for service-owners to publish a gRPC ServiceConfig over DNS TXT Records per [gRPC design](https://github.com/grpc/grpc/blob/837a99e1d49a892e6f2c46ee09a1b6b8405571c6/doc/service_config.md). But as this does come online, we want GAPICs to transition in their own time, hence the work to disable resolving the ServiceConfig in all langauges #2778.

However, when it becomes the blessed method for service owners to configure clients, we will need to:

- [ ] ensure GAPICs have a default gRPC ServiceConfig
- [ ] reenable the resolution of the ServiceConfig in all languages

**Comment by noahdietz** [comment]
The adoption of the DNS-provided gRPC ServiceConfig will be a long-term process.

**Comment by hzyi-google** [comment]
Hey @noahdietz  this is done right?

**Comment by noahdietz** [comment]
This is actually just a tracking bug for adopting remote resolution of grpc service config. It is not implemented completely today in the grpc layer and so its unsupported in client libraries today. Furthermore, it requires API implementation at the serving layer to supply the config. 

I am tracking this work in an internal bug, so maybe we can close this one.

**Comment by hzyi-google** [comment]
Oh gotcha. Feel free to leave it open then.

**Comment by hkdevandla** [comment]
There is no concrete plan for this to be implemented in the near future. We will track this internally if it requires work / implementation. Closing.
