### ISSUE TITLE
[Java] cannot generate io.grafeas protos

### ISSUE THREAD

**Issue by chingor13** [googleapis/gapic-generator#2826]
We're trying to generate the io.grafeas v1 protos from: https://github.com/googleapis/googleapis/tree/master/grafeas

The Java Gapic generator does not allow clients that do not follow `com.google.cloud.*` as the package name. https://github.com/googleapis/gapic-generator/blob/d204c06777c38e351ef665c69f0f31fa0b61c3bf/src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceNamer.java#L455

**Comment by hzyi-google** [comment]
I can take this.
