### ISSUE TITLE
SampleGen Feature Request: string field support for `value_is_file`

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2829]
Response support:
 - [X] Save bytes to file
 - [X] Save test to file

Request support:
 - [X] Read file bytes into field 
 - [ ] **Read file text into field**

Let's fill in: **Read file text into field** support :)

@googleapis/samplegen

**Comment by hzyi-google** [comment]
Moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
