### ISSUE TITLE
Extraneous protobuf require breaking builds

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator#2835]
We have an issue over here where a bonus protofbuf require is breaking eslint:
https://github.com/googleapis/nodejs-talent/pull/69

**Comment by vchudnov-g** [comment]
@alexander-fenster Any updates on this? We're out of SLO on this issue.

**Comment by alexander-fenster** [comment]
I made the change to fix this in https://github.com/googleapis/gax-nodejs/pull/544 (`protobufjs` is now exported from `google-gax` so the generated libraries don't need to depend on it directly). Changes to the generator to stop depending on `protobufjs` are in #2888. Merging #2888 will close this one.

**Comment by JustinBeckwith** [comment]
I'm closing this one, because the original issue (generation being broken) has been fixed :)
