### ISSUE TITLE
[Java] pin protoc version to 3.7

### ISSUE THREAD

**Issue by chingor13** [googleapis/gapic-generator#2840]
For google-cloud-java, we need to try to keep our dependencies in a compatible state across the stack. We need to use the same protobuf version that grpc-protobuf uses. This is currently 3.7.x.

The newest artman versions use protoc 3.8.0 which generates code that is incompatible with protobuf 3.7.x (relies on a new class introduced in 3.8.0).

We need to be able to pin the protoc version for Java. As a workaround, we have locked our Artman version to 0.22.0, but we won't be able to get any generated bugfixes (like #2826)

**Comment by hzyi-google** [comment]
Fixed by: https://github.com/googleapis/artman/pull/641
