### ISSUE TITLE
Java: proto and grpc artifacts are not preserving license headers

### ISSUE THREAD

**Issue by chingor13** [googleapis/gapic-generator#2850]
The license headers should be preserved from the license headers present in the proto files.

**Comment by vam-google** [comment]
@chingor13 proto and grpc stubs are generated by `protoc` directly (grpc using grpc plugin from grpc-java repository). Gapic generator is not used. Most probably this request should go to https://github.com/protocolbuffers/protobuf

**Comment by hzyi-google** [comment]
Doesn't seem executable.
