### ISSUE TITLE
SampleGen: Initialize Python request object from top to bottom

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2874]
With this protobuf object:

```
message Person {
  string name = 1;
  Address address = 2;
}

message Address {
  string line1 = 1;
  string line2 = 2;
}
```

We should generate the following code:
```python
person = Person()
person.name = "Adam Smith"
person.address.line1 = "1 Some Street"
person.address.line2 = "Apt 890"
```

It's more idiomatic, and will also get initializing map fields in Python work (see: https://github.com/googleapis/gapic-generator/issues/2624)

**Comment by hzyi-google** [comment]
cc @googleapis/samplegen

**Comment by beccasaurus** [comment]
I'm down with this. But I want to make sure it's idiomatic.

@lukesneeringer Is this how you'll want to generate Python samples?

/cc @nnegrey @dizcology

**Comment by nnegrey** [comment]
In handwritten I think we would write it like this. 

```
address = Address(line1='1 Some Street, line2='Apt 890')
person = Person(name='Adam Smith', address=address)
```

Side thing, in your code above you don't create an `Address()` object, wouldn't you need to do that before you could assign the `.line#` values or am I mistaken?

**Comment by hzyi-google** [comment]
Nope. I think creating a protobuf objects initializes all fields with zero values. The code above works fine for me.

**Comment by vchudnov-g** [comment]
I agree with doing this. Can we do it in the format suggested by @nnegrey ? Note that this also affects the micro-generators, so looping in @software-dov

**Comment by software-dov** [comment]
To the best of my limited experience, I think @nnegrey is correct, that the bottom up initialization is the popular idiom. I cannot comment on the correctness of the top down approach.

**Comment by hzyi-google** [comment]
Talked with @software-dov offline. This is the strategy that Python micro-generator is taking:

<b>1. Prefer dictionaries over objects</b> (This is the same as the monolith)

With the support of [proto-plus-python](https://github.com/googleapis/proto-plus-python), dictionaries works perfect with protobuf messages.

<b>2. Prefer setting up an empty dictionary first, and then setting key/value pair</b>

Example: 
```py
address = {}
address.line1 = '1 Some Street'
address.line2 = 'Apt 890'

person = {}
person.name = 'Adam Smith'
person.address = address

client.addPerson(person)
```
Actually @software-dov , would this work? And what's your preference on this one over the above one?

```py
person = {
  'name': 'Adam Smith',
  'address' = address
}
```
^^^^ will be the output of the monolith after implementing inlining literals.

<b>3. Goes back to objects for map fields</b>

Dictionaries don't work when serving as a map value: #2624 . We need to go back to and initialize the object when the object serves as the value of a map entry.
Example:
```py
address = Address(line1='1 Some Street, line2='Apt 890')
address_book = {}
address_book['Tom'] = address
```

For work in the monolith, after we implement inlining literals, the output would be very much similar to that of the micro in 1) and 2) (with little differences, which we can continue to tweak). So therefore I consider 3) the most important thing that the monolith should fix that is specifically related to this issue.

**Comment by software-dov** [comment]
The example is not valid python; the current python would do

line1 = "1 Some Street"
line2 = "Apt 890"
address = {"line1": line1, "line2": line2}

name = "Adam Smith"
person = {"name": name, "address": address}

The convention I'm using for the microgenerator setting up the dictionary
and then assigning to keys directly, e.g.
address = {}
address["line1"] = "1 Some Street"
address["line2"] = "Apt 890"
person = {}
person["name"] = "Adam Smith"
person["address"] = address

I haven't started work on supporting deeply nested fields, though, and I
need to do a closer read of proto-plus-python.

**Comment by hzyi-google** [comment]
Gotcha! Updated the original post too

**Comment by hzyi-google** [comment]
Moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog
