### ISSUE TITLE
Possible missing packageInfo property in JavaSurfaceTransformer

### ISSUE THREAD

**Issue by msridhar** [googleapis/gapic-generator#2892]
This issue was discovered with a static analysis tool we are developing.  We are not fully confident it is a real bug, but it was suspicious enough that we thought it was worth reporting.

In `PackageInfoView`, the output path is a required property (no `@Nullable` annotation):

https://github.com/googleapis/gapic-generator/blob/768b9f60d7b02479b1bef35ba4bac8af5a1723c4/src/main/java/com/google/api/codegen/viewmodel/PackageInfoView.java#L29-L30

But in `JavaSurfaceTransformer` this property seems to only be set if some conditions are met:

https://github.com/googleapis/gapic-generator/blob/768b9f60d7b02479b1bef35ba4bac8af5a1723c4/src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceTransformer.java#L746-L753

If the `findFirst()` call returns an empty `Optional`, then `outputPath()` never gets called on the builder, and the subsequent call to `packageInfo.build()` will cause a crash.  It is possible that `findFirst()` will never return an empty `Optional` in which case the crash will never occur; we are not sure. 

We hope this report was helpful!

**Comment by noahdietz** [comment]
@hzyi-google when you get a chance, would you mind investigating this issue and reporting back on if it is possible/is it a concern? Thank you!

**Comment by hzyi-google** [comment]
Hi @msridhar, thank you so much for letting us know this issue, and your static analysis tool sounds truly amazing!

Yes your analysis is totally correct. This is indeed a code path that is not explicitly handled. In real world, however, this would (almost) never happen because the pipeline would have failed earlier. But I agree there are still potential risks of crashing without helpful debugging information.

I am working on a PR to have the stream throw an `IllegalStateException` when the `Optional` is empty.

**Comment by msridhar** [comment]
Thanks for the feedback @hzyi-google!  We are very happy to know that this report was useful.  We are working on making our tool more robust so it is usable by other developers; we will publicize the tool more once we hit that milestone.  Thanks again!

**Comment by msridhar** [comment]
@noahdietz @hzyi-google quick question.  Would it be of interest for us to put up a pull request adding our checker to the CI builds for gapic-generator, once it is more mature and ready?

**Comment by noahdietz** [comment]
@msridhar Thanks for offer. We will discuss it and get back to you in a few days.

**Comment by noahdietz** [comment]
Hi @msridhar so this sounds interesting. Why don't you come back in a few months when it is fully ready and we can discuss the possibility of integrating it. Thanks!

**Comment by msridhar** [comment]
Sounds good @noahdietz! I’ll open a proposal issue before creating a full PR so I can give more details and we can have a discussion.
