### ISSUE TITLE
SampleGen cleanup: SampleFileRegistry class

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2893]
The class has been used for slightly different purposes before and after the config migration and the code is contaminated. Consider doing the following after the migration is done:

- [ ] Remove deprecated methods and fields used by only deprecated methods
- [ ] Stop passing in a map through constructor, it's confusing
- [ ] If not breaking static languages, change `userProvidedIdCount` to a set (or sets): we only care about if an id has exactly one or more calling forms. We don't care about the actual number.
- [ ] Better internal field names

**Comment by hzyi-google** [comment]
DPE still needs gapic config for a while.

**Comment by software-dov** [comment]
Any update on this task?

**Comment by hzyi-google** [comment]
Still blocked.
