### ISSUE TITLE
Python Samples style change

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2928]
- [ ] Remove the calling_form sample ID combination in the `DO NOT EDIT` warning
- [x] Imports should have an empty line above them from the comment
- [x] Remove the blank line between region tag and first import
- [x] Comment blocks shouldn't have a newline at the end
- [x] Remove unused `import sys`

cc/ @nnegrey Please let me know if I missed a thing or two :stuck_out_tongue_closed_eyes:

**Comment by vchudnov-g** [comment]
We haven't decided to do the first item yet. I'm not opposed, but let's discuss metadata in general and where we want it to live.

**Comment by hzyi-google** [comment]
2 - 5 are fixed. We don't have any immediate work item for 1. Close this issue.
