### ISSUE TITLE
samplegen: satisfy generation semantics depending on user-specified files/directories

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#2931]
As per [this PR comment thread](https://github.com/googleapis/gapic-generator/pull/2924#discussion_r313184210) referencing [this design discussion](https://docs.google.com/a/google.com/document/d/1g6M5gl2gdrefQGyCW_MHAqZPRBiobCNJ4XChJJ4ufq4/edit?disco=AAAADYbhLxU), the semantics for sample generation should be that 

1. if no sample files/directories are specified, no samples files, manifest files, or sample directory are generated.

2. if sample files/directories are specified
  2.1 if files are explicitly specified, each such file must be a yaml file that contains at least one sample config doc (otherwise fail)
  2.2 if directories are specified, in each such directory we ignore non-yaml files and files that don't include any sample config docs
  2.2 across all the sample files and directories specified, we must have obtained at least one sample config doc

Thus, 
* specifying just `--samples=/tmp/non-sample.yaml` will fail
* if we were to support globbing (which is not in the µ-samplegen spec and we should not support it until it is): if `/tmp/foo/`  has both sample-configs and non-sample-config YAML files, specifying `--samples=/tmp/foo/*yaml` will fail, but `--samples=/tmp/foo/` will pass

From [this comment thread](https://github.com/googleapis/gapic-generator/pull/2924#discussion_r313184210) it appears the expansion from directories to files (part of 2.2) happens in artman. However, we need to check
(a) that we fail if 2.1, we fail generation. This will require moving the artman check to here, I think, because we need to distinguish between files specified explicitly by the user from files specified indirectly via an explicit directory. Alternatively, we could do the whole check in artman, but we'll need to move it here anyway when we rm artman and have to have gapic-generator conform to the protoc-plugin interface as a _bona fide_ microgenerator.
(b) that we satisfy 2.2 or fail otherwise
(c) that we satisfy 1 (I think this is true, but let's point to an explicit test that captures this).

All of (a), (b), and (c) must be covered by tests (some of them might already exist, which is great)

**Comment by hzyi-google** [comment]
I really _don't_ think this is a P1 and I am quite unsure about this is what we should force every micro generator and artman to implement it.

I don't think the requirement has been well communicated to customers (If so, and this is what customers wanted, I apologize and will get to it as soon as possible). I sincerely don't think we should continue to push out features that customers don't care at this critical time when releasing a working product to suit Cloud DPEs' need is the highest priority.

**Comment by vchudnov-g** [comment]
We discussed it in the spec and have it in there for a reason (it's a conclusion in a comment thread, and we need to update the main doc), so this is a requirement for having parity with microgenerators. And while it's not a blocker per se for the samplegen launch this quarter, it will lead to incompatibilities when everything moves over to the microgenerator invocation paradigm. So this is a non-conformance with the spec, hence a bug. I'll downgrade it to P2 for now because it doesn't block the samplegen release.

**Comment by hzyi-google** [comment]
It is not clear how this conclusion is reached:

> the microgenerators MUST accept any number of repeated parameters called samples.

This is the base of all other comment threads that talks about details of each parameter is handled but does not address why the flag `samples` have to take repeated fields, and whether this should be a required feature.

From how I have observed DPEs authoring samples there is a high chance they won't need to pass in a list of `--samples`, as long as the generator knows how to take directories and find sample configs in the directory.

Also the doc is written for microgenerators but gapic-generator working as a microgenerator is not finished work yet. Therefore this is a feature request IMO.

**Comment by software-dov** [comment]
I'd argue that it's not a feature request, it's establishing a standard. Bringing artman or a microgenerator into conformance with that standard would be a series of feature requests.

Not the focus of the thread, but just want to get my $0.02 in: I am against globbing because of complications it brings to build tools, and the intersection of recursive-directory-traversal and explicitly-named-files gives us most of the functionality.

**Comment by hzyi-google** [comment]
IMHO recursive-directory-traversal is enough.

I want to hear user's opinion on this. I put this topic on next week's samplegen team meeting.

**Comment by vchudnov-g** [comment]
I do see your POV, @hzyi-google . It's adding new functionality. OTOH, it's also fixing functionality that was added incompletely in the previous PR. That's how I was approaching it. :man_shrugging: 

In regards to passing sample configs in, I really do think only allowing dirs will be too restrictive and un-intuitive. We're building this for more than one customer.

WRT globbing: I'm of mixed mind but I'm more and more tending to agree with your position, @software-dov . I think globbing within the tool can be useful when the user wants many but not all files in a directory, eg `foo/v1*.yaml` But if the user has that many files that can't be individually enumerated, then they could just create a dir, symlink the files, and point the tool to the dir.....

**Comment by hzyi-google** [comment]
Users can still pass in an arbitrary path, which can be either a directory or a file.

My main concern is to not support multiple entries at the moment, i.e.,

I am OK with:
```bash
$ protoc --python-gapic-opt="samples='/path/to/a/sample/or/a/dir'"
```
or, in artman config,

```yaml
- gapic_yaml: ...  // some other fields not specific to samples
- proto_src_deps: ... // some other fields not specific to samples
- samples: /path/to/a/file/or/a/directory
```

But I don't quite like (at least not for now):
```
$ protoc --python-gapic-opt="samples="file1", samples="dir1", samples="file2"
```
or in artman config,
```yaml
- gapic_yaml: ...  // some other fields not specific to samples
- proto_src_deps: ... // some other fields not specific to samples
- samples: 
  - /path/to/a/file/or/a/directory1
  - /path/to/a/file/or/a/directory2
```

I do agree only allowing directories is counter-intuitive, but I think it's good enough to allow both a single file and a single directory. Like you said, people can create a directory and symlink the files if they really want to pass in sample configs from all over the world.

The multi-entry `--samples` flag does not foresee any immediate uses and will be a burden on the implementation (of at least 6 generators), thus I am fairly reluctant to make it a standard until someone has a strong use case. Also it wouldn't cause any breaking change to go from a single `--samples` flag to a repeated one should we need to, but maintaining a list always needs a bit more effort than maintaining a singular value.

**Comment by software-dov** [comment]
The important point seems to be that, whatever complicated use case the user has, their needs can be met with a combination of existing tools and functionality plus tweaking their directory structure somewhat.

**Comment by vchudnov-g** [comment]
We discussed offline and arrived at the following requirement:

µgenerators can accept multiple `--sample` flags, each specifying one yaml file that must contain one or more sample-config doc (but may contain other types of docs as well). Directories may NOT be specified via the `--sample` flag; it is the job of the caller to glob files as needed.

(If there's demand/reason to, we may relax this requirement in a future version of the spec)

@hzyi-google  Could you make sure the monolith and the go generators meet this requirement? (link to this issue). Thanks!

**Comment by vchudnov-g** [comment]
Update: we're putting samplegen eng work on hold for the moment, so we won't address this in 2020q1.

**Comment by hzyi-google** [comment]
Moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
