### ISSUE TITLE
SampleGen: initializing map fields

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2943]
- [x] - In Java: the key should be boxed type (`Integer`)
- [ ] - In C#: the format is broken
- [ ] - In Python: we need to use objects instead of dictionaries when used as a map value (to be verified)
- [x] - In Node.js: there seems to be an extra comma(?)

**Comment by hzyi-google** [comment]
cc @googleapis/samplegen

**Comment by hzyi-google** [comment]
https://github.com/googleapis/gapic-generator/pull/2946 Fix Java and Node.js

**Comment by vchudnov-g** [comment]
Lowering priority as we are pausing samplegen work for now.

**Comment by hzyi-google** [comment]
Moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
