### ISSUE TITLE
[SampleGen] 🚀 Enable Google Cloud client library repo support

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2954]
## 🚀 Enable SampleGen functionality for client library repos

» Tracking issue 🐞

Now that `gapic-generator` supports generating code samples in C#, Go, Java, Node.js, PHP, Python, and Ruby, each of the respective client library repositories should enable support for generated code samples so that `autosynth` distributes generated samples for publication.

----

#### 🖋 Sample Authoring [Journey] – _(same journey as making library config changes)_
 - `googleapis` is updated – _(with new sample and/or test configs)_
 - `autosynth` triggers `synthtool` – _(results in new/updated sample/test files being generated)_
 - `autosynth` creates a Pull Request – _(b/c generator output changed including sample/test files)_
 - **Pull Request runs sample tests** – _(requires running `$ sample-tester`)_
 - _That's all!_

----

📝 Two changes are required in client library repos to enable support for generated samples:
 1. Update the **CI / test scripts** to run sample tests (`*.test.yaml`) using `$`[`sample-tester`](https://github.com/googleapis/sample-tester)  
    
 2. On a per-API per-Library basis, each `synth.py` needs to be updated to generate samples  
     _(intentionally manual process to enable; enabling requires setting `include_samples=True`)_

This issue tracks `#1` – _**Enable CI / test scripts to run sample tests**_ (for each language / API)

----

#### In Review
 - [ ] PHP – 🤖 [Generated code samples for Natural Language and Speech-to-Text](https://github.com/googleapis/google-cloud-php/pull/2294) [🐘]
 - [x] Python – 🤖 [Generated code samples for Natural Language and Speech-to-Text](https://github.com/googleapis/google-cloud-python/pull/9153) [🐍]
 - [ ] Ruby – 🤖 [Generated code samples for Natural Language and Speech-to-Text](https://github.com/googleapis/google-cloud-ruby/pull/3992) [💎]

**Upcoming** _(issues not yet filed against library repos)_
 - 🐹 Go
 - 🚀 Node.js
 - ☕️ Java
 - #️⃣ C# / .NET

> (... I'll fill in the above with links as they become available ...)

----

> [go/library-samples](http://go/library-samples) (internal)

@googleapis/samplegen

**Comment by hzyi-google** [comment]
Moved to backlog. https://github.com/googleapis/gapic-generator/wiki/feature-backlog
