### ISSUE TITLE
Support well known env variable name to configure local emulators

### ISSUE THREAD

**Issue by ludoch** [googleapis/gapic-generator#2974]
I am starting developing a new Cloud Tasks emulator.
It is very similar to the PubSub emulator.

I see that in order to use it, one must change the application code to access the emulator:
See https://cloud.google.com/pubsub/docs/emulator#accessing_environment_variables

In Cloud Datastore emulator, one does not need to change the client code, as seen in:
https://cloud.google.com/datastore/docs/tools/datastore-emulator as DATASTORE_EMULATOR_HOST is known by the client layer and does the right thing when used...
It would be nice to provide such override capabilities via the gapic generator.
For Pub Sub, the known env variable would be PUBSUB_EMULATOR_HOST.
For Cloud Tasks, it would be CLOUDTASKS_EMULATOR_HOST
Etc...
Thanks!

**Comment by ludoch** [comment]
+lesv@

**Comment by ludoch** [comment]
Java pubSub section is what I was referring to:
https://cloud.google.com/pubsub/docs/emulator#pubsub-emulator-java

**Comment by vam-google** [comment]
@ludoch Can you please clarify you request please. 
From what I understood, there is a missing feature in the generated GAPIC clients, because to to switch between real service and an emulator one would need to change code in their application. Is it correct?

If yes, can you please clarify which code change that would be (an example would be ideal)?

Do I understand it right, that the suggestion is to use environment variables to pull the values, which differ between emulator and real service (like endpoint), so to switch between emulator and real service one would need to change the values in the invironment variables, but would not need to change the app code itself?

**Comment by ludoch** [comment]
The example is in the public documentation, but I can copy paste if you want:

Production code for PubSub shown in the doc:
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/TopicAdminClientSnippets.java#L52

```
    try (TopicAdminClient topicAdminClient = TopicAdminClient.create()) {

```
Emulator: https://cloud.google.com/pubsub/docs/emulator#pubsub-emulator-java
```

String hostport = System.getenv("PUBSUB_EMULATOR_HOST");
ManagedChannel channel = ManagedChannelBuilder.forTarget(hostport).usePlaintext().build();
try {
  TransportChannelProvider channelProvider =
      FixedTransportChannelProvider.create(GrpcTransportChannel.create(channel));
  CredentialsProvider credentialsProvider = NoCredentialsProvider.create();

  // Set the channel and credentials provider when creating a `TopicAdminClient`.
  // Similarly for SubscriptionAdminClient
  TopicAdminClient topicClient =
      TopicAdminClient.create(
          TopicAdminSettings.newBuilder()
              .setTransportChannelProvider(channelProvider)
              .setCredentialsProvider(credentialsProvider)
              .build());

  ProjectTopicName topicName = ProjectTopicName.of("my-project-id", "my-topic-id");
  // Set the channel and credentials provider when creating a `Publisher`.
  // Similarly for Subscriber
  Publisher publisher =
      Publisher.newBuilder(topicName)
          .setChannelProvider(channelProvider)
          .setCredentialsProvider(credentialsProvider)
          .build();
} finally {
  channel.shutdown();
}
```

As you can see, a lot of boiler plate code that a user would have to type to have a code base that supports the 2 use cases: prod and Emulator.

Cloud Datastore does not impose this, as its hand written client library is adapted to this use case.

App Engine Java or Python APIs do not impose this (since 2009, before GAE was GA): local dev app server works with the same code that would be deployed to prod.

It seems to me that the generated code could handle nicely an emulator Env variable, and based on its presence, could create the correct ManagedChannel TransportChannelProvider and CredentialsProvider objects that are adapted to the local case.

For sure, it is possible to have the workaround seen in the pubsub documentation, but this is breaking the ease of development I would expect from a good client library layer: easy of configuration, and not complicated and verbose builders.
The documentation would be also much simple: to use an emulator from a client library, just set up an env variable, do not change your code, do not recompile it.

**Comment by ludoch** [comment]
Datastore emulator documentation, simple and elegant: 

https://cloud.google.com/datastore/docs/tools/datastore-emulator

Ideally, the Cloud SDK should even be using these settings, i'e to create a pubsub or task via CLI would talk to the emulator if the env variable is set....But maybe the Cloud SDK is not using the Client APIs?

**Comment by ludoch** [comment]
Any interest in helping user experience?

**Comment by lesv** [comment]
I'm working on a PRD for this.  Will share when I'm done.

**Comment by miraleung** [comment]
Noted and will put on the internal FR backlog. Closing as obsolete given the new Java microgenerator.
