### ISSUE TITLE
gapic-generator does not support multiple patterns for resources

### ISSUE THREAD

**Issue by xiaozhenliu-gg5** [googleapis/gapic-generator#2975]
One use case [dataproc_v1]:

message WorkflowTemplate {
  option (google.api.resource) = {
    type: "dataproc.googleapis.com/WorkflowTemplate"
    pattern: "projects/{project}/regions/{region}/workflowTemplates/{workflow_template}"
    pattern: "projects/{project}/locations/{location}/workflowTemplates/{workflow_template}"
    history: ORIGINALLY_SINGLE_PATTERN
  };
...
}

We have two patterns for WorkflowTemplate resource [only region one is in gapic_yaml, but since location is comparatively new, we decide to add the pattern of locations], but generating client library using artman will give error of writing the same file.

**Comment by hzyi-google** [comment]
@xiaozhenliu-gg5 Can you dump the whole error here? Thanks!

**Comment by hzyi-google** [comment]
Some progress:

The actual code that causes this issue is the resource name plugin, but some design decisions must be made before we precede. I'll capture the problem in a doc.

**Comment by software-dov** [comment]
Ping @hzyi-google : any progress? Can you post a link to the doc?

**Comment by hzyi-google** [comment]
@software-dov thanks for pinging.

For anyone who is interested in this, see go/multi-pattern-resource-names

**Comment by hzyi-google** [comment]
Fixed by #3044 #3031 #3087
