### ISSUE TITLE
Code formatter can't remove unused imports in Java

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2983]
We have a very unique style in Java samples on showing users what imports are needed:

```java
package com.google.cloud.examples.speech.v1;

import com.google.api.gax.longrunning.OperationFuture;
import com.google.cloud.speech.v1.LongRunningRecognizeMetadata;
...
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;

public class SpeechTranscribeAsync {
  // [START speech_transcribe_async]
  /*
   * Please include the following imports to run this sample.
   *
   * import com.google.api.gax.longrunning.OperationFuture;
   * import com.google.cloud.speech.v1.LongRunningRecognizeMetadata;
   * import com.google.cloud.speech.v1.LongRunningRecognizeRequest;
   * import com.google.cloud.speech.v1.LongRunningRecognizeResponse;
   * ...
   */

  /**
   * Transcribe a long audio file using asynchronous speech recognition
   *
   * @param localFilePath Path to local audio file, e.g. /path/audio.wav
   */
  public static void sampleLongRunningRecognize(String localFilePath) {
    // ...
  }
  // [END speech_transcribe_async]

  public static void main(String[] args) throws Exception {
    // ...
  }
}
```

We have this comment showing which imports are needed instead of showing the real import statements on the devsite because:
1. We would have to show the entire file on the devsite if we show the imports, because otherwise there would be unmatching braces
2. We didn't want to show imports used only in the main method (apache clis), and inserting region tags between imports would break code formatter

However, this setting causes code formatter to be unable to remove unused imports from this comment showing required imports, because, well it is a comment. Although the generator is trying to be accurate about useful imports, but having code formatter to do another check is always safer.

Proposing:

We are having this `ApplicationChooser` idea in C#, which is basically a unified entry to the sample project. Each individual sample will not have any main method, and the `ApplicationChooser` class will decide which sample method to call based on user input.

This way we can get rid of the main method in each sample, and we can show the entire file on the devsite, and we don't need to put imports in a comment.

**Comment by hzyi-google** [comment]
cc/ @googleapis/samplegen

**Comment by vchudnov-g** [comment]
Let's see whether there are other possible solutions, but the `ApplicationChooser` sounds like a very reasonable one. We should collect use cases (like this one) for `ApplicationChooser`, as well as any cons of implementing it to help us decide.

**Comment by hzyi-google** [comment]
Moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog
