### ISSUE TITLE
Special Characters parsed out of generated samples

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2984]
@googleapis/samplegen 

For Dialogflow samples there needs to be special characters in some fields, but samplegen edits it out. 

Yaml: https://paste.googleplex.com/5494533670305792
Generated: https://paste.googleplex.com/6222908395356160
Handwritten Optimized: https://paste.googleplex.com/5432050028904448 (aka Noah's wishes)

Yaml: Line 52 
Generated: Line 70 missing ‘@’

Yaml: Line 85 
Generated: Line 100 missing ‘@’

**Comment by hzyi-google** [comment]
Hey Noah, this is probably already fixed by https://github.com/googleapis/gapic-generator/pull/2966. Can you try again?

**Comment by software-dov** [comment]
Any update on whether this is still an issue?

**Comment by nnegrey** [comment]
Howdy, I won't have time to touch samplegen till Dec.

**Comment by hzyi-google** [comment]
I verified it locally and it worked. Please feel free to ask for reopening it the issue persists.
