### ISSUE TITLE
Resource Name Renaming

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#2986]
A small-but-nonzero number of APIs (currently known: Cloud Functions) used a name that is different from their [AIP-123](https://aip.dev/123) unified resource name (e.g. `Function` vs. `CloudFunction`). We have no way of mapping the URT name to a different name to preserve backwards compatibility.

We need to learn the scope of the problem and then determine an appropriate solution.

**Comment by hzyi-google** [comment]
@miraleung FYI. We should probably just take a major bump for all of such cases.

**Comment by miraleung** [comment]
Noted, thanks. Closing since we likely won't change the monolith for such cases.
