### ISSUE TITLE
Strings should always be accepted for resource names

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#2987]
In Java and C#, we generate methods that take resource name classes _instead of_ generating methods that take strings. In order to adhere to [AIP-4231](https://aip.dev/client-libraries/4231), we need to generate methods that accept strings all the time.

Justification:

1. An existing API that adds resource descriptor annotations should be able to do so without incurring a breaking change.
2. Resource name patterns occasionally evolve, and users need to be able to send and receive resource names that a statically-compiled client library may not yet acknowledge.

**Comment by lukesneeringer** [comment]
Worth noting: As best as @jskeet or I can tell, this is already the case. @vam-google has said there are some exceptional cases where they are not generated, but I have not found them yet.

**Comment by hzyi-google** [comment]
@vam-google care to dump those exceptional cases here?

**Comment by hzyi-google** [comment]
Fixed by #3081 when all APIs move over to proto annotations.
