### ISSUE TITLE
inconsistent sample config `type` value across repos

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#2997]
*(cross-repo issue, filing here as the most central reference place in use)*

For the sample configs, gapic-generator [expects](https://github.com/googleapis/gapic-generator/blob/master/src/test/java/com/google/api/codegen/testsrc/common/samples/babble_about_book.sample.yaml#L2)
```
type: com.google.api.codegen.samplegen.v1p2.SampleConfigProto
```
but gapic-generator-python [expects](https://github.com/googleapis/gapic-generator-python/blob/00fdb08bdce5d7c1eacaf3ab0f65a8fdba0ec5ce/gapic/samplegen_utils/utils.py#L28) 
```
type: com.google.api.codegen.SampleConfigProto
```

We need to consistently use only one of these! The internal user guide has the latter specified, but DPEs have already been configuring samples with the former.

Options:
1. Use the latter, and have bw-compatibility code in gapic-generator to allow for `samplegen.v1p2.` in the `type`. Pro: more user-friendly: this gets us away from having the `schema_version` information duplicated in the `type`. Con: b/w compatibility code in gapic-generator until we do a sweep to update all the configs, and we can't use the python generator until we do.
2. Use the former, and change the user guide and generator-python to use `samplegen.v1p2.`. Pro: no bw compatibility code, no config sweep. Con: worse config
3. Switch to a more user-friendly type such as `type: config/sample`. This has already been requested and we were putting it off until after the upcoming launch, but given this bug we might want to do it before the launch. Pro: the most user-friendly by far. Con: backward compatibility code in *both* gapic-generator and gapic-generator-python, until we do a sweep of all the configs.

From the standpoint of user-friendliness and eventually-clean code, I suggest we do (3) ASAP, and in the meantime implement (2) as a stop-gap. @beccasaurus how hard/how automatable would it be to change this one field in all the submitted configs?

(If we weren't going to do (3) at some point, I would lean for (1), since that is the next-best UX, but bw-compatibility is an issue)

Once we decide on a plan, we should agree on the staging sequence so as to not break anything during the transition to the final state.

**Comment by vchudnov-g** [comment]
cc/ @googleapis/samplegen

**Comment by hzyi-google** [comment]
I don't have any preference between the two. Switching from the former to the latter will make the monolith slightly unhappy, but should be very easy to fix.

**Comment by software-dov** [comment]
I'm actually leaning towards (2); it's not a lot worse of a config, and it means the fewest changes all around.

**Comment by hzyi-google** [comment]
Okay let's do 2. I'll close it since 2) requires no work in this generator.
