### ISSUE TITLE
Python: `expected_request` in unit test does not have all required fields

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator#3004]
A generated unit test for videointelligence has an `expected_request` that does not have all the required fields.

Function `annotate_video` has required parameters `features` and `input_uri`. The unit test constructs a `AnnotateVideoRequest` with only the `features` and no `input_uri`.

The library was generated with Artman 0.38.0

See https://github.com/googleapis/google-cloud-python/pull/9440/files for more detail.

**Comment by software-dov** [comment]
Can you post the annotated proto or the gapic_yaml just we're looking at the same inputs?

**Comment by busunkim96** [comment]
* [annotated proto](https://github.com/googleapis/google-cloud-python/blob/6e72f9d9e444725f347bc6744a494a584a96b6f3/videointelligence/google/cloud/videointelligence_v1/proto/video_intelligence.proto)
* [gapic_yaml](https://github.com/googleapis/googleapis/blob/9d52ad21797ef188d73b36f633467c1319765df9/google/cloud/videointelligence/v1/videointelligence_gapic.yaml)

**Comment by software-dov** [comment]
This should be fixed by https://github.com/googleapis/gapic-generator/pull/3006 . Let me know if the problem persists.

**Comment by hzyi-google** [comment]
Closing it. Please yell at us if the bug is still there.
