### ISSUE TITLE
consider emitting java manifest with two environments, mvn and gradle

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#3007]
Given current offline discussions, if we decide to have the Java samples be readily executable by both maven and gradle, and we generate the necessary helper files for both, we should consider emitting each sample twice (probably once in each of two manifest files). One listing could have an `env` of `java-gradle` and a corresponding `invocation`, and the other would be similar but for `mvn`.

Pros: this makes it easy to test both build systems out of the box

Cons: each sample artifact appears more than once. It's very easy to replace the `invocation` in the file, since it appears in just one place.

Alternative: we could continue to list each sample once, but have a top-level `invocation:` for one of the two systems. and have a commented-out `# invocation:` for the other system, so that it becomes trivial to replace.

We should discuss this and decide before implementing any solution.

**Comment by hzyi-google** [comment]
Why is Gradle needed?

**Comment by vchudnov-g** [comment]
It sounded like both are in widespread use, no? If that's not the case, then just switching to the one we want to support (which sounds like `mvn`) is enough

**Comment by hzyi-google** [comment]
The client library repos are structured heavily around maven, thus generating `invocations` with gradle in the manifest file does not bring us any benefit.
