### ISSUE TITLE
Python: Deprecate resource name helper functions

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator#3012]
These functions will be going away in the microgenerator.

**Comment by hzyi-google** [comment]
Is this a proper way to deprecated a method in Python?

```python
@classmethod
def book_path(cls, book_shelf, book):
    """Return a fully-qualified book string."""
    import warnings
    warnings.warn("resource name helper functions are deprecated", DeprecationWarning,
              stacklevel=2)
    return google.api_core.path_template.expand(
        'bookShelves/{book_shelf}/books/{book}',
        book_shelf=book_shelf,
        book=book,
    )

```

**Comment by software-dov** [comment]
```python
from deprecated import deprecated


@deprecated
def print_value(value):
    """
    Print the value

    :param value: The value to print
    """
    pprint.pprint(value)
```
https://python-deprecated.readthedocs.io/en/latest/installation.html

If we don't want the extra dependency it's easy to write a custom decorator that does the same thing.

**Comment by busunkim96** [comment]
@hzyi-google that looks to be how stuff has been deprecated in the past:

**Comment by busunkim96** [comment]
@software-dov I would lean towards not adding the extra dependency. 

The deprecation should also be noted in the docstring (so it is visible in the [published documentation](https://googleapis.dev/python/cloudtasks/latest/gapic/v2/api.html#google.cloud.tasks_v2.CloudTasksClient.location_path)).


```python
@classmethod
def book_path(cls, book_shelf, book):
    """DEPRECATED. Return a fully-qualified book string."""
    warnings.warn("resource name helper functions are deprecated", DeprecationWarning,
              stacklevel=1)
    return google.api_core.path_template.expand(
        'bookShelves/{book_shelf}/books/{book}',
        book_shelf=book_shelf,
        book=book,
    )
```

**Comment by software-dov** [comment]
Something like
```python
from functools import wraps
import warnings
def deprecated(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        warnings.warn("Deprecated: " + func.__name__, DeprecationWarning, stacklevel=2)
        return func(*args, **kwargs)
    wrapper.__doc__ = ("DEPRECATED. " + (wrapper.__doc__ or "")).strip()
    return wrapper
```

should work. Just a pet peeve, but a decorator feels like a better fit than generating all the warnings in situ.

**Comment by busunkim96** [comment]
:+1: I have no strong feelings on the implementation, as long as there is (1) a warning and (2) something in the docstring.

Would adding the decorator to `google-api-core` work?

CC @crwilcox @tseaver @tswast who may have more opinions about this.

**Comment by software-dov** [comment]
It sounds fine to have the decorator in `google-api-core`, but other people should weigh in too.

**Comment by tseaver** [comment]
Seems like gratuitous breakage to drop the name / path helper functions in the microgenerator:  what is the rationale?

**Comment by software-dov** [comment]
Paraphrasing @lukesneeringer :they're very thin wrappers around string formatting, and python's string manipulation and formatting support is excellent. It's arguably nicer to just do the formatting by hand.

**Comment by tseaver** [comment]
The current helpers encapsulate knowledge of the required format strings:  making users type those strings in their code will be a bug magnet.  In any case, this is going to be a breaking change for anybody using the helpers:  is *that* the barricade we want to die on?

**Comment by tseaver** [comment]
Re: bug magnet -- consider *this* path template:

```
automl/google/cloud/automl_v1beta1/gapic/auto_ml_client.py-
    "projects/{project}/locations/{location}/datasets/{dataset}/annotationSpec/{annotation_spec}",
```
Note the oddness (plurals in some parts of the path, not in others, and the easy-to-overlook camelCase in one element.

**Comment by hzyi-google** [comment]
@tseaver not sure if I am understanding you correctly, but to the best of my knowledge all the paths should be plurals. The path template of this resource has `annotationSpecs` in it ([here](https://github.com/googleapis/google-cloud-python/blob/48359eb74b9d251c5ffd20d9dc3b1fd29310660d/automl/google/cloud/automl_v1beta1/gapic/auto_ml_client.py#L108)).

Honestly, it should be very rare that users need to manually construct these resource name strings. Most of the time they should be getting them from the server via a `CreateXXX` or `ListXXXs` call.

**Comment by software-dov** [comment]
^Just the person to weigh in!

There are other problems with providing the wrapper methods.
The monolithic generator used the names provided by the GAPIC yaml file, which the microgenerator doesn't read and which does not have a good maintenance prognosis due to the adoption of proto annotations.

@hzyi-google has a document where he highlights the problem and proposes per-language solutions. The only low cost, non-disruptive alternative is to make the name of the resource wrapper method the concatenation of the parameters, e.g. `project_location_dataset_annotationspec`. The surface-preserving alternative requires drastic changes to the proto annotations that will generate severe pushback from other invested parties.

**Comment by busunkim96** [comment]
The path will be specified in the docstring, so folks shouldn't have to do too much typing.

```python
project = 'test-project'
location = 'global'
dataset = 'test-dataset'
annotation_spec = 'test-spec'

path = f'projects/{project}/locations/{location}/datasets/{dataset}/annotationSpec/{annotation_spec}'
```

**Comment by hzyi-google** [comment]
@software-dov I'm totally happy to tweak the generator to generate whatever you and @busunkim96 loves most, but IMHO if it requires work in api-core it seems to be an overkill, unless this is something that will likely be widely used in the future too.

The warning style is already used in our [client libraries](https://github.com/googleapis/google-cloud-python/blob/6b5218b20d3fa69c96f9690eac07f5a92d13b255/container/google/cloud/container_v1/gapic/cluster_manager_client.py#L118-L121): so it's worth considering to keep the style consistent too.

**Comment by software-dov** [comment]
My vote is to deprecate.
