### ISSUE TITLE
Ensure we don't generate standalone samples if `sample_type` says not to

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#3015]
As of #2996 , there is now a `sample_type` field in the sample config. If not present, it defaults to standalone samples, so current configs will continue to work.

However, some upcoming configs may have it set to produce in-code samples only. In that case, we should make sure we don't produce standalone samples.

**Comment by vchudnov-g** [comment]
Update: We're putting samplegen eng work on hold for 2020q1, but this will need to be addressed when we resume.

**Comment by hzyi-google** [comment]
Moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog
