### ISSUE TITLE
go: auto pagination shouldn't happen unless the required fields are present

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator#3039]
Today, Go GAPICs are generated regardless of if the required fields (page_size & page_token) or not. The resulting output cannot be compiled. Instead, if there is no page_size || no page_token fields, auto pagination should not be generated.

**Comment by hzyi-google** [comment]
@noahdietz I created https://github.com/googleapis/gapic-generator/issues/3077 to track the work for all languages. I'll close it here if you don't mind!
