### ISSUE TITLE
Paging: error when paging response messages do not meet prerequisites

### ISSUE THREAD

**Issue by yihanzhen** [googleapis/gapic-generator#3077]
The prerequisites of the response message of an auto-paging method are listed in [AIP-4233](https://aip.dev/client-libraries/4233).

**Comment by hzyi-google** [comment]
Update: there are several APIs that do not conform to this rule. We should still add this check, but maybe whitelist those APIs.

**Comment by hkdevandla** [comment]
I think we have fixed this and there is no action to be taken on this. Please re-open if there is anything else to be done or fixed.
