### ISSUE TITLE
google.cloud hardcoded into node snip

### ISSUE THREAD

**Issue by jpoehnelt** [googleapis/gapic-generator#3129]
https://github.com/googleapis/gapic-generator/blob/e3501faea84f61be2f59bd49a7740a486a02fa6b/src/main/resources/com/google/api/codegen/nodejs/version_index.snip#L12

**Comment by hzyi-google** [comment]
@alexander-fenster How do we handle this for Ads (which I assume isn't under cloud namespace)?

**Comment by alexander-fenster** [comment]
We don't handle this. JavaScript generation is being deprecated in gapic-generator and is moving to https://github.com/googleapis/gapic-generator-typescript. We are not going to onboard any new users to JavaScript and/or fix any issues here.

**Comment by hzyi-google** [comment]
Closing the issue for there's no action item. Please feel free to continue the discussion.
