### ISSUE TITLE
Support TypeScript in rules_gapic

### ISSUE THREAD

**Issue by jpoehnelt** [googleapis/gapic-generator#3130]
TypeScript support was added in a different tool: https://github.com/googleapis/gapic-generator-typescript See #2054 for context.

**Comment by jpoehnelt** [comment]
Related https://github.com/googleapis/gapic-generator-typescript/issues/87

**Comment by hzyi-google** [comment]
Hello @jpoehnelt ! Thanks for reaching out. Unfortunately this generator won't support TypeScript. Please switch to use gapic-generator-typescript. Please contact @alexander-fenster and @xiaozhenliu-gg5

**Comment by alexander-fenster** [comment]
Yeah, we're deprecating this, and https://github.com/googleapis/gapic-generator-typescript is a fully compatible replacement. If you are missing any feature, let me know (here or in that repo). Bazel build is being taken care of, expect to see it soon!

**Comment by hzyi-google** [comment]
Closing the issue for there's no action item. Please feel free to continue the discussion here.
