### ISSUE TITLE
Java: generator is not respecting the default_host option annotation

### ISSUE THREAD

**Issue by chingor13** [googleapis/gapic-generator#3160]
This proto: https://github.com/googleapis/java-document-ai/blob/5244424f217ed31e5a86086196c8027257c0a6da/proto-google-cloud-document-ai-v1beta2/src/main/proto/google/cloud/documentai/v1beta2/document_understanding.proto#L36

is generating this settings configuration:

https://github.com/googleapis/java-document-ai/blob/master/google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta2/stub/DocumentUnderstandingServiceStubSettings.java#L136

**Comment by summer-ji-eng** [comment]
Working on migrating gapic v1 to v2. I will keep update here.

**Comment by hzyi-google** [comment]
Thanks Summer!
