### ISSUE TITLE
Java: breaking change when a string becomes a resource name

### ISSUE THREAD

**Issue by yihanzhen** [googleapis/gapic-generator#3167]
In Java, if a method has fields referencing resource names, we generate overloads that cover all combinations of resource name types as well as an extra one where all fields are treated as strings. This may cause breaking changes if a ordinary string becomes a resource name string:

For example, if we used to have:

```protobuf
rpc CreateFoo(CreateFooRequest) returns (CreateFooResponse) {
  option (google.api.method_signature) = "foo,bar";
}

message CreateFooRequest {
  string foo = 1 [
    (google.api.resource_reference).type = "foo.googleapis.com/Foo"];

  string bar = 2;
}
```

we generate:
```java
CreateFooResponse createFoo(CreateFooRequest request);
CreateFooResponse createFoo(FooName foo, String bar);
CreateFooResponse createFoo(String foo, String bar);
```

Now we want to make `bar` a resource name, or we realized we forgot to annotate `bar`, we change the request message to:

```protobuf
message CreateFooRequest {
  string foo = 1 [
    (google.api.resource_reference).type = "foo.googleapis.com/Foo"];

  string bar = 2  [
    (google.api.resource_reference).type = "foo.googleapis.com/Bar"];
}
```

And we will generate:
```java
CreateFooResponse createFoo(CreateFooRequest request);
CreateFooResponse createFoo(FooName foo, BarName bar);
CreateFooResponse createFoo(String foo, String bar);
```

This is problematic: the signature of the second method is changed and thus causing a breaking change.

Proposing: we generate overloads that covers combinations where each field can be a resource name type or a string.

So for the second case above, we generate:

```
CreateFooResponse createFoo(CreateFooRequest request);
CreateFooResponse createFoo(FooName foo, BarName bar);
CreateFooResponse createFoo(FooName foo, String bar);
CreateFooResponse createFoo(String foo, BarName bar);
CreateFooResponse createFoo(String foo, String bar);
```

**Comment by miraleung** [comment]
Discussion resolved in #3177.
