### ISSUE TITLE
Multiple *Name.java classes for a single resource

### ISSUE THREAD

**Issue by aohren** [googleapis/gapic-generator#3173]
If we have a proto package hierarchy as follows (i.e., the [googleads](https://github.com/googleapis/googleapis/tree/master/google/ads/googleads) project)
```
├── common
├── enums
├── errors
├── resources
│   └── campaign.proto
└── services
    └── campaign_service.proto
```
where [campaign_service.proto](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v3/services/campaign_service.proto) has rpc methods that depend on [campaign.proto](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v3/resources/campaign.proto) like [`GetCampaign`](https://github.com/googleapis/googleapis/blob/b5aa7d668d9513cf0d305c8b23262ee0ea9b850c/google/ads/googleads/v3/services/campaign_service.proto#L43):

```
  rpc GetCampaign(GetCampaignRequest) returns (google.ads.googleads.v3.resources.Campaign) {
    option (google.api.http) = {
      get: "/v3/{resource_name=customers/*/campaigns/*}"
    };
    option (google.api.method_signature) = "resource_name";
  }
```

Then, `gapic-generator` generates many `CampaignName` classes, one in each package:
```
src/main/java/com/google/ads/googleads/v3/resources/CampaignName.java
src/main/java/com/google/ads/googleads/v3/enums/CampaignName.java
src/main/java/com/google/ads/googleads/v3/common/CampaignName.java
src/main/java/com/google/ads/googleads/v3/errors/CampaignName.java
src/main/java/com/google/ads/googleads/v3/services/CampaignName.java
```

We'd like to delete all except either the one in `services` or `resources`, so that the client code is less confusing to users. 

However, the generated test classes depend on _both_ `services/CampaignName.java` _and_ `resources/CampaignName.java`, so we have to keep both copies so that test compile. For example, `src/test/java/com/google/ads/googleads/v3/services/CampaignServiceClientTest.java`:
```java
  @Test
  @SuppressWarnings("all")
  public void getCampaignTest() {
    com.google.ads.googleads.v3.resources.CampaignName resourceName2 =
        com.google.ads.googleads.v3.resources.CampaignName.of("[CUSTOMER]", "[CAMPAIGN]");
    Campaign expectedResponse =
        Campaign.newBuilder().setResourceName(resourceName2.toString()).build();
    mockCampaignService.addResponse(expectedResponse);

    CampaignName resourceName = CampaignName.of("[CUSTOMER]", "[CAMPAIGN]");

    Campaign actualResponse = client.getCampaign(resourceName);
    Assert.assertEquals(expectedResponse, actualResponse);

    List<AbstractMessage> actualRequests = mockCampaignService.getRequests();
    Assert.assertEquals(1, actualRequests.size());
    GetCampaignRequest actualRequest = (GetCampaignRequest) actualRequests.get(0);

    Assert.assertEquals(resourceName, CampaignName.parse(actualRequest.getResourceName()));
    Assert.assertTrue(
        channelProvider.isHeaderSent(
            ApiClientHeaderProvider.getDefaultApiClientHeaderKey(),
            GaxGrpcProperties.getDefaultApiClientHeaderPattern()));
  }
```
Both the method argument and the return type are annotated as type `googleads.googleapis.com/Campaign`, so I'd think there's enough semantic info to resolve them to a single entity. Is there a way to get around requiring both copies of `CampaignName` object in the generated code?

**Comment by miraleung** [comment]
Fixed and verified to be working in the microgenerator.
