### ISSUE TITLE
Incorrect code generated

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/gapic-generator#3181]
Hi,
We have some issues with the code generated in `MockBigQueryWriteImpl.java` file which resulted in synth tool proposing this following PR: https://github.com/googleapis/java-bigquerystorage/pull/191/files

The element is never used before being popped so we would like to get it fixed to what we have on https://github.com/googleapis/java-bigquerystorage/blob/d810b819e386a69df1781d3ed4b47f75f63a320e/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/MockBigQueryWriteImpl.java#L90 

```
requests.add(value);
final Object response = responses.remove();
```

Please correct the generator code or point us to where we can correct it ourselves. Thanks!

**Comment by hkdevandla** [comment]
@miraleung , can you please take a look?

**Comment by miraleung** [comment]
We haven't updated bigquery/storage/v1alpha2 gapic configs, nor have related changes gone into the generator (that I know of).

@vam-google for his thoughts as well.

**Comment by stephaniewang526** [comment]
That might be the case, the code generated has not been correct all along. We would like to have it corrected so that our test cases don't fail. It's a two-line change.

**Comment by miraleung** [comment]
Could you please clarify if the request is for a change in the generator, or just the specified two lines? The former would be likely be complex, the latter trivial.

**Comment by stephaniewang526** [comment]
If there's an easier way to have the generated file include the two lines that we specified instead of the one line generated by gapic then that works for us (just want to make sure this is corrected every time when the file is generated).

**Comment by vam-google** [comment]
@stephaniewang526 @miraleung Those two lines where are currently missing in the autogenerated PR were added 6 days ago manually in the generated class by [this PR](https://github.com/googleapis/java-bigquerystorage/pull/165/files#diff-728743ad17cb157fe55ecc5d3128af6c). 

Please never edit manually generated classes, as the chagnes will be overwritten  on next synth PR. You can tell if the file was generated by gapic or no by the `Generated("by GAPIC")` class-level annotation at the top of the class.

As for fixing this. If you are confident that this chagne (these two lines) are the correct solution for the generic case (not bitquery-storage only), then it can be fixed here: [mock_service_impl.snip#L84](https://github.com/googleapis/gapic-generator/blob/master/src/main/resources/com/google/api/codegen/java/mock_service_impl.snip#L84) by simply adding those two lines, and possibly removing Line 81 (to match what you have now for bigquery-storage). After that run tests, update baseline files and post a PR.
