### ISSUE TITLE
`identitytoolkit/v3/relyingparty` proto definitions

### ISSUE THREAD

**Issue by long1eu** [googleapis/gapic-generator#3270]
Usually I can find all google apis proto definitions here (https://github.com/googleapis/googleapis). But there is no definitions for `identitytoolkit/v3/relyingparty`.

Sorry if this is missplaced, `googleapis` repo doesn't allow issues.

**Comment by miraleung** [comment]
It doesn't look like that API is on the googleapis repo, please try the [identitytoolkit documentation](https://developers.google.com/identity/toolkit/web/reference) instead.

**Comment by long1eu** [comment]
Well I need the proto files to generate code. Should I recreate them based on documentation? Also the documentation seems incomplete.

For example:

The iOS SDK uses an endpoint that is not documented, that is `signInWithGameCenter`.

https://github.com/firebase/firebase-ios-sdk/blob/42655733d51214ee83362afab0b0f545ce3b2102/FirebaseAuth/Sources/Backend/RPC/FIRSignInWithGameCenterRequest.m

**Comment by long1eu** [comment]
Also @chingor13 @miraleung, can you make sure to tell me if this is the right repo. And if not, witch one is it?

**Comment by chingor13** [comment]
Sorry, did not see this issue. We do not publish a gRPC endpoint for this API. You can use the HTTP/JSON API https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-identitytoolkit/v3/1.31.0

**Comment by long1eu** [comment]
Almost all Google apis are gRPC.
