### ISSUE TITLE
Generated java Gapic client tests don't include @RunWith annotation

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/gapic-generator#3291]
Example:
https://github.com/googleapis/java-bigtable/blob/8f53b43880be905ea0221d255fe6f81ffe7161e9/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BaseBigtableTableAdminClientTest.java#L92-L93

**Comment by hkdevandla** [comment]
@miraleung , is this still valid issue to be tracked in this repo?

**Comment by hkdevandla** [comment]
This repo will be deprecated soon. If this is still an issue in the gapic-generator, can you please open up an issue in https://github.com/googleapis/gapic-generator-java?
