### ISSUE TITLE
More concise class names for ApiWrapperName?

### ISSUE THREAD

**Issue by jmuk** [googleapis/gapic-generator#385]
It seems Golang already did the similar thing -- LanguageService => Language or LoggingServiceV2 => Logging.  Can we apply the same heuristics for the class names for other languages?  So now it's LanguageApi, not LanguageServiceApi, or it's LoggingApi, not LoggingServiceV2Api.
- [X] Go
- [x] Java
- [x] ~.NET~
- [ ] NodeJS
- [x] ~PHP~
- [ ] Python
- [x] Ruby

**Comment by saicheems** [comment]
Specifically - the heuristic in Go does the following:

1. Matches and removes `(V[0-9]+$)`
2. Matches and removes `(Service$)`

**Comment by jskeet** [comment]
I remember there being discussions around this, but I *thought* the consensus was that we should just stick with what was given.

@omaray and @anthmgoogle to comment - we definitely need to determine this before GA!

**Comment by eoogbe** [comment]
@omaray @anthmgoogle @jskeet What was the conclusion of the discussions?

**Comment by jskeet** [comment]
Well for C#, we're still just generating what we already have - we don't remove anything.

**Comment by eoogbe** [comment]
Does it still make sense to try to add this change?

**Comment by jskeet** [comment]
I don't think it does for C#. Other languages may wish to make different decisions.

**Comment by eoogbe** [comment]
@garrettjonesgoogle @lukesneeringer @michaelbausor @geigerj Is this relevant to your languages?

**Comment by geigerj** [comment]
@landrito has already done this for Ruby.

**Comment by michaelbausor** [comment]
I think this makes sense to do in PHP, but it is not yet done, so we should leave PHP on the list.

**Comment by garrettjonesgoogle** [comment]
This was done using config for Java.

**Comment by jskeet** [comment]
Mmm... if there's config for Java, we *may* want to follow it after all for C#. @garrettjonesgoogle do you have any specific examples I could look at?

cc @chrisdunelm

**Comment by garrettjonesgoogle** [comment]
Here is the config for Java for Logging:

https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_gapic.yaml#L5

```
language_settings:
  java:
    package_name: com.google.cloud.logging.v2
    interface_names:
      google.logging.v2.ConfigServiceV2: Config
      google.logging.v2.LoggingServiceV2: Logging
      google.logging.v2.MetricsServiceV2: Metrics
```

We take the interface name `Logging` and add `Client` to get `LoggingClient` and we add `Settings` to get `LoggingSettings`.

**Comment by jskeet** [comment]
@garrettjonesgoogle: Thanks. Although the ship has sailed for logging in C# (we've gone GA) we may want to do this for other APIs.

@chrisdunelm is this something that would make sense to do in your current toolkit work?

**Comment by michaelbausor** [comment]
PHP won't do this

**Comment by landrito** [comment]
I am fairly sure Python won't do this. @lukesneeringer?

**Comment by chrisdunelm** [comment]
C# already supports this, using the same language-specific config as Java.
