### ISSUE TITLE
Support java test generation for non-flattening methods

### ISSUE THREAD

**Issue by shinfan** [googleapis/gapic-generator#393]
Some clients do not have flattened methods, as result the non-flattened methods are simply not tested. This also leads to extreme cases, when the whole generated test is empty, because there are no flattened methods in the client at all. This already affects multiple clients:
- [Dlp](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/DlpServiceClientTest.java)
- [Asset](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-asset/src/test/java/com/google/cloud/asset/v1beta1/AssetServiceClientTest.java)

In Bazel it makes things even worse, because `java_test` rules in bazel fail in case if we try to run an empty test (which is, I believe, the correct behavior, because an empty test is not a valid test).

**Comment by eoogbe** [comment]
@shinfan Are you still working on this?

**Comment by shinfan** [comment]
We have already supported request object for streaming methods. Right now we don't have plan to test non-flattening unary methods yet.

**Comment by vam-google** [comment]
This issue must be fixed. We currently simply do not generate any tests for methods, which do not have flattening configured. Some clients do not have any flattened methods, and as result the generated tests for them are empty. Trying to run an empty test also breaks Bazel's `java_test` rule.

**Comment by andreamlin** [comment]
Ack

**Comment by jbolinger** [comment]
@andreamlin Any updates on this?

**Comment by landrito** [comment]
@andreamlin any updates?

**Comment by jbolinger** [comment]
@andreamlin anything new here?

**Comment by andreamlin** [comment]
this has been deprioritized and will become a problem when it becomes a problem

**Comment by hzyi-google** [comment]
Fixed by #3087
