### ISSUE TITLE
[Python] Fix documentation linking to protos

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator#394]
### What:

Fix text in first page of [documentation](http://pythonhosted.org/gax-google-pubsub-v1/) to say something like "The .proto files used to create this client library are available on [github]".
### Why:

The current text "defined in the [googleapis] git repository" is unclear.

**Comment by eoogbe** [comment]
@lukesneeringer Is this still relevant?

**Comment by landrito** [comment]
If this is still an issue I'd assert this will be a 'will not fix' in lieu of solving this in gapic-generator-python. @lukesneeringer if you disagree, please reopen.
