### ISSUE TITLE
[Python] Sphinx doesn't recognize closing backticks when not adjacent to word boundary

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#401]
### Observed behavior:

Build `vision` docs:

```
python execute_pipeline.py \
    --config "../googleapis/gapic/api/artman_vision.yaml,\
    ../googleapis/gapic/lang/doc.yaml" \
    --language python \
    GapicClientPipeline 
```

```
cd output
```

```
tox -e docs
```

fails with

```
/usr/local/google/home/jgeiger/repos/gapi-dev/artman/output/gcloud-python-cloud-vision/.tox/docs/local/lib/python2.7/site-packages/google/cloud/vision/v1/image_annotator_pb2.py:docstring of google.cloud.vision.v1.image_annotator_pb2.EntityAnnotation:38: WARNING: Inline literal start-string without end-string.
```
### Cause

Appears to be that generated docstring for EntityAnnotator contains the text 

```
``boundingPoly``s
```

Sphinx does not recognize the second pair of backticks because it is not at a word boundary
### Solution

TBD

/cc @bjwatson

**Comment by geigerj** [comment]
@lukesneeringer

**Comment by geigerj** [comment]
This will likely involve a fix at https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/py/PythonSphinxCommentFixer.java

**Comment by eoogbe** [comment]
@lukesneeringer @geigerj Is this still relevant?

**Comment by geigerj** [comment]
I'd assume so, but @lukesneeringer to confirm.

**Comment by andreamlin** [comment]
This is possible related to https://github.com/googleapis/gapic-generator/issues/401

**Comment by vchudnov-g** [comment]
@lukesneeringer Any updates (to meet our SLO)?

**Comment by vchudnov-g** [comment]
@lukesneeringer @hzyi-google Any updates on this? We're out of SLO.

**Comment by software-dov** [comment]
Leaning towards won't fix due to microgenerator transition timeline
