### ISSUE TITLE
NodeJS Enum doc links broken

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#515]
### Expected behavior

NodeJS enum links in the generated documentation are be prefixed by their namespace, typically an enclosing method. For example, if the enum `Enm` is defined in the top-level message `Msg`, the enum should be referred to as `Msg.Enm`.
### Observed behavior

The link uses just the element simple name, e.g., `Enm`.

**Comment by vchudnov-g** [comment]
@alexander-fenster Could you verify whether this is still an issue and close if not?

**Comment by noahdietz** [comment]
@alexander-fenster could you triage this and determine if it is still an issue? Thanks

**Comment by alexander-fenster** [comment]
I tried clicking some enum links in the docs and everything worked. Closing for now.
