### ISSUE TITLE
Add missing docs on codegen classes

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/gapic-generator#62]
e.g. classes like JavaContext and JavaContextCommon don't have javadoc on some public methods.

**Comment by garrettjonesgoogle** [comment]
Also improve unhelpful docs (e.g. constructor docs that just say "constructs an instance")

**Comment by bjwatson** [comment]
Protected methods and fields also, per https://google.github.io/styleguide/javaguide.html#s7-javadoc.

**Comment by geigerj** [comment]
The Python GAX repository enforces style checks like this via travis, which runs several linters. Is something similar possible for Java?

**Comment by bjwatson** [comment]
Probably. Adding that checking sounds in scope for this issue.

**Comment by andreamlin** [comment]
This seems like it would be a lot of toil.

**Comment by hkdevandla** [comment]
Obsolete.
