### ISSUE TITLE
Define init value for entries in LoggingServiceV2Api.write_log_entries()

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator#636]
### What:

Define some init values for the `entries` argument in [`LoggingServiceV2Api.write_log_entries()`](https://github.com/googleapis/api-client-staging/blob/master/generated/python/gapic-google-logging-v2/google/cloud/gapic/logging/v2/logging_service_v2_api.py#L225).
### Why:

The structure of the expected values is not obvious, especially in our dynamic languages. See the discussion in https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2552.

Doing this will improve our method samples.

**Comment by swcloud** [comment]
@bjwatson @danoscarmike  Will this affect the surface generation in any way?

**Comment by bjwatson** [comment]
Nope, init values affect samples and tests, not the surface.

**Comment by hzyi-google** [comment]
Moved to backlog. https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
