### ISSUE TITLE
Variable naming in test generation

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#888]
There are some inconsistencies in variable naming in the generated unit tests across languages:
- Variables with a numerical suffix often occur before variables without one (e.g. name2 here: https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/java_test_library.baseline#L174)
- Variables have a numerical suffix when it is not required (e.g. https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/go_mock_library.baseline#L951)

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority?

**Comment by michaelbausor** [comment]
No longer relevant, closing out.
