### ISSUE TITLE
Manual interface documentation cannot be un-escaped

### ISSUE THREAD

**Issue by pongad** [googleapis/gapic-generator#937]
See: https://github.com/googleapis/googleapis/pull/241#discussion_r96564470

**Comment by eoogbe** [comment]
@pongad Can you add a priority to this?

**Comment by noahdietz** [comment]
@pongad can you give some more detail on this issue? Not sure there is enough here to start a fix. Thanks.

**Comment by pongad** [comment]
I'm not sure how relevant this is anymore. At one point, we had `lang_doc` GAPIC config that lets us add free form string to our client. At least in Java, this string is also always escaped so it's impossible to make Javadoc link like `@See` etc.

Does this make sense?

**Comment by noahdietz** [comment]
I'm just poking issue for SLO triage. If you think this is obsolete, feel free to close the issue. Else, lets assign to someone else?

**Comment by pongad** [comment]
Ah sorry. I don't think this issue should be closed yet: `lang_doc` is [still being use](https://github.com/googleapis/googleapis/search?q=lang_doc&unscoped_q=lang_doc) and we still can't link is Javadoc. Who's the Java lead now?

**Comment by noahdietz** [comment]
@andreamlin ?

**Comment by andreamlin** [comment]
@pongad feel free to reassign this to me.

As a P2+, this is a low-level FR.

**Comment by hkdevandla** [comment]
Obsolete.
