### ISSUE TITLE
sample_code_init_fields initial value as a file

### ISSUE THREAD

**Issue by jmuk** [googleapis/gapic-generator#945]
Related to https://github.com/googleapis/toolkit/issues/941 and https://github.com/googleapis/googleapis/issues/243, the speech audio data will normally come from a file, and I believe that data coming from a file will be seen in other APIs. It's nicer to extend the sample_code_init_fields syntax to denote that. I'm not sure about its actual specs though.

**Comment by jmuk** [comment]
Some things like `audio.content=file%audio_file.flac` ?

**Comment by garrettjonesgoogle** [comment]
the syntax `template%parameter` is already reserved for parameters to path templates. I think the first thing to start with is this: What do you want the generated code to look like?

**Comment by jmuk** [comment]
Good to know that.

The samplegen should generate the code to read the file from the sample name of the file; with Node.JS, it's gonna be like
```javascript
var fs = require('fs');
...
var content = fs.readFileSync('audio_file.flac');
var audio = {
  content: content
};
...
```

**Comment by garrettjonesgoogle** [comment]
So then the Java version might be something like this:

```
  byte[] fileBytes = Files.readAllBytes(Paths.get("audio_file.flac"));
  ByteString content = ByteString.copyFrom(fileBytes);
  RecognitionAudio audio = RecognitionAudio.newBuilder().setContent(content).build();
```

(There might be a more condensed way to do this.)

So in the config, we need some language-agnostic way to indicate that the content of a file needs to be read with a given name and populated into a given field. Here is one option:

```
- audio.content=$FILE_BYTES("audio_file.flac")
```

Here, the `$FILE_BYTES` indicates a "macro" of sorts for the sample code generator, and tells it to generate code that loads the bytes from a file with the given name. (We have other special dollar-sign features, like `$PROJECT_ID` and `$RANDOM`).

**Comment by jmuk** [comment]
sounds good to me.

**Comment by eoogbe** [comment]
@garrettjonesgoogle Is this still relevant?

**Comment by garrettjonesgoogle** [comment]
It's still something we could do that would be helpful.

**Comment by vchudnov-g** [comment]
We are allowing file input in the standalone samples. When we migrate the same samplegen infrastructure to also generate the in-code samples, this will come along for the ride.

**Comment by hzyi-google** [comment]
Moved to backlog. https://github.com/googleapis/gapic-generator/wiki/feature-backlog
