### ISSUE TITLE
Support ClientStreaming test generation

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#946]
Unit test generation for ClientStreaming methods is not yet supported in these languages (which otherwise have unit test generation for gRPC streaming methods):
- [ ] Java
- [ ] NodeJS

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority?

**Comment by hkdevandla** [comment]
@alexander-fenster, can you take a pass at this and see if it is still relevant?

**Comment by alexander-fenster** [comment]
We generate tests for client streaming in the micro-generator.
