### ISSUE TITLE
Switch `SurfaceNamer` to an abstract class

### ISSUE THREAD

**Issue by shinfan** [googleapis/gapic-generator#947]
I don't think a general surface namer should be a concrete class since surface naming itself is language dependent. 

One of the benefits of making SurfaceNamer abstract is that we can get rid of the unimplemented methods such as:

```Java
  public String getTestPackageName() {
    return getNotImplementedString("SurfaceNamer.getTestPackageName");
  }
```

@garrettjonesgoogle @pongad @michaelbausor  thoughts?

**Comment by garrettjonesgoogle** [comment]
I made it concrete to make development of a new language incremental - someone isn't forced by the compiler to provide everything at the first go.

**Comment by shinfan** [comment]
One of the drawbacks of current surface namer is that every method goes to the top `SurfaceNamer` class even the method is only used by one language.  Now the class has over 1000 lines which makes it unmanageable. When anyone develops a new language, it would be hard for him to discover which method has already been implement and which has not.

**Comment by garrettjonesgoogle** [comment]
But if you have an abstract class and you add a method, then you are forced to either 1) implement it in all currently supported languages, or 2) give a default implementation, which is the status quo.

**Comment by shinfan** [comment]
I am thinking about making the `SurfaceNamer` only contain the common methods which are used by all languages (which should reduce the number of methods in `SurfaceNamer`). And allow the `LanguageSurfaceNamer` add the extra methods on demand.

**Comment by garrettjonesgoogle** [comment]
But that defeats the ability to pass `SurfaceNamer` object around to language-agnostic transformers. Even if you confined `${language}SurfaceNamer` usage to the `${language}GapicSurfaceTransformer` classes, that would make it more difficult to pull code out of those transformer classes later to share among multiple transformers (Luke is doing this for Php & Python).

**Comment by shinfan** [comment]
How about this:
`SurfaceNamer`: A concrete class contains common methods by default. It may also contain some methods that are not used by all languages to make things easier for shared transformers. (e.g.  Luke's work for Php & Python)
`@{language}SurfaceNamer` A subclass of `SurfaceNamer` with extra lanaguge-dependent methods

In this case:
For the language-agnostic transformers or any transformer that is used by multiple languages, we can just pass `SurfaceNamer`.

So the difference between this approach with the current approach is: Currently we put all methods into `SurfaceNamer` by default. My approach is that the `SurfaceNamer` class will only contain the common methods by default, and we can add methods to `SurfaceNamer` on demand (e.g. Luke can move some methods to `SurfaceNamer` to make things easier for Php & Python even though they are not used by all languages)

**Comment by garrettjonesgoogle** [comment]
How many methods actually fall under the case of only being used in a language-specific transformer (and aren't slated to move to a language-agnostic one)?

**Comment by pongad** [comment]
I had this same problem a while back. I agree the class is too large. On the other hand, it's not so clear what constitutes "common methods" and "language-specific methods". We are working in 7 languages, many methods are needed in maybe 4 of them.

**Comment by shinfan** [comment]
Yes, it is hard to tell which methods are "language-specific" but we seem all agree that the class is too large. I can take a deeper look at this and hopefully put up a PR for review so we can evaluate this thing better.

**Comment by eoogbe** [comment]
Would the decorator pattern help?

For example, say the `PhpGapicSurfaceTransformer` needs to pass an `ApiMethodSurfaceNamer` interface to the `ApiMethodTransformer`. It would wrap the `PhpSurfaceNamer` in a `PhpApiMethodSurfaceNamer` using `new PhpApiMethodSurfaceNamer(context.getNamer())`.

So each context that uses the `SurfaceNamer` gets its own interface and language-specific or context-specific (e.g. `DynamicLangApiMethodSurfaceNamer`) implementations. The `SurfaceNamer` is converted to an interface, and each language-specific one is changed to implement the interface.

Given the sheer number of contexts a `SurfaceNamer` is expected in and that they don't expect the same interface, we should reify that in the code that these different contexts expect different interfaces by literally using different interfaces.

**Comment by garrettjonesgoogle** [comment]
There are a couple issues that have prevented me from going that route. If I understand your proposal correctly:

* The interface of `SurfaceNamer` now needs to be repeated by L languages x T transformer types; if L = 7 and T ~ 10, that means 70 times. 
* There would now be potentially T times as many surface namer classes

While it can be challenging to find functionality in a large file, it is even harder to find it across T times as many files.
