### ISSUE TITLE
Generate more idiomatic name parsing methods

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator#975]
## What
The generator is generating methods that have method names that are _"incredibly"_ long. More idiomatic methods should be created to parse names.

### Example
```ruby
# Parses the monitored_resource_descriptor from a monitored_resource_descriptor resource.
# @param monitored_resource_descriptor_name [String]
# @return [String]
def self.match_monitored_resource_descriptor_from_monitored_resource_descriptor_name monitored_resource_descriptor_name
  MONITORED_RESOURCE_DESCRIPTOR_PATH_TEMPLATE.match(monitored_resource_descriptor_name)["monitored_resource_descriptor"]
end
```

#### Change from this
```ruby
client.match_project_from_group_name "[GROUP]"
client.match_project_from_metric_descriptor_name "[METRIC_DESCRIPTOR]"
client.match_project_from_monitored_resource_descriptor_name "[MONITORED_RESOURCE]"
```

#### To this
```ruby
client.match_project :group "[GROUP]"
client.match_project :metric_descriptor "[METRIC_DESCRIPTOR]"
client.match_project :monitored_resource_descriptor_name "[MONITORED_RESOURCE]"
```

- [x] PHP
- [x] Python
- [x] Ruby
- [ ] NodeJS

**Comment by landrito** [comment]
## Suggested solution

#### Change from this
```ruby
client.match_project_from_group_name "[GROUP]"
client.match_project_from_metric_descriptor_name "[METRIC_DESCRIPTOR]"
client.match_project_from_monitored_resource_descriptor_name "[MONITORED_RESOURCE]"
```

#### To this
```ruby
client.match_project :group "[GROUP]"
client.match_project :metric_descriptor "[METRIC_DESCRIPTOR]"
client.match_project :monitored_resource_descriptor_name "[MONITORED_RESOURCE]"
```

**Comment by eoogbe** [comment]
Note that, despite the reduction of function length, the line length difference in the suggested solution is minimal. I don't think it solves the problem, and in fact it introduces a new one. What should we return if the developer passes in a dictionary with multiple entries? If we handle only the first entry, we’re misleading the developer. If we handle all the entries, returning some sort of dictionary, then we have to add much more complexity for very little value. Regardless of how we handle the problem of multiple entries, using a dictionary parameter obscures the point of the function.

**Comment by eoogbe** [comment]
This has been solved in Java and C# by using objects. The C# solution is pretty clear:
1. Create the resource wrapper classes
2. reopen the request classes and have them accept the new classes in their constructor

This solution will work for Ruby (and I think Node.js), but in the other languages, you can't reopen classes. You also can't reopen classes in Java, and for the life of me I can't figure out where the Java resource objects are implemented. They seem to come out of nowhere and just work. Can we do the same for PHP and Python?

**Comment by garrettjonesgoogle** [comment]
@michaelbausor implemented the Java magic for this.

**Comment by remi** [comment]
Another tool to consider is shortening identifiers such as `monitored_resource_descriptor_name` to `resource`.

The Logging library uses `resource` as a name for a `monitored_resource`: [Writing Log Entries](monitored_resource_descriptor_name)

**Comment by remi** [comment]
Can you show an example of what the C# solution that you're referring to, which you like?

Looking through the C# [Monitoring client](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Monitoring.V3/api/Google.Cloud.Monitoring.V3.MetricService.MetricServiceBase.html#Google_Cloud_Monitoring_V3_MetricService_MetricServiceBase_ListMetricDescriptors_Google_Cloud_Monitoring_V3_ListMetricDescriptorsRequest_Grpc_Core_ServerCallContext_), but I haven't used the C# generated yet 😄

**Comment by eoogbe** [comment]
@remi The link is broken

The resource name generation for c#: https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicClientTransformer.java#L127

**Comment by eoogbe** [comment]
Test example: https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/csharp_gapic_resourcenames_library.baseline

**Comment by remi** [comment]
Whoops ~  [Writing Log Entries](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.25.0/google/cloud/logging#writing-log-entries)

Sweet, thanks!

**Comment by remi** [comment]
What does the developer surface look like for the end user for one of these calls?

**Comment by eoogbe** [comment]
I think this uses the gapic but unsure: https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Monitoring.V3/index.html#list-metric-descriptors

**Comment by eoogbe** [comment]
Going back to the name-shortening:
Because the functions are in the form `match_{potentially long thing}_from_{potentially long thing2}_name` and thing2 gets repeated for every field in the path, it would be hard to come up with unambiguous yet short names in many cases. Even `monitored_resource` => `resource` still produces `def match_resource_descriptor_from_resource_descriptor_name resource_descriptor_name` (84 characters). We have to get rid of part that requires two potentially long names in one line. Resource objects will do that.

**Comment by remi** [comment]
+1

**Comment by remi** [comment]
Are these `match_x_from_y` methods only used internally by the client library?  Should they actually be public at all?  IIUC these feel like internal private helper methods for parsing display names from namespaced resource strings.

From a quick skim of the C# client, I don't see any similar functionality being exposed.  And I can't think of a developer use case.

**Comment by eoogbe** [comment]
The `match_x_from_y` functions are intended to be used by the developer. As far as I know, they aren't used internally. They allow the developer to parse resource paths into the field parts. For example:
```ruby
widget = client.get_widget # params...
puts widget.name  # projects/foo/topics/bar/widgets/baz
project_name = client.match_project_from_widget_name widget.name
puts project_name # foo
```

The C# client doesn't have `match_x_from_y`. (Or maybe it does, but doesn't really use it. Moot either way.) Instead, it has resource classes. From the earlier link, `ProjectName` is a resource class.

**Comment by michaelbausor** [comment]
PHP updated format and parse methods in this PR: https://github.com/googleapis/toolkit/pull/1485

**Comment by landrito** [comment]
These methods were removed from ruby in https://github.com/googleapis/gapic-generator/pull/1375

**Comment by jbolinger** [comment]
These languages all have new generators. If this is still relevant please open an issue on any or all of the following:

https://github.com/googleapis/gapic-generator-ruby
https://github.com/googleapis/gapic-generator-python
https://github.com/googleapis/gapic-generator-typescript
etc.
