### ISSUE TITLE
Ruby: Consider generating methods on the resource level.

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator#976]
## What
It was pointed out that methods like `getResource`, `listResource`, and `deleteResource` are not idiomatic in ruby. 

## Suggested solution
The `getter` and `lister` methods should be methods on a resource class and the `deletion` method should be an instance method of a descriptor.

### Example
```ruby
# Listing a resource
client.resource.each do |resource|
  puts resource.name
end

# Getting a resource
myResource = client.resource "[resource_name]"

# Deleting a resource
myResource.delete
```

**Comment by jcanizales** [comment]
Very old conversation with plenty of baggage :) I hope we finally do it.

**Comment by vchudnov-g** [comment]
@landrito @jbolinger Is this still an issue? Can we close it?

**Comment by landrito** [comment]
This is a very old discussion that I think we can close, we can reopen in googleapis/gapic-generator-ruby if needed.
