### ISSUE TITLE
Add more descriptions of constructor parameters

### ISSUE THREAD

**Issue by jmuk** [googleapis/gapic-generator#977]
Through some internal feedback; the constructor has lots of the parameters and they will confuse the users what are the right values to be specified.

In reality, all of them are optional and it connects to the default parameters without specifying any of them, but probably the existing documentation isn't clear enough to say so.

Suggestions:

- mention the default value for each of the parameters. This will clarify that they are optional.
- add a sample code section to the constructor comment which shows that a client can be created without any parameters.

Affects Python, Ruby, Node at least. cc/ @bjwatson @swcloud @lukesneeringer 

- [ ] Python
- [ ] Ruby
- [ ] Node

**Comment by eoogbe** [comment]
cc/ @geigerj for Ruby
@lukesneeringer Can you add a priority?

**Comment by eoogbe** [comment]
@geigerj @lukesneeringer @alexander-fenster Is this still relevant for your languages? Can you add a priority?

**Comment by geigerj** [comment]
These seem like valuable but non-urgent doc improvements. Setting as P2.

**Comment by jbolinger** [comment]
These languages all have new generators. If this is still relevant please open an issue on any or all of the following:

https://github.com/googleapis/gapic-generator-ruby
https://github.com/googleapis/gapic-generator-python
https://github.com/googleapis/gapic-generator-typescript
