### ISSUE TITLE
Refactor TestCaseView to include ApiMethodView

### ISSUE THREAD

**Issue by swcloud** [googleapis/gapic-generator#990]
When generating unit test and smoke test, TestCaseView has been passed into the snip file. However, it contains lots of redundant information with ApiMethodView (such as InitCodeView) which is used by sample gen. TestCaseView stores extra test-related data, however, the data and snip code that needs to be used to generate api method call have already been handled by ApiMethodView. So if TestCaseView includes ApiMethodView, then the snip code to generate samples can be directly used by smoke_test.snip.

**Comment by eoogbe** [comment]
@shinfan @garrettjonesgoogle Can you add a priority?

**Comment by hkdevandla** [comment]
Obsolete.
