### ISSUE TITLE
Flattening patterns for bidi streaming

### ISSUE THREAD

**Issue by jmuk** [googleapis/gapic-generator#996]
We see multiple APIs which define the inputs for bidi streaming as fist initialization message / multiple message bodies. Some examples are Speech's streaming recognize (audio config / audio content) and Pubsub's streaming pull (initially list of subscriptions / further acks).

To address this pattern, it seems useful to change the surface for bidi streaming as:
- the method itself takes a parameter, which builds the initial message
- the returned stream will accept a write method to build the further messages

The idea of the configuration will be:
```yaml
- name: StreamingPull
  initial_request:
    name: StartStreamingPullRequest
    flattening:
       ...
  stream_request:
    name: IncrementalStreamingPullRequest
    flattening:
       ...
```

The generated surface will be:
```csharp
var streamingPull = service.StartStreamingPull("my-subscription", 10);
streamingPull.WriteAsync(new[] { "ack1", "ack2", "ack3" });
```

This pattern will be beneficial to some languages, including C#, Java, and Node.JS.

**Comment by geigerj** [comment]
@jmuk What does this look like if you want to specify more fields than just the `ack_ids` field on one of the non-initial requests in the stream?

**Comment by jmuk** [comment]
@chrisdunelm @garrettjonesgoogle, do you have ideas? I think they will come as flattened parameters, i.e. `streamingPull.WriteAsync(ack_ids, other_param)`.

**Comment by chrisdunelm** [comment]
Some questions (apologies if some of these are obvious!):
* What defines the content of the "StartStreamingPullRequest" and "IncrementalStreamingPullRequest" messages? I.e. which fields of the underlying proto will be contained in each. Will this be specified in the gapic config?
* And are these going to be full protos? Or just plain (language-specific) objects?
  * If protos, how/where will these be defined/generated?
* What about fields that can be used in both the initial request, and following requests? E.g. [stream_ack_deadline_seconds](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L512) in StreamingPullRequest. Will this be contained in both the Start... and Incremental... messages?
* Presumably multiple flattenings will be supported for initial and incremental calls? E.g. in pubsub two flattenings may be useful for incremental messages: ack_ids alone; and modify_deadline_seconds with modify_deadline_ack_ids together.
* Are extra messages required? Or could this just be a flattening, with two sets of flattenings supported (initial and incremental), rather than just one for unary calls?
  * This would add less complexity.
  * If a potential flattening would have too many parameters, then just fallback to the underlying proto, as we do already for unary calls. I would expect this would be reasonably rare.
* Presuambly this will also support server-streaming rpcs, not just bidi?

**Comment by jmuk** [comment]
What I wrote above is my summary for the internal discussion between you and @garrettjonesgoogle -- I believe @garrettjonesgoogle would have more detailed answers, but:

> - What defines the content of the "StartStreamingPullRequest" and "IncrementalStreamingPullRequest" messages? I.e. which fields of the underlying proto will be contained in each. Will this be specified in the gapic config?

Should be in the gapic config, at the `...` part in the sample yaml above.

> - And are these going to be full protos? Or just plain (language-specific) objects?
>    - If protos, how/where will these be defined/generated?

You meant "these" for the parameters like `"my-subscription"`, `10`, or acks, right? I believe that they should be in the same rule as the normal flattened parameters. They can be full protos if the field definition is so, but usually plain objects, I think.

> - What about fields that can be used in both the initial request, and following requests? E.g. stream_ack_deadline_seconds in StreamingPullRequest. Will this be contained in both the Start... and Incremental... messages?

I think toolkit should allow having the same field on both initial and stream requests. In that case, `Start...` and `Write...` method should accept that field.

> - Presumably multiple flattenings will be supported for initial and incremental calls? E.g. in pubsub two flattenings may be useful for incremental messages: ack_ids alone; and modify_deadline_seconds with modify_deadline_ack_ids together.

Hmmm. I haven't thought that details.  An idea is to allow specifying the name for each of the flattened groups, such as:
```yaml
stream_requests:
  flattening:
    groups:
      ack: [ack_ids]
      modify_deadline: [modify_deadline_seconds, modify_deadline_ack_ids]
```

Then use the group name `ack` or `modify` for the method name (or its prefix/suffix) (i.e. `stream.ack(ack_ids)` vs `stream.modifyDeadline(modify_deadline_seconds, modify_deadline_ack_ids)`).

> - Are extra messages required? Or could this just be a flattening, with two sets of flattenings supported (initial and incremental), rather than just one for unary calls?
>    - This would add less complexity.
>    - If a potential flattening would have too many parameters, then just fallback to the underlying proto, as we do already for unary calls. I would expect this would be reasonably rare.

I don't think extra messages are required -- I didn't know the thing around unary calls as you explained (possibly because I'm not familiar with C# codegen). Can you explain a bit more?

> - Presuambly this will also support server-streaming rpcs, not just bidi?

I am not sure how server-streaming can be affected. Such methods receive a single message once, and then multiple messages will come. This discussion will not be affected.

Client-streaming -- client sends multiple messages and then return a single response at the end of the stream -- *could* be affected, but we are not sure what is the typical pattern on the client-streaming (actually there's no client-streaming methods in googleapis repo yet). I personally think like client-streaming requests are more monotonic and do not need separating initial / other requests, but that's just my wild guess.

**Comment by garrettjonesgoogle** [comment]
>> - What defines the content of the "StartStreamingPullRequest" and "IncrementalStreamingPullRequest" messages? I.e. which fields of the underlying proto will be contained in each. Will this be specified in the gapic config?
>
>Should be in the gapic config, at the `...` part in the sample yaml above.

Actually, the original proposal was to handcraft additional proto declarations for the partial messages.

```
message StartStreamingPullRequest {
	  string subscription = 1;
	  int32 stream_ack_deadline_seconds = 5;
}

message IncrementalStreamingPullRequest {
	  repeated string ack_ids = 2;
	  repeated int32 modify_deadline_seconds = 3;
	  repeated string modify_deadline_ack_ids = 4;
}
```

The fields would have to match the original exactly.

Using gapic config is an interesting alternative, but then we need to figure out how to do the following:

1. Generate a proto file from the GAPIC declaration
2. Run the proto compiler on the generated .proto declarations from within toolkit (we don't have support for running proto generation under toolkit yet, right?)

>> - And are these going to be full protos? Or just plain (language-specific) objects?
>>    - If protos, how/where will these be defined/generated?
>
>You meant "these" for the parameters like `"my-subscription"`, `10`, or acks, right? I believe that they should be in the same rule as the normal flattened parameters. They can be full protos if the field definition is so, but usually plain objects, I think.

I think @chrisdunelm means the start/incremental messages for "these." My proposal is to have them be full protos. As for how they are defined, my original proposal was to handwrite them, although as I say above, generating them might be fine too.

The parameters like `"my-subscription"`, `10`, or acks would be part of the flattening config.

>> - What about fields that can be used in both the initial request, and following requests? E.g. stream_ack_deadline_seconds in StreamingPullRequest. Will this be contained in both the Start... and Incremental... messages?
>
>I think toolkit should allow having the same field on both initial and stream requests. In that case, `Start...` and `Write...` method should accept that field.

Agreed.

>> - Presumably multiple flattenings will be supported for initial and incremental calls? E.g. in pubsub two flattenings may be useful for incremental messages: ack_ids alone; and modify_deadline_seconds with modify_deadline_ack_ids together.
>
>Hmmm. I haven't thought that details.  An idea is to allow specifying the name for each of the flattened groups, such as:
> [clipped]

That's an interesting idea! This could actually be applied generally to flattening configurations for simple API methods. The names could be used by languages which have no method overloading, and they could be ignored by languages with method overloading (which could use the same name for all of the methods). 

Although, for this case, you could also consider using just a single entry point in languages with no method overloading but support default values, which is the status quo for normal API methods in Python/etc.

>> - Are extra messages required? Or could this just be a flattening, with two sets of flattenings supported (initial and incremental), rather than just one for unary calls?
>>    - This would add less complexity.
>>    - If a potential flattening would have too many parameters, then just fallback to the underlying proto, as we do already for unary calls. I would expect this would be reasonably rare.
>
>I don't think extra messages are required -- I didn't know the thing around unary calls as you explained (possibly because I'm not familiar with C# codegen). Can you explain a bit more?

The issue with supporting this only through flattening is the case when new parameters get added. This either explodes the surface (a new flattening each time a new parameter is added) or creates a usability cliff (use the nice flattening or the original request type which allows for more mistakes). 

I would argue that there are languages where building this only on flattening creates more complexity; languages which don't use flattening for simple API methods would have to make an exception for streaming methods and use flattening config there. That setup is harder to understand.

Regarding flattenings for unary calls: It's actually already possible to have multiple flattenings for a unary call (what I've been calling "simple API methods" - single request/single response).

**Comment by eoogbe** [comment]
@garrettjonesgoogle Can you add a priority?

**Comment by eoogbe** [comment]
@garrettjonesgoogle Can you assign someone to this P1 issue?

**Comment by eoogbe** [comment]
@garrettjonesgoogle Had to unassign shinfan as he has left the team. Can you assign this issue again?

**Comment by hkdevandla** [comment]
Obsolete.
